import * as vscode from 'vscode';

export const noCsprojFound = vscode.l10n.t('No AppHost found in the current workspace.');
// l10n.t only substitutes primitives, so passing an Error left the message as the literal "Error: {0}".
export const errorMessage = (error: unknown) => vscode.l10n.t('Error: {0}', error instanceof Error ? error.message : String(error));
export const yesLabel = vscode.l10n.t('Yes');
export const noLabel = vscode.l10n.t('No');
export const directUrl = (url: string) => vscode.l10n.t('Direct: {0}', url);
export const codespacesUrl = (url: string) => vscode.l10n.t('Codespaces: {0}', url);
export const directLink = vscode.l10n.t('Open local URL');
export const codespacesLink = vscode.l10n.t('Open codespaces URL');
export const openAspireDashboard = vscode.l10n.t('Launch Aspire Dashboard');
export const settingsLabel = vscode.l10n.t('Settings');
export const aspireDashboard = vscode.l10n.t('Aspire Dashboard');
export const noWorkspaceOpen = vscode.l10n.t('No workspace is open. Please open a folder or workspace before running this command.');
export const failedToShowPromptEmpty = vscode.l10n.t('Failed to show prompt, text was empty.');
export const rpcServerAddressError = vscode.l10n.t('Failed to get RPC server address. The extension may not function correctly.');
export const rpcServerError = (err: any) => vscode.l10n.t('RPC server error: {0}.', err);
export const incompatibleAppHostError = vscode.l10n.t('The AppHost is not compatible. Consider upgrading the AppHost or Aspire CLI.');
export const aspireHostingSdkVersion = (version: string) => vscode.l10n.t('Aspire Hosting SDK Version: {0}.', version);
export const aspireCliVersion = (version: string) => vscode.l10n.t('Aspire CLI Version: {0}.', version);
export const requiredCapability = (capability: string) => vscode.l10n.t('Required capability: {0}.', capability);
export const aspireTerminalName = vscode.l10n.t('Aspire terminal');
export const aspireTerminalClosedBeforeProcessStarted = vscode.l10n.t('Aspire terminal closed before its process started.');
export const aspireTerminalProcessFailedToStart = vscode.l10n.t('Aspire terminal process failed to start.');
export const createWithAspirePlaceholder = vscode.l10n.t('Choose how to set up Aspire');
export const createNewAspireAppLabel = vscode.l10n.t('Create a new Aspire app');
export const createNewAspireAppDescription = vscode.l10n.t('Start a greenfield application in a new directory using an Aspire template.');
export const addAspireToWorkspaceLabel = vscode.l10n.t('Add Aspire to this workspace');
export const addAspireToWorkspaceDescription = vscode.l10n.t('Add an AppHost and Aspire configuration alongside applications already in this workspace.');
export const aspireCliPathEnvironmentDescription = vscode.l10n.t('Forwards aspire.aspireCliExecutablePath as AspireCliPath so MSBuild bundle resolution and integrated terminals use the configured Aspire CLI.');
export const configuredCliPathRejected = (configuredPath: string) => vscode.l10n.t('The configured Aspire CLI path could not be used, so a different Aspire CLI is running instead: {0}. Check that aspire.aspireCliExecutablePath points to the aspire executable itself and that it runs.', configuredPath);
export const configuredCliPathRejectedOpenSetting = vscode.l10n.t('Open Setting');
export const installCliPlaceholder = vscode.l10n.t('Select how to install the Aspire CLI');
export const installCliViewAllOptions = vscode.l10n.t('View all installation options');
export const installCliViewAllOptionsDescription = vscode.l10n.t('Open the installation guide (includes the install script)');
export const installCliDailyBuild = vscode.l10n.t('Daily build (dev)');
export const installCliDailyBuildDescription = vscode.l10n.t('Latest build from main via the install script');
export const terminalCommandArgumentControlCharacters = vscode.l10n.t('Aspire terminal command arguments cannot contain control characters.');
export const terminalCommandUnsafeLiteral = vscode.l10n.t('Aspire terminal command syntax can only contain command names and flags.');
export const cmdShimPercentArgument = vscode.l10n.t('Arguments containing %NAME% cannot be forwarded through a Windows .cmd or .bat shim, because cmd.exe expands them before the Aspire CLI receives the value. Configure aspire.aspireCliExecutablePath to point at aspire.exe instead of the .cmd shim and try again.');
export const azureFunctionsUnsupportedTaskShell = vscode.l10n.t('The configured VS Code task shell is not supported for Azure Functions launch arguments. Configure terminal.integrated.automationProfile to use PowerShell, Command Prompt, bash, zsh, fish, or WSL.');
export const azureFunctionsCmdPercentArgument = vscode.l10n.t('Azure Functions launch arguments containing "%" are not supported by cmd.exe. Configure terminal.integrated.automationProfile.windows to use PowerShell and try again.');
export const azureFunctionsCmdDelayedExpansion = vscode.l10n.t('Azure Functions launch arguments containing "!" are not supported by cmd.exe because delayed environment variable expansion may change them. Configure terminal.integrated.automationProfile.windows to use PowerShell and try again.');
export const azureFunctionsInvalidProcessId = (processId: string) => vscode.l10n.t('Azure Functions returned an invalid worker process ID: {0}.', processId);
export const azureFunctionsTaskExitedBeforeStartup = (exitCode: number) => vscode.l10n.t('Azure Functions task exited with code {0} before startup completed.', exitCode);
export const azureFunctionsHostStartupTimedOut = (timeoutSeconds: number, port: number) => vscode.l10n.t('Timed out after {0} seconds waiting for the Azure Functions host to start on port {1}.', timeoutSeconds, port);
export const azureFunctionsWorkerStartupTimedOut = (timeoutSeconds: number) => vscode.l10n.t('Timed out after {0} seconds waiting for the Azure Functions worker process to start.', timeoutSeconds);
export const aspireOutputChannelName = vscode.l10n.t('Aspire Extension');
export const fieldRequired = vscode.l10n.t('This field is required.');
export const runProject = (projectName: string) => vscode.l10n.t('Run {0}', projectName);
export const debugProject = (projectName: string) => vscode.l10n.t('Debug {0}', projectName);
export const watchProject = (projectName: string, projectType: string) => vscode.l10n.t('Watch {0} ({1})', projectName, projectType);
export const noCsharpBuildTask = vscode.l10n.t('No C# Dev Kit build task found, defaulting to dotnet CLI. Maybe the workspace hasn\'t finished loading?');
export const noWatchTask = vscode.l10n.t('No watch task found. Please ensure a watch task is defined in your workspace.');
export const buildFailedWithExitCode = (exitCode: number | string) => vscode.l10n.t('Build failed with exit code {0}.', exitCode);
export const noOutputFromMsbuild = vscode.l10n.t('No output from msbuild.');
export const failedToGetTargetPath = (err: string) => vscode.l10n.t('Failed to get TargetPath: {0}.', err);
export const unsupportedResourceType = (type: string) => vscode.l10n.t('Attempted to start unsupported resource type: {0}.', type);
export const rpcServerNotInitialized = vscode.l10n.t('RPC server is not initialized.');
export const extensionContextNotInitialized = vscode.l10n.t('Extension context is not initialized.');
export const aspireDebugSessionNotInitialized = vscode.l10n.t('Aspire debug session is not initialized');
export const errorRetrievingAppHosts = vscode.l10n.t('Error retrieving AppHosts in the current workspace. Debug options may be incomplete.');
export const launchingWithDirectory = (sessionType: 'run' | 'debug', appHostPath: string) => sessionType === 'run'
    ? vscode.l10n.t('Launching Aspire run session using directory {0}: attempting to determine effective AppHost...', appHostPath)
    : vscode.l10n.t('Launching Aspire debug session using directory {0}: attempting to determine effective AppHost...', appHostPath);
export const launchingWithAppHost = (sessionType: 'run' | 'debug', appHostPath: string) => sessionType === 'run'
    ? vscode.l10n.t('Launching Aspire run session for AppHost {0}...', appHostPath)
    : vscode.l10n.t('Launching Aspire debug session for AppHost {0}...', appHostPath);
export const disconnectingFromSession = vscode.l10n.t('Disconnecting from Aspire debug session... Child processes will be stopped.');
export const processExitedWithCode = (code: number | string) => vscode.l10n.t('Process exited with code {0}.', code);
export const failedToStartPythonProgram = (errorMessage: string) => vscode.l10n.t('Failed to start Python program: {0}.', errorMessage);
export const csharpSupportNotEnabled = vscode.l10n.t('C# support is not enabled in this workspace. This project should have started through the Aspire CLI.');
export const failedToStartProject = (errorMessage: string) => vscode.l10n.t('Failed to start project: {0}.', errorMessage);
export const dcpServerNotInitialized = vscode.l10n.t('DCP server not initialized - cannot forward debug output.');
export const appHostSessionTerminated = vscode.l10n.t('The AppHost process has terminated. To view console output, select the AppHost session from the debug console dropdown.');
export const debugSessionsFailedToStop = (count: number, reasons: string) => vscode.l10n.t('{0} debug sessions failed to stop: {1}', count, reasons);
export const debugSessionStartTimedOut = (sessionName: string, seconds: number) => vscode.l10n.t("Timed out after {1} seconds waiting for debug session '{0}' to start.", sessionName, seconds);
export const debugSessionStopTimedOut = (sessionName: string, seconds: number) => vscode.l10n.t("Timed out after {1} seconds waiting for debug session '{0}' to stop.", sessionName, seconds);
export const invalidTokenProvided = vscode.l10n.t('Invalid token provided.');
export const noWorkspaceFolder = vscode.l10n.t('No workspace folder found.');
export const selectWorkspaceFolderForAspireCommand = vscode.l10n.t('Select the workspace folder for the Aspire command');
export const aspireConfigExists = vscode.l10n.t('Aspire launch configuration already exists in launch.json.');
export const failedToConfigureLaunchJson = (error: any) => vscode.l10n.t('Failed to configure launch.json: {0}.', error);
export const defaultConfigurationName = vscode.l10n.t('Aspire: Launch default AppHost');
export const defaultConfigurationNameForWorkspaceFolder = (workspaceFolderName: string, workspaceFolderUri: string) => vscode.l10n.t('Aspire: Launch default AppHost ({0}: {1})', workspaceFolderName, workspaceFolderUri);
export const debugSessionAlreadyExists = (id: string) => vscode.l10n.t('A debug session is already active for id {0}.', id);
export const selectDashboardLaunchBehavior = vscode.l10n.t('Select what should happen with the Aspire Dashboard when this launch configuration starts');
export const dashboardLaunchNoneLabel = vscode.l10n.t('Do not open the dashboard');
export const dashboardLaunchNoneDescription = vscode.l10n.t('The dashboard URL is still printed in the terminal and available from the Aspire panel.');
export const dashboardLaunchNotificationLabel = vscode.l10n.t('Show a notification');
export const dashboardLaunchNotificationDescription = vscode.l10n.t('Show a notification with a link to open the dashboard.');
export const dashboardLaunchExternalBrowserLabel = vscode.l10n.t('Open in external browser');
export const dashboardLaunchExternalBrowserDescription = vscode.l10n.t('Open the dashboard in the system default browser.');
export const dashboardLaunchIntegratedBrowserLabel = vscode.l10n.t('Open in VS Code');
export const dashboardLaunchIntegratedBrowserDescription = vscode.l10n.t("Open the dashboard in VS Code's integrated browser.");
export const dashboardLaunchChromeLabel = vscode.l10n.t('Debug with Chrome');
export const dashboardLaunchChromeDescription = vscode.l10n.t('Launch Chrome as a child debug session.');
export const dashboardLaunchEdgeLabel = vscode.l10n.t('Debug with Microsoft Edge');
export const dashboardLaunchEdgeDescription = vscode.l10n.t('Launch Microsoft Edge as a child debug session.');
export const dashboardLaunchFirefoxLabel = vscode.l10n.t('Debug with Firefox');
export const dashboardLaunchFirefoxDescription = vscode.l10n.t('Launch Firefox as a child debug session.');
export const dashboardLaunchBehaviorChanged = vscode.l10n.t('The Aspire Dashboard does not open automatically. Open it from the Aspire panel anytime, or configure a launch behavior.');
export const changelogLabel = vscode.l10n.t('Changelog');
export const processExceptionOccurred = (error: string, command: string) => vscode.l10n.t('Encountered an exception ({0}) while running the following command: {1}.', error, command);

// Aspire panel strings
export const pidDescription = (pid: number) => vscode.l10n.t('PID: {0}', pid);
export const dashboardLabel = vscode.l10n.t('Dashboard');
export const errorFetchingAppHosts = (error: string) => vscode.l10n.t('Error fetching running AppHosts: {0}', error);
export const aspireCliCommandFailed = (command: string, exitCode: string, output: string) => vscode.l10n.t('{0} exited with code {1}{2}', command, exitCode, output);
export const aspireCliCommandTimedOut = (timeoutMs: number) => vscode.l10n.t('timed out after {0}ms', timeoutMs);
export const aspireCliOutputParseFailed = (command: string, error: string) => vscode.l10n.t('Failed to parse {0} output: {1}', command, error);
export const aspireCommandOutputTruncated = (limit: number) => vscode.l10n.t('[Aspire command output truncated to {0} characters. Showing the beginning and end of the output.]', limit);
export const appHostPathMustBeNonEmptyAbsolute = vscode.l10n.t('appHostPath must be a non-empty absolute path');
export const aspireDescribeMinimumVersion = '13.2.0';
export const aspireCliDescribeNotSupported = (version: string) => vscode.l10n.t('Workspace resources require Aspire CLI {0} or newer. Update the Aspire CLI and refresh the Aspire panel.', version);
export const appHostDescribeMayNotBeSupported = (version: string) => vscode.l10n.t('No workspace resources were returned. Workspace resources require the AppHost to reference Aspire.Hosting {0} or newer.', version);
export const resourcesGroupLabel = vscode.l10n.t('Resources');
export const commandsLabel = vscode.l10n.t('Commands');
export const noCommandsAvailable = vscode.l10n.t('No commands available for this resource.');
export const selectCommandPlaceholder = vscode.l10n.t('Select a command to execute');
export const resourceCommandArgumentsTitle = (command: string) => vscode.l10n.t('Run {0}', command);
export const resourceCommandArgumentInputTitle = (command: string, input: string) => vscode.l10n.t('{0}: {1}', command, input);
export const resourceCommandCustomChoice = (value: string) => vscode.l10n.t('Use "{0}"', value);
export const resourceCommandCustomChoiceDescription = vscode.l10n.t('Custom value');
export const resourceCommandDynamicInputsUnsupported = vscode.l10n.t('This command has dynamic inputs that the Aspire extension cannot prompt for yet. Run it from the Aspire Dashboard or Aspire CLI instead.');
export const resourceCommandDynamicInputsFailed = vscode.l10n.t('Failed to load dynamic command inputs. Run this command from the Aspire Dashboard or Aspire CLI instead.');
export const resourceCommandLoadingDynamicInputs = vscode.l10n.t('Updating command inputs...');
export const resourceCommandSecretWarning = vscode.l10n.t('This command has secret arguments. Values are masked while you enter them, but they are passed to the Aspire CLI as command-line arguments and may briefly be visible to other processes on this machine.');
export const resourceCommandContinue = vscode.l10n.t('Continue');
export const resourceCommandDontShowAgain = vscode.l10n.t("Don't show again");
export const resourceCommandInvalidNumber = vscode.l10n.t('Enter a number using invariant culture, for example 1, -1.5, or 1e3.');
export const resourceCommandMaxLength = (length: number) => vscode.l10n.t('Value must be {0} characters or fewer.', length);
export const resourceCommandDisabledDescription = vscode.l10n.t('(disabled)');
export const resourceCommandRunning = (command: string, resource: string) => vscode.l10n.t("Running '{0}' on '{1}'...", command, resource);
export const resourceCommandSucceeded = (command: string, resource: string) => vscode.l10n.t("Command '{0}' completed on '{1}'.", command, resource);
export const resourceCommandFailed = (command: string, resource: string, error: string) => vscode.l10n.t("Command '{0}' on '{1}' failed: {2}", command, resource, error);
export const resourceCommandFailedNoDetail = (command: string, resource: string) => vscode.l10n.t("Command '{0}' on '{1}' failed.", command, resource);
export const resourceCommandCliNotInstalled = (error: string) => vscode.l10n.t('The Aspire CLI could not be started: {0}', error);
export const resourceCommandOpenCliLog = vscode.l10n.t('Open CLI Log');
export const resourceCommandOpenAppHostLog = vscode.l10n.t('Open AppHost Log');
export const resourceCommandLogOpenFailed = (path: string, error: string) => vscode.l10n.t('Failed to open resource command log file {0}: {1}', path, error);
export const resourceCommandOutputOpenFailed = (error: string) => vscode.l10n.t('The command completed, but its output could not be opened: {0}', error);
export const selectDashboardPlaceholder = vscode.l10n.t('Select a dashboard to open');
export const dashboardUrlNotFound = vscode.l10n.t('No Aspire Dashboard URL is available. Start an AppHost and try again.');
export const dashboardUrlUnsupported = vscode.l10n.t('The Aspire Dashboard URL must use http or https.');
export const workspaceAppHostLabel = vscode.l10n.t('Workspace AppHost');
export const workspaceAppHostsGroupLabel = vscode.l10n.t('Workspace AppHosts');
export const runningAppHostsGroupLabel = vscode.l10n.t('Running AppHosts');
export const appHostOpenSourceActionLabel = vscode.l10n.t('Open AppHost source');
export const appHostRunActionLabel = vscode.l10n.t('Run AppHost');
export const appHostDebugActionLabel = vscode.l10n.t('Debug AppHost');
export const appHostDeployActionLabel = vscode.l10n.t('Deploy AppHost');
export const appHostPublishActionLabel = vscode.l10n.t('Publish AppHost');
export const appHostRunPipelineStepActionLabel = vscode.l10n.t('Run pipeline step');
export const appHostDebugPipelineStepActionLabel = vscode.l10n.t('Debug pipeline step');
export const appHostPathLabel = vscode.l10n.t('Path');
export const appHostPathCopiedToClipboard = vscode.l10n.t('AppHost path copied to clipboard.');
export const appHostPathInvalid = vscode.l10n.t('Could not determine the AppHost path to copy.');
export const appHostStartingDescription = vscode.l10n.t('Starting...');
export const appHostStoppingDescription = vscode.l10n.t('Stopping...');
export const appHostDeployingDescription = vscode.l10n.t('Deploying...');
export const appHostPublishingDescription = vscode.l10n.t('Publishing...');
export const appHostRunningPipelineStepDescription = vscode.l10n.t('Running pipeline step...');
export const appHostDebuggingPipelineStepDescription = vscode.l10n.t('Debugging pipeline step...');
export const appHostDiscoveryProgress = vscode.l10n.t('Discovering AppHosts...');
export const resourceCountDescription = (count: number) => vscode.l10n.t('({0} resources)', count);
export const appHostCandidateDescription = (language: string, status: string) => vscode.l10n.t('{0} · {1}', language, status);
export const workspaceViewSelectedSingleAppHost = (language?: string) => language
    ? vscode.l10n.t('Workspace view selected because aspire ls found one buildable {0} AppHost.', language)
    : vscode.l10n.t('Workspace view selected because aspire ls found one buildable AppHost.');
export const workspaceViewSelectedMultipleAppHosts = (count: number) => vscode.l10n.t('Workspace view selected because aspire ls found {0} buildable AppHosts.', count);
export const tooltipType = (type: string) => vscode.l10n.t('Type: {0}', type);
export const tooltipState = (state: string) => vscode.l10n.t('State: {0}', state);
export const tooltipHealth = (health: string) => vscode.l10n.t('Health: {0}', health);
export const tooltipEndpoints = vscode.l10n.t('Endpoints:');
export const healthChecksLabel = vscode.l10n.t('Health Checks');
export const healthCheckDescription = (status: string) => vscode.l10n.t('Status: {0}', status);
export const resourceDescriptionHealth = (passed: number, total: number) => vscode.l10n.t('Health: {0}/{1}', passed, total);
export const resourceDescriptionExitCode = (exitCode: number) => vscode.l10n.t('Exit Code: {0}', exitCode);
export const parameterValueMissing = vscode.l10n.t('Value missing');
export const failedToStartDebugSession = vscode.l10n.t('Failed to start debug session.');
export const failedToGetConfigInfo = (exitCode: number) => vscode.l10n.t('Failed to get Aspire config info (exit code: {0}). Try updating the Aspire CLI with: aspire update', exitCode);
export const failedToParseConfigInfo = (error: any) => vscode.l10n.t('Failed to parse Aspire config info: {0}. Try updating the Aspire CLI with: aspire update', error);
export const errorGettingConfigInfo = (error: any) => vscode.l10n.t('Error getting Aspire config info: {0}. Try updating the Aspire CLI with: aspire update', error);
export const configInfoTimedOut = (seconds: number) => vscode.l10n.t('Aspire config info timed out after {0} seconds.', seconds);
export const invalidLaunchConfiguration = (projectPath: string) => vscode.l10n.t('Invalid launch configuration for {0}.', projectPath);
export const browserDisplayName = (url: string) => vscode.l10n.t('Browser: {0}', url);
export const browserLabel = vscode.l10n.t('Browser');
export const unsupportedBrowserDebugTarget = (browser: string, url: string, supportedBrowsers: string) => vscode.l10n.t("Browser '{0}' cannot be debugged for '{1}'. Supported browsers are: {2}.", browser, url, supportedBrowsers);
export const unsupportedBrowserDebugTargetWithoutUrl = (browser: string, supportedBrowsers: string) => vscode.l10n.t("Browser '{0}' cannot be debugged. Supported browsers are: {1}.", browser, supportedBrowsers);
export const goDisplayName = (program: string) => `Go: ${program}`;
export const goLabel = 'Go';
export const rustDisplayName = (program: string) => vscode.l10n.t('Rust: {0}', program);
export const rustLabel = vscode.l10n.t('Rust');
export const rustBuildFailedWithError = (workingDirectory: string, error: string) => vscode.l10n.t('cargo build failed in {0} with error: {1}.', workingDirectory, error);
export const rustBuildFailedWithExitCode = (workingDirectory: string, exitCode: string) => vscode.l10n.t('cargo build failed in {0} with exit code {1}.', workingDirectory, exitCode);
export const rustBuildProducedNoExecutable = (workingDirectory: string) => vscode.l10n.t('cargo build in {0} completed but did not produce a runnable binary. Ensure the crate defines a binary target.', workingDirectory);
export const rustBuildProducedMultipleExecutables = (workingDirectory: string, targets: string) => vscode.l10n.t('cargo build in {0} could not determine which target to debug. Available targets: {1}. Call WithCargoBinTarget to specify one.', workingDirectory, targets);
export const rustBuildOutputRedacted = vscode.l10n.t('[redacted]');
export const rustBuildStderrTruncated = (limit: number) => vscode.l10n.t('[cargo stderr truncated to the last {0} characters.]', limit);
export const rustLaunchConfigurationMissingExecutable = (workingDirectory: string) => vscode.l10n.t('The Aspire app host did not report which executable the Rust app in {0} produces, so there is nothing to debug.', workingDirectory);
export const rustWindowsGnuDebuggerUnsupported = (target: string) => vscode.l10n.t('The cppvsdbg debugger cannot debug Rust target {0} because GNU Windows targets use DWARF symbols. Install CodeLLDB or build an MSVC Rust target such as x86_64-pc-windows-msvc.', target);
export const rustDebuggerExtensionNotInstalled = (extensionId: string) => vscode.l10n.t('Rust AppHosts require native debugger support. Set up {0} in the Extensions view, then start the AppHost again.', extensionId);
export const bunDisplayName = (script: string) => `Bun: ${script}`;
export const bunLabel = 'Bun';
export const nodeDisplayName = (script: string) => `Node.js: ${script}`;
export const nodeLabel = 'Node.js';
// Neutral wording: a required extension that is installed but disabled is absent from
// vscode.extensions, so we cannot tell missing from disabled until the action runs.
export const debuggerSetupAction = vscode.l10n.t({ message: 'Set Up', comment: 'Button label; "Set Up" is an imperative verb.' });
export const debuggerSetupNotification = (debuggerName: string) => vscode.l10n.t('Set up {0} debugging support to debug resources in this app.', debuggerName);
export const debuggerExtensionDisabled = (debuggerName: string) => vscode.l10n.t('One or more extensions required for {0} debugging did not become available. They may be disabled or require a window reload. Open the Extensions view to continue setup.', debuggerName);
export const debuggerInstalledRestartAppHost = (debuggerName: string) => vscode.l10n.t('The extensions required for {0} debugging are installed. Restart the AppHost to enable debugging.', debuggerName);
export const openExtensionsLabel = vscode.l10n.t('Open Extensions');
export const javaDisplayName = (mainClass: string) => vscode.l10n.t('Java: {0}', mainClass);
export const javaLabel = vscode.l10n.t('Java');
export const dontShowAgainLabel = vscode.l10n.t("Don't Show Again");
export const doYouWantToSetDefaultApphost = (appHost: string) => vscode.l10n.t('Do you want to set {0} as the default AppHost for this workspace?', appHost);
export const doYouWantToSelectDefaultApphost = vscode.l10n.t('Do you want to select the default AppHost for this workspace?');
export const selectDefaultLaunchApphost = vscode.l10n.t('Select the default AppHost to launch when starting an Aspire debug session');
export const selectAppHostToLaunch = vscode.l10n.t('Multiple AppHosts were found. Select the one to launch');
export const noAppHostInWorkspace = vscode.l10n.t('No AppHost found in the Aspire settings file.');
export const dashboard = vscode.l10n.t('Dashboard');
export const codespaces = vscode.l10n.t('Codespaces');
export const encounteredErrorStartingResource = (error: string) => vscode.l10n.t('Encountered an error starting resource: {0}', error);
export const invalidOrMissingToken = vscode.l10n.t('Invalid or missing token in Authorization header.');
export const invalidTokenLength = vscode.l10n.t('Invalid token length in Authorization header.');
export const authorizationHeaderMustStartWithBearer = vscode.l10n.t('Authorization header must start with \'Bearer \'.');
export const authorizationAndDcpHeadersRequired = vscode.l10n.t('Authorization and Microsoft-Developer-DCP-Instance-ID headers are required.');
export const authorizationHeaderRequired = vscode.l10n.t('Authorization header is required.');
export const testRunSessionManagerNotInitialized = vscode.l10n.t('Test run session manager has not been initialized with DCP server connection information.');
export const buildFailedForProjectWithError = (project: string, error: string) => vscode.l10n.t('Build failed for project {0} with error: {1}.', project, error);
export const failedToInspectRuntimeConfig = (outputPath: string, error: string) => vscode.l10n.t('Failed to inspect runtimeconfig for {0}: {1}', outputPath, error);
export const dotNetRunFallbackDisablesDebugger = (outputPath: string, projectPath: string) => vscode.l10n.t('Project output {0} is not directly runnable; launching {1} with dotnet run without debugger attach. Breakpoints will not be hit for this resource.', outputPath, projectPath);
export const dotNetRunFileBasedExecutableProfileFallback = (profileName: string, projectPath: string) => vscode.l10n.t('The default launch profile \'{0}\' is an Executable profile, so dotnet run-api does not return the file-based app {1}; launching it with dotnet run without debugger attach. Breakpoints will not be hit for this resource.', profileName, projectPath);
export const executableLaunchProfileMissingExecutablePath = (profileName: string) => vscode.l10n.t('Launch profile \'{0}\' uses commandName \'Executable\' but does not specify an executablePath. Add an executablePath to the launch profile.', profileName);
export const explicitLaunchProfileNotResolved = (profileName: string) => vscode.l10n.t('Launch profile \'{0}\' could not be uniquely resolved from the project launch settings.', profileName);
export const launchProfileUnsupportedCommandName = (profileName: string) => vscode.l10n.t('Launch profile \'{0}\' uses a commandName that dotnet run does not support. Use \'Project\' or \'Executable\'.', profileName);
export const launchProfileHasInvalidProperties = (profileName: string) => vscode.l10n.t('Launch profile \'{0}\' contains property values that dotnet run does not support.', profileName);
export const lookingForDevkitBuildTask = vscode.l10n.t('C# Dev Kit is installed, looking for C# Dev Kit build task...');
export const javaDebuggerExtensionNotInstalled = (extensionId: string) => vscode.l10n.t('Java AppHosts require Java debugger support. Set up {0} in the Extensions view, then start the AppHost again.', extensionId);
export const javaAppHostCommandNotRecognized = () => vscode.l10n.t('The Java AppHost launch command was not recognized and cannot be debugged.');
export const javaAttachNotSupported = vscode.l10n.t('Java resources are started by the IDE rather than attached to, and the app host requested an attach session. Aspire cannot start one because no debug address is available.');
export const csharpDevKitNotInstalled = vscode.l10n.t('C# Dev Kit is not installed, building using dotnet CLI...');
export const hotReloadDisabledNotice = vscode.l10n.t('C# Dev Kit Hot Reload is disabled. When enabled, it can apply .NET code edits while debugging where supported.');
export const openSettingsLabel = vscode.l10n.t('Open Settings');
export const dismissLabel = vscode.l10n.t('Dismiss');
export const openCliInstallInstructions = vscode.l10n.t('See CLI installation instructions');
export const cliNotAvailable = vscode.l10n.t('Aspire CLI is not available on PATH. Please install it and restart VS Code.');
export const cliFoundAtDefaultPath = (path: string) => vscode.l10n.t('Aspire CLI found at {0}. The extension will use this path.', path);
export const selectDirectoryTitle = vscode.l10n.t('Select directory');
export const unableToAddFolderToWorkspace = (path: string) => vscode.l10n.t('Unable to add folder to workspace: {0}', path);
export const runningAspireRestore = (configPath: string) => vscode.l10n.t('Running aspire restore on {0} ...', configPath);
export const runningAspireRestoreProgress = (completed: number, total: number) => vscode.l10n.t('Running aspire restore ({0}/{1} projects) ...', completed, total);
export const aspireRestoreCompleted = (configPath: string) => vscode.l10n.t('Aspire restore completed for {0}.', configPath);
export const aspireRestoreAllCompleted = vscode.l10n.t('Aspire restore completed');
export const aspireRestoreFailed = (configPath: string, error: string) => vscode.l10n.t('aspire restore failed for {0}: {1}', configPath, error);
export const aspireRestoreFailedStatusBar = vscode.l10n.t('Aspire restore failed (click to retry)');
export const selectFileTitle = vscode.l10n.t('Select file');
export const enterPipelineStep = vscode.l10n.t('Enter the pipeline step to execute');
export const pipelineStepRequired = vscode.l10n.t('Enter a pipeline step name.');
export const loadingPipelineSteps = vscode.l10n.t('Loading pipeline steps...');
export const selectPipelineStep = vscode.l10n.t('Select a pipeline step to execute');
export const noPipelineStepsFound = vscode.l10n.t('No pipeline steps were found.');
export const appHostSourceNotFound = vscode.l10n.t('Could not determine the AppHost source file to open.');
export const appHostSourceOpenFailed = (path: string) => vscode.l10n.t('Failed to open AppHost source file: {0}', path);
export const logFilePathInvalid = vscode.l10n.t('Could not determine the AppHost log file to open.');
export const logFileOpenFailed = (path: string, error: string) => vscode.l10n.t('Failed to open AppHost log file {0}: {1}', path, error);
export const logFileLabel = vscode.l10n.t('AppHost logs');
export const startDebuggingDeclined = (command: string, appHostPath: string) => vscode.l10n.t('VS Code did not start the Aspire {0} session for {1}.', command, appHostPath);

// CodeLens strings.
// The "\u200A" between the codicon and the label is U+200A HAIR SPACE; it adds
// roughly one extra pixel of breathing room between the icon and the text in the
// CodeLens title. The CodeLens API exposes no other typography control.
export const codeLensDebugPipelineStep = vscode.l10n.t('$(bug)\u200A Debug pipeline step');
export const codeLensResourceRunning = vscode.l10n.t('$(pass)\u200A Running');
export const codeLensResourceRunningWarning = vscode.l10n.t('$(warning)\u200A Running');
export const codeLensResourceRunningError = vscode.l10n.t('$(error)\u200A Running');
export const codeLensResourceStarting = vscode.l10n.t('$(loading~spin)\u200A Starting');
export const codeLensResourceStopping = vscode.l10n.t('$(loading~spin)\u200A Stopping');
export const codeLensResourceNotStarted = vscode.l10n.t('$(circle-outline)\u200A Not Started');
export const codeLensResourceWaiting = vscode.l10n.t('$(loading~spin)\u200A Waiting');
export const codeLensResourceStopped = vscode.l10n.t('$(circle-outline)\u200A Stopped');
export const codeLensResourceStoppedWithExitCode = (exitCode: number) => vscode.l10n.t('$(circle-outline)\u200A Stopped (Exit Code: {0})', exitCode);
export const codeLensResourceStoppedError = vscode.l10n.t('$(error)\u200A Stopped');
export const codeLensResourceStoppedErrorWithExitCode = (exitCode: number) => vscode.l10n.t('$(error)\u200A Stopped (Exit Code: {0})', exitCode);
export const codeLensResourceFailedToStart = vscode.l10n.t('$(warning)\u200A Failed to start');
export const codeLensResourceFailedToStartError = vscode.l10n.t('$(error)\u200A Failed to start');
export const codeLensResourceRuntimeUnhealthy = vscode.l10n.t('$(warning)\u200A Runtime unhealthy');
export const codeLensResourceValueMissing = vscode.l10n.t('$(warning)\u200A Value missing');
export const codeLensRestart = vscode.l10n.t('$(debug-restart)\u200A Restart');
export const codeLensStop = vscode.l10n.t('$(debug-stop)\u200A Stop');
export const codeLensStart = vscode.l10n.t('$(debug-start)\u200A Start');
export const codeLensViewLogs = vscode.l10n.t('$(output)\u200A Logs');
export const codeLensCommand = (name: string) => vscode.l10n.t('$(terminal)\u200A {0}', name);
export const codeLensOpenDashboard = vscode.l10n.t('$(dashboard)\u200A Open Dashboard');
export const codeLensViewAppHostLogs = vscode.l10n.t('$(output)\u200A View Logs');
// An emoji rather than $(warning): CodeLens titles render codicons in the lens foreground color,
// so the codicon warning cannot be yellow.
export const codeLensSetUpDebugger = (debuggerName: string) => vscode.l10n.t('⚠️ Set up {0} debugger', debuggerName);
export const codeLensRustAppHostAlreadyRunning = vscode.l10n.t('⚠️ Do not click the rust-analyzer Run or Debug actions; this AppHost is already running in Aspire');
export const codeLensRustAppHostAlreadyRunningTooltip = vscode.l10n.t('Use Aspire controls instead. rust-analyzer starts another Cargo process outside the running Aspire session.');
export const codeLensRustAppHostUseAspire = vscode.l10n.t('⚠️ Do not click the rust-analyzer Run or Debug actions; they bypass Aspire');
export const codeLensRustAppHostUseAspireTooltip = vscode.l10n.t('Use Aspire Run or Debug instead. rust-analyzer starts Cargo directly, so VS Code does not create or attach to an Aspire AppHost session.');
export const codeLensSpringBootDashboardBypassesAspire = vscode.l10n.t('⚠️ Do not start this app from the Spring Boot Dashboard; it bypasses Aspire');
export const codeLensSpringBootDashboardBypassesAspireTooltip = vscode.l10n.t('Use Aspire Run or Debug instead. The Spring Boot Dashboard starts the app on its own, so it receives none of the service discovery, connection string, or OpenTelemetry settings Aspire injects.');
export const codeLensJavaAppHostAlreadyRunning = vscode.l10n.t('⚠️ Do not click the Java Run or Debug actions; this AppHost is already running in Aspire');
export const codeLensJavaAppHostAlreadyRunningTooltip = vscode.l10n.t('Use Aspire controls instead. The Java extension starts another java process outside the running Aspire session.');
export const codeLensJavaAppHostUseAspire = vscode.l10n.t('⚠️ Do not click the Java Run or Debug actions; they bypass Aspire');
export const codeLensJavaAppHostUseAspireTooltip = vscode.l10n.t('Use Aspire Run or Debug instead. The Java extension runs this file directly, so the AppHost starts with no Aspire session: none of its resources are launched, and the dashboard never appears.');

export const appHostLifecycleStartConfirmationTitle = vscode.l10n.t('Start Aspire AppHost');
export const appHostLifecycleStopConfirmationTitle = vscode.l10n.t('Stop Aspire AppHost');
export const appHostLifecycleStartConfirmationMessage = (appHostPath: string, mode: string) => vscode.l10n.t('Start the Aspire AppHost {0} in {1} mode?', appHostPath, mode);
export const appHostLifecycleStartConfirmationMessageIsolated = (appHostPath: string, mode: string) => vscode.l10n.t('Start the Aspire AppHost {0} in {1} mode with isolation?', appHostPath, mode);
export const appHostLifecycleStartConfirmationMessageWithLaunchProfile = (appHostPath: string, mode: string, launchProfile: string) => vscode.l10n.t('Start the Aspire AppHost {0} in {1} mode using launch profile {2}?', appHostPath, mode, launchProfile);
export const appHostLifecycleStartConfirmationMessageIsolatedWithLaunchProfile = (appHostPath: string, mode: string, launchProfile: string) => vscode.l10n.t('Start the Aspire AppHost {0} in {1} mode with isolation using launch profile {2}?', appHostPath, mode, launchProfile);
export const appHostLifecycleStopConfirmationMessage = (appHostPath: string) => vscode.l10n.t('Stop the Aspire AppHost {0}?', appHostPath);
export const appHostLifecycleStartInvocationMessage = (appHostPath: string) => vscode.l10n.t('Starting Aspire AppHost {0}...', appHostPath);
export const appHostLifecycleStopInvocationMessage = (appHostPath: string) => vscode.l10n.t('Stopping Aspire AppHost {0}...', appHostPath);
export const appHostLifecycleUnspecifiedMode = vscode.l10n.t('unspecified');
export const appHostLifecycleUnresolvedPath = vscode.l10n.t('an unresolved path');
export const appHostLifecycleBusy = vscode.l10n.t('Another start or stop operation for this Aspire AppHost is still in progress. Wait for it to finish and try again.');
export const appHostLifecycleIsolationModeNotSupported = vscode.l10n.t('The selected Aspire CLI does not support the requested isolation mode.');
export const appHostLifecycleIsolationCapabilityCouldNotBeVerified = vscode.l10n.t('The selected Aspire CLI isolation capability could not be verified.');
export const appHostLifecycleLaunchProfileNotSupported = vscode.l10n.t('The selected Aspire CLI does not support the requested launch profile.');
export const appHostLifecycleLaunchProfileCapabilityCouldNotBeVerified = vscode.l10n.t('The selected Aspire CLI launch profile capability could not be verified.');
export const appHostLifecycleInvalidLaunchProfile = vscode.l10n.t('an invalid launch profile');
export const appHostLifecycleLaunchProfileRequiresRun = vscode.l10n.t('Launch profiles are only supported for the run command.');
export const appHostLifecycleLaunchAlreadyClaimed = vscode.l10n.t('This Aspire AppHost is already starting or running. The new debug session was cancelled so only one AppHost runs.');
export const appHostOperationAlreadyInProgress = vscode.l10n.t('Another operation is already in progress for this Aspire AppHost. The new operation was cancelled.');
