//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Hosting.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Hosting.Resources.CommandStrings", typeof(CommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart resource.
        /// </summary>
        internal static string RestartDescription {
            get {
                return ResourceManager.GetString("RestartDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart resource. Source code is not recompiled..
        /// </summary>
        internal static string RestartProjectDescription {
            get {
                return ResourceManager.GetString("RestartProjectDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string RestartName {
            get {
                return ResourceManager.GetString("RestartName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete parameter value.
        /// </summary>
        internal static string DeleteParameterDescription {
            get {
                return ResourceManager.GetString("DeleteParameterDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete parameter.
        /// </summary>
        internal static string DeleteParameterName {
            get {
                return ResourceManager.GetString("DeleteParameterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open the app in a tracked browser session and stream browser logs to this resource..
        /// </summary>
        internal static string OpenTrackedBrowserDescription {
            get {
                return ResourceManager.GetString("OpenTrackedBrowserDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open tracked browser.
        /// </summary>
        internal static string OpenTrackedBrowserName {
            get {
                return ResourceManager.GetString("OpenTrackedBrowserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capture a screenshot from the active tracked browser session and save it as a PNG artifact..
        /// </summary>
        internal static string CaptureScreenshotDescription {
            get {
                return ResourceManager.GetString("CaptureScreenshotDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capture screenshot.
        /// </summary>
        internal static string CaptureScreenshotName {
            get {
                return ResourceManager.GetString("CaptureScreenshotName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop the resource, rebuild the project from source, and restart. Use this to apply source code changes..
        /// </summary>
        internal static string RebuildDescription {
            get {
                return ResourceManager.GetString("RebuildDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        internal static string RebuildName {
            get {
                return ResourceManager.GetString("RebuildName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rebuilder resource for &apos;{0}&apos; not found..
        /// </summary>
        internal static string RebuilderResourceNotFound {
            get {
                return ResourceManager.GetString("RebuilderResourceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted parameter &apos;{0}&apos;..
        /// </summary>
        internal static string ResourceDeletedParameter {
            get {
                return ResourceManager.GetString("ResourceDeletedParameter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully rebuilt &apos;{0}&apos;..
        /// </summary>
        internal static string ResourceRebuilt {
            get {
                return ResourceManager.GetString("ResourceRebuilt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully restarted &apos;{0}&apos;..
        /// </summary>
        internal static string ResourceRestarted {
            get {
                return ResourceManager.GetString("ResourceRestarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully set parameter &apos;{0}&apos;..
        /// </summary>
        internal static string ResourceSetParameter {
            get {
                return ResourceManager.GetString("ResourceSetParameter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully started &apos;{0}&apos;..
        /// </summary>
        internal static string ResourceStarted {
            get {
                return ResourceManager.GetString("ResourceStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully stopped &apos;{0}&apos;..
        /// </summary>
        internal static string ResourceStopped {
            get {
                return ResourceManager.GetString("ResourceStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set parameter value.
        /// </summary>
        internal static string SetParameterDescription {
            get {
                return ResourceManager.GetString("SetParameterDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set parameter.
        /// </summary>
        internal static string SetParameterName {
            get {
                return ResourceManager.GetString("SetParameterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start resource.
        /// </summary>
        internal static string StartDescription {
            get {
                return ResourceManager.GetString("StartDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartName {
            get {
                return ResourceManager.GetString("StartName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop resource.
        /// </summary>
        internal static string StopDescription {
            get {
                return ResourceManager.GetString("StopDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopName {
            get {
                return ResourceManager.GetString("StopName", resourceCulture);
            }
        }
    }
}
