//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class AzureFrontDoorExtensions
    {
        [AspireExport(Description = "Adds an Azure Front Door resource")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureFrontDoorResource> AddAzureFrontDoor(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport(Description = "Adds an origin (backend) to the Azure Front Door resource")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureFrontDoorResource> WithOrigin<T>(this ApplicationModel.IResourceBuilder<Azure.AzureFrontDoorResource> builder, ApplicationModel.IResourceBuilder<T> resource)
            where T : ApplicationModel.IComputeResource, ApplicationModel.IResourceWithEndpoints { throw null; }
    }
}

namespace Aspire.Hosting.Azure
{
    public partial class AzureFrontDoorResource : AzureProvisioningResource
    {
        public AzureFrontDoorResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public BicepOutputReference GetEndpointUrl(string originResourceName) { throw null; }
    }
}