import {
    AksNodeVmSizes,
    AzureServiceTags,
    WellKnownPipelineSteps,
    WellKnownPipelineTags,
    createBuilder,
    CertificateTrustScope,
    ContainerImageDestination,
    ContainerImageFormat,
    ContainerTargetPlatform,
    EndpointProperty,
    HealthStatus,
    IconVariant,
    InputType,
    MessageIntent,
    OtlpProtocol,
    ProbeType,
    ResourceCommandState,
    refExpr,
} from './.aspire/modules/aspire.mjs';
import type { DockerfileBuilderCallbackContext, DockerfileFactoryContext, HealthCheckResult, InteractionChoiceOption } from './.aspire/modules/aspire.mjs';
import { fileURLToPath } from 'node:url';

const builder = await createBuilder();
const processCommandStdinScriptPath = fileURLToPath(new URL("./process-command-scripts/stdin.js", import.meta.url));

// ===================================================================
// Factory methods on builder
// ===================================================================

// addContainer (pre-existing)
const container = await builder.addContainer("mycontainer", "nginx");
await container.withOtlpExporter({ protocol: OtlpProtocol.HttpJson });
const taggedContainer = await builder.addContainer("mytaggedcontainer", {
    image: "nginx",
    tag: "stable-alpine",
});

// addDockerfile
const dockerContainer = await builder.addDockerfile("dockerapp", "./app");
const dockerFactoryContainer = await builder.addDockerfileFactory("dockerfactoryapp", "./app", async (factoryContext: DockerfileFactoryContext) => {
    const _factoryResource = await factoryContext.resource();
    return `
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
WORKDIR /app
ENTRYPOINT ["dotnet", "App.dll"]
`;
}, { stage: "runtime" });

const configureDockerfileBuilder = async (dockerfileContext: DockerfileBuilderCallbackContext) => {
    const _dockerfileResource = await dockerfileContext.resource();
    const dockerfileServices = await dockerfileContext.services();
    const dockerfileLoggerFactory = await dockerfileServices.getLoggerFactory();
    const dockerfileLogger = await dockerfileLoggerFactory.createLogger("ValidationAppHost.DockerfileBuilder");
    await dockerfileLogger.logInformation("Configuring Dockerfile builder");

    const dockerfileBuilder = await dockerfileContext.builder();
    await dockerfileBuilder.arg("BASE_IMAGE", { defaultValue: "mcr.microsoft.com/dotnet/runtime:8.0" });
    await dockerfileBuilder.addContainerFilesStages(_dockerfileResource, { logger: dockerfileLogger });

    const buildStage = await dockerfileBuilder.from("mcr.microsoft.com/dotnet/sdk:8.0", { stageName: "build" });
    await buildStage.arg("APP_DIR", { defaultValue: "/src" });
    await buildStage.workDir("/src");
    await buildStage.copy("./src", "/src", { chown: "1000:1000" });
    await buildStage.run("echo building dockerfile");
    await buildStage.runWithMounts("echo mounted", ["/tmp:/mnt"]);

    const runtimeStage = await dockerfileBuilder.from("mcr.microsoft.com/dotnet/runtime:8.0", { stageName: "runtime" });
    await runtimeStage.copyFrom("build", "/src", "/app", { chown: "1000:1000" });
    await runtimeStage.env("ASPIRE_ENV", "Development");
    await runtimeStage.expose(8080);
    await runtimeStage.cmd(["dotnet", "App.dll"]);
    await runtimeStage.entrypoint(["dotnet", "App.dll"]);
    await runtimeStage.user("1000");
    await runtimeStage.addContainerFiles(_dockerfileResource, "/app", { logger: dockerfileLogger });
    await runtimeStage.emptyLine();
    await runtimeStage.comment("Generated by TypeScript polyglot validation");
};

const dockerBuilderContainer = await builder.addDockerfileBuilder("dockerbuilderapp", "./app", configureDockerfileBuilder, { stage: "runtime" });
await dockerContainer.withDockerfileBuilder("./app", configureDockerfileBuilder, { stage: "runtime" });
await dockerFactoryContainer.withDockerfileFactory("./app", async (factoryContext: DockerfileFactoryContext) => {
    const _factoryResource = await factoryContext.resource();
    return `
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
WORKDIR /app
ENTRYPOINT ["dotnet", "App.dll"]
`;
}, { stage: "runtime" });

// addExecutable (pre-existing)
const exe = await builder.addExecutable("myexe", "echo", ".", ["hello"]);

// addProject (pre-existing)
const project = await builder.addProject("myproject", "./src/MyProject", { launchProfileOrOptions: "https" });
const projectWithoutLaunchProfile = await builder.addProject("myproject-noprofile", "./src/MyProject");
await project.withEndpointsInEnvironment(["https"]);
// ATS exports ReferenceEnvironmentInjectionFlags as a DTO-shaped object in TypeScript.
const referenceEnvironmentOptions = {
    connectionString: true,
    serviceDiscovery: true,
};
await project.withReferenceEnvironment(referenceEnvironmentOptions);

const customHealthCheck = async (): Promise<HealthCheckResult> => ({
    status: HealthStatus.Healthy,
    description: "custom health check",
    data: {
        custom: "value",
    },
});
await builder.addHealthCheck("custom_check", customHealthCheck);

// addCSharpApp
const csharpApp = await builder.addCSharpApp("csharpapp", "./src/CSharpApp");

// addRedis
const cache = await builder.addRedis("cache");

// addDotnetTool
const tool = await builder.addDotnetTool("mytool", "dotnet-ef");

// addParameterFromConfiguration
const configParam = await builder.addParameterFromConfiguration("myconfig", "MyConfig:Key");
const secretParam = await builder.addParameterFromConfiguration("mysecret", "MyConfig:Secret", { secret: true });
const generatedParam = await builder.addParameterWithGeneratedValue("generated-secret", {
    minLength: 24,
    lower: true,
    upper: true,
    numeric: true,
    special: false,
    minUpper: 2,
    minNumeric: 2,
}, {
    secret: true,
    persist: true,
});
const customInputParam = await builder.addParameter("custom-input");
await customInputParam.withCustomInput({
    inputType: InputType.Number,
    label: "Worker Count",
    placeholder: "Enter number (1-10)",
    options: {
        one: "One",
        two: "Two",
    },
});

// ===================================================================
// Container-specific methods on ContainerResource
// ===================================================================

// withDockerfileBaseImage
await container.withDockerfileBaseImage({ buildImage: "mcr.microsoft.com/dotnet/sdk:8.0" });
await dockerContainer.withBuildArg("STATIC_BRANDING", "/app/static/branding/custom");
await dockerContainer.withBuildArg("CONFIG_BRANDING", configParam);
await container.withContainerCertificatePaths({
    customCertificatesDestination: "/usr/lib/ssl/aspire/custom",
    defaultCertificateBundlePaths: ["/etc/ssl/certs/ca-certificates.crt"],
    defaultCertificateDirectoryPaths: ["/etc/ssl/certs", "/usr/local/share/ca-certificates"],
});
await container.withContainerFiles("/usr/lib/aspire/container-files", ".", {
    defaultOwner: 1000,
    defaultGroup: 1000,
    umask: 0o022,
});

// withContainerFilesCallback — build entries dynamically via the context factory methods
await container.withContainerFilesCallback("/usr/lib/aspire/container-files", async (filesCtx) => {
    const filesServices = await filesCtx.services();
    const filesLoggerFactory = await filesServices.getLoggerFactory();
    const filesLogger = await filesLoggerFactory.createLogger("ValidationAppHost.ContainerFilesCallback");
    await filesLogger.logInformation("ContainerFilesCallback services");

    const appConfig = await filesCtx.createFile("app.conf", { contents: "key=value", mode: 0o644 });
    const nestedConfig = await filesCtx.createFile("nested.conf", { contents: "nested=true" });
    const confDir = await filesCtx.createDirectory("conf.d", [nestedConfig], { mode: 0o755 });
    const cert = await filesCtx.createCertificateFile("server.pem", { contents: "-----BEGIN CERTIFICATE-----" });
    return [appConfig, confDir, cert];
}, { defaultOwner: 1000, defaultGroup: 1000, umask: 0o022 });

// withImageRegistry
await container.withImageRegistry("docker.io");

// ===================================================================
// ConnectionStringBuilderExtensions.cs — NEW exports
// ===================================================================

await dockerContainer.withHttpEndpoint({ name: "http", targetPort: 80 });
await dockerContainer.withHttpEndpointCallback(async (updateContext) => {
    await updateContext.port.set(8080);
    await updateContext.isProxied.set(false);
}, { name: "http", createIfNotExists: false });
const endpoint = await dockerContainer.getEndpoint("http");
const expr = refExpr`Host=${endpoint}`;
const endpointHost = await dockerContainer.getEndpoint("http").property(EndpointProperty.Host);
const endpointPort = await dockerContainer.getEndpoint("http").property(EndpointProperty.Port);
const endpointUrl = refExpr`http://${endpointHost}:${endpointPort}`;

const builtConnectionString = await builder.addConnectionString("customcs", { environmentVariableNameOrExpression: expr });

await builtConnectionString.withConnectionProperty("Host", expr);
await builtConnectionString.withConnectionProperty("Mode", "Development");
await container.withReference(endpoint);
await container.withReference("https://example.com/", { name: "external-uri" });
const externalService = await builder.addExternalService("external-service", "https://example.com");

const envConnectionString = await builder.addConnectionString("envcs");
const expressionConnectionString = await builder.addConnectionString("exprcs", { environmentVariableNameOrExpression: expr });

// ===================================================================
// Azure network and AKS exported value catalogs
// ===================================================================

const vnet = await builder.addAzureVirtualNetwork("vnet", { addressPrefix: "10.0.0.0/16" });
const subnet = await vnet.addSubnet("web", "10.0.1.0/24");
await subnet.allowInbound({ port: "443", from: AzureServiceTags.AzureLoadBalancer });
await subnet.denyInbound({ from: AzureServiceTags.Internet });

const aks = await builder.addAzureKubernetesEnvironment("aks");
await aks.addNodePool("system", { vmSize: AksNodeVmSizes.StandardDSv5.StandardD2sV5 });

// ===================================================================
// Application pipeline on builder
// ===================================================================

const pipeline = await builder.pipeline();

await pipeline.addStep("custom-builder-step", async (stepContext) => {
    const summary = await stepContext.summary();
    await summary.add("BuilderPipelineStep", "Validated");
}, {
    dependsOn: [WellKnownPipelineSteps.Build],
    requiredBy: [WellKnownPipelineSteps.Publish],
});

await pipeline.configure(async (configContext) => {
    const builderPipeline = await configContext.pipeline();
    const _allSteps = await builderPipeline.steps();
    const _builderTaggedSteps = await configContext.getSteps("custom-build");
});

// ===================================================================
// ResourceBuilderExtensions.cs — NEW exports on ContainerResource
// ===================================================================

// withEnvironment - EndpointReference
await container.withEnvironment("MY_ENDPOINT", endpoint);

// withEnvironment — with ReferenceExpression
await container.withEnvironment("MY_EXPR", expr);
await container.withEnvironment("MY_ENDPOINT_URL", endpointUrl);

// withEnvironment — with ParameterResource
await container.withEnvironment("MY_PARAM", configParam);
await container.withEnvironment("MY_GENERATED_PARAM", generatedParam);

// withEnvironment — with connection string resource
await container.withEnvironment("MY_CONN", envConnectionString);
await container.withEnvironment("MY_EXPR_CONN", expressionConnectionString);

// withEnvironment — with external service resource
await container.withEnvironment("MY_EXTERNAL_SERVICE", externalService);

// callback editors/facades
await container.withEnvironmentCallback(async (context) => {
    const environment = await context.environment();
    const environmentLog = await context.log();
    const _environmentResource = await context.resource();
    const _environmentIsRunMode: boolean = await context.executionContext().isRunMode();
    await environmentLog.warning("Environment callback logger");
    await environment.set("MY_CALLBACK_ENDPOINT", endpoint);
});

await container.withArgsCallback(async (context) => {
    const args = await context.args();
    const argsLog = await context.log();
    const _argsResource = await context.resource();
    const _argsIsRunMode: boolean = await context.executionContext().isRunMode();
    await argsLog.error("Args callback logger");
    await args.add("--validation-callback");
    await args.add(expr);
});

await container.withUrls(async (context) => {
    const _urlsResource = await context.resource();
    const urlsLog = await context.log();
    const _urlsIsRunMode: boolean = await context.executionContext().isRunMode();
    const callbackEndpoint = await context.getEndpoint("http");
    const callbackEndpointHost = await context.getEndpoint("http").property(EndpointProperty.Host);
    const urls = await context.urls();
    await urlsLog.debug("URLs callback logger");
    await urls.add(refExpr`https://${callbackEndpoint}`);
    await urls.add(refExpr`https://${callbackEndpointHost}`);
    await urls.addForEndpoint(callbackEndpoint, "/details", { displayText: "Details" });
});

// withConnectionProperty — with ReferenceExpression
await builtConnectionString.withConnectionProperty("Endpoint", expr);

// withConnectionProperty — with string
await builtConnectionString.withConnectionProperty("Protocol", "https");

// excludeFromManifest
await container.excludeFromManifest();

// excludeFromMcp
await container.excludeFromMcp();

// waitForCompletion (pre-existing)
await container.waitForCompletion(exe);

// withDeveloperCertificateTrust
await container.withDeveloperCertificateTrust(true);

// withCertificateTrustScope
await container.withCertificateTrustScope(CertificateTrustScope.System);

// withHttpsDeveloperCertificate
await container.withHttpsDeveloperCertificate();

// withoutHttpsCertificate
await container.withoutHttpsCertificate();

// withChildRelationship
await container.withChildRelationship(exe);

// withRelationship
await container.withRelationship(taggedContainer, "peer");
await project.withReference(cache);

// withIconName
await container.withIconName("Database", { iconVariant: IconVariant.Filled });

// withHttpProbe
await container.withHttpProbe(ProbeType.Liveness, { path: "/health" });

// withRemoteImageName
await container.withRemoteImageName("myregistry.azurecr.io/myapp");

// withRemoteImageTag
await container.withRemoteImageTag("latest");

// withImagePushOptions
await container.withImagePushOptions(async (context) => {
    const options = await context.options();
    await options.remoteImageName.set("myregistry.azurecr.io/myapp");
    await options.remoteImageTag.set("latest");
});

// withMcpServer
await container.withMcpServer({ path: "/mcp" });

// withRequiredCommand
await container.withRequiredCommand("docker");

// withRequiredCommandValidation
await container.withRequiredCommandValidation("docker", async (validationCtx) => {
    const _validationResolvedPath = await validationCtx.resolvedPath();
    const validationServices = await validationCtx.services();
    const validationLoggerFactory = await validationServices.getLoggerFactory();
    const validationLogger = await validationLoggerFactory.createLogger("ValidationAppHost.RequiredCommandValidation");
    await validationLogger.logInformation("RequiredCommandValidation services");
    return await validationCtx.success();
});

// ===================================================================
// DotnetToolResourceExtensions.cs — NEW exports
// ===================================================================

// withToolIgnoreExistingFeeds
await tool.withToolIgnoreExistingFeeds();

// withToolIgnoreFailedSources
await tool.withToolIgnoreFailedSources();

// withToolPackage
await tool.withToolPackage("dotnet-ef");

// withToolPrerelease
await tool.withToolPrerelease();

// withToolSource
await tool.withToolSource("https://api.nuget.org/v3/index.json");

// withToolVersion
await tool.withToolVersion("8.0.0");

// publishAsDockerFile
await tool.publishAsDockerFile(async (_container) => {
});

// PipelineStepFactoryExtensions.cs — NEW exports
// ===================================================================

await container.withPipelineStepFactory("custom-build-step", async (stepContext) => {
    const pipelineContext = await stepContext.pipelineContext();
    const pipelineModel = await pipelineContext.model();
    const _pipelineResources = await pipelineModel.getResources();
    const _pipelineContainer = await pipelineModel.findResourceByName("mycontainer");
    const pipelineServices = await pipelineContext.services();
    const pipelineLoggerFactory = await pipelineServices.getLoggerFactory();
    const pipelineFactoryLogger = await pipelineLoggerFactory.createLogger("ValidationAppHost.PipelineContext");
    await pipelineFactoryLogger.logInformation("Pipeline factory context logger");
    const pipelineLogger = await pipelineContext.logger();
    await pipelineLogger.logDebug("Pipeline context logger");
    const pipelineSummary = await pipelineContext.summary();
    await pipelineSummary.add("PipelineContext", "Validated");
    await pipelineSummary.addMarkdown("PipelineMarkdown", "**Validated**");

    const _isPublishMode: boolean = await stepContext.executionContext().isPublishMode();
    const stepServices = await stepContext.services();
    const stepLogger = await stepContext.logger();
    await stepLogger.logInformation("Pipeline step context logger");
    const stepSummary = await stepContext.summary();
    await stepSummary.add("PipelineStepContext", "Validated");
    const reportingStep = await stepContext.reportingStep();
    await reportingStep.logStep("information", "Reporting step log");
    await reportingStep.logStepMarkdown("information", "**Reporting step markdown log**");
    const reportingTask = await reportingStep.createTask("Task created");
    await reportingTask.updateTask("Task updated");
    await reportingTask.updateTaskMarkdown("**Task markdown updated**");
    await reportingTask.completeTask({ completionMessage: "Task complete" });
    const markdownTask = await reportingStep.createMarkdownTask("**Markdown task created**");
    await markdownTask.completeTaskMarkdown("**Markdown task complete**", { completionState: "completed-with-warning" });
    await reportingStep.completeStep("Reporting step complete");
    await reportingStep.completeStepMarkdown("**Reporting step markdown complete**", { completionState: "completed-with-warning" });
    const stepModel = await stepContext.model();
    const _stepResources = await stepModel.getResources();
    const _stepContainer = await stepModel.findResourceByName("mycontainer");
    const stepLoggerFactory = await stepServices.getLoggerFactory();
    const stepFactoryLogger = await stepLoggerFactory.createLogger("ValidationAppHost.PipelineStepContext");
    await stepFactoryLogger.logDebug("Pipeline step factory logger");
    const cancellationToken = await stepContext.cancellationToken();
    const cacheUriExpression = await cache.uriExpression();
    const _cacheUri = await cacheUriExpression.getValue(cancellationToken);
}, {
    dependsOn: [WellKnownPipelineSteps.Build],
    requiredBy: [WellKnownPipelineSteps.Deploy],
    tags: [WellKnownPipelineTags.BuildCompute],
    description: "Custom pipeline step"
});

await container.withPipelineConfiguration(async (configContext) => {
    const configLog = await configContext.log();
    await configLog.info("Pipeline configuration logger");

    const configPipeline = await configContext.pipeline();
    const allSteps = await configPipeline.steps();
    const taggedSteps = await configPipeline.stepsByTag(WellKnownPipelineTags.BuildCompute);

    const _stepName: string = await allSteps[0].name();
    const _description: string | null = await allSteps[0].description();
    const _dependsOnSteps = await allSteps[0].dependsOnSteps();
    const _requiredBySteps = await taggedSteps[0].requiredBySteps();
    const _tags = await taggedSteps[0].tags();

    await allSteps[0].addTag("validated");
    await allSteps[0].dependsOn("restore");
    await taggedSteps[0].requiredBy(WellKnownPipelineSteps.Publish);
    await allSteps[0].dependsOn(WellKnownPipelineSteps.Build);
});

await container.withPipelineConfiguration(async (configContext) => {
    const configPipeline = await configContext.pipeline();
    const _resourceSteps = await configPipeline.steps();
    const _taggedSteps = await configPipeline.stepsByTag(WellKnownPipelineTags.BuildCompute);
});

// ===================================================================
// Builder, eventing, logging, model, notification, and user secrets
// ===================================================================

const _appHostDirectory: string = await builder.appHostDirectory();
const _isDevelopment: boolean = await builder.environment().isDevelopment();
const _isProduction: boolean = await builder.environment().isProduction();
const _isStaging: boolean = await builder.environment().isStaging();
const _isSpecificEnvironment: boolean = await builder.environment().isEnvironment("Development");

const builderConfiguration = await builder.getConfiguration();
const _configValue: string = await builderConfiguration.getConfigValue("MyConfig:Key");
const _connectionString: string = await builderConfiguration.getConnectionString("customcs");
const _configSection = await builderConfiguration.getSection("MyConfig");
const _configChildren = await builderConfiguration.getChildren();
const _configExists: boolean = await builderConfiguration.exists("MyConfig:Key");

const builderExecutionContext = builder.executionContext();
const executionContextServiceProvider = await builderExecutionContext.serviceProvider();
const _distributedApplicationModelFromExecutionContext = await executionContextServiceProvider.getDistributedApplicationModel();
const resourceCommandService = await executionContextServiceProvider.getResourceCommandService();

await builder.addEventingSubscriber(async (registrationContext) => {
    const _subscriberIsRunMode: boolean = await registrationContext.executionContext().isRunMode();
    const _subscriberCancellationToken = await registrationContext.cancellationToken();

    await registrationContext.onBeforeStart(async (beforeStartEvent) => {
        const subscriberServices = await beforeStartEvent.services();
        const aspireStore = await subscriberServices.getAspireStore();
        const _contentBackedFilename = await aspireStore.getFileNameWithContent("validation-apphost.mts", "apphost.mts");
    });

    await registrationContext.onBeforePublish(async (beforePublishEvent) => {
        const beforePublishServices = await beforePublishEvent.services();
        const beforePublishModel = await beforePublishEvent.model();
        const _beforePublishEventing = await beforePublishServices.getEventing();
        const _beforePublishResources = await beforePublishModel.getResources();
    });

    await registrationContext.onAfterPublish(async (afterPublishEvent) => {
        const afterPublishServices = await afterPublishEvent.services();
        const afterPublishModel = await afterPublishEvent.model();
        const _afterPublishEventing = await afterPublishServices.getEventing();
        const _afterPublishResources = await afterPublishModel.getResources();
    });

    await registrationContext.onAfterResourcesCreated(async (afterResourcesCreatedEvent) => {
        const afterResourcesCreatedServices = await afterResourcesCreatedEvent.services();
        const afterResourcesCreatedModel = await afterResourcesCreatedEvent.model();
        const _afterResourcesCreatedEventing = await afterResourcesCreatedServices.getEventing();
        const _afterResourcesCreatedResources = await afterResourcesCreatedModel.getResources();
    });
});

await builder.tryAddEventingSubscriber(async (_registrationContext) => {
});

await container.withArgs(["--validation"]);

const executionConfigurationBuilder = await container.createExecutionConfiguration();
await executionConfigurationBuilder.withArgumentsConfig();
await executionConfigurationBuilder.withEnvironmentVariablesConfig();
await executionConfigurationBuilder.withCertificateTrustConfig(async (requestedTrustScope) => {
    const _requestedTrustScope = requestedTrustScope;

    return {
        certificateBundlePath: refExpr`/etc/ssl/certs/custom-bundle.pem`,
        certificateDirectoriesPath: refExpr`/etc/ssl/certs/custom`,
        rootCertificatesPath: "/etc/ssl/certs",
        isContainer: true,
    };
});
await executionConfigurationBuilder.withHttpsCertificateConfig(async (certificateInfo) => {
    const _certificateSubject = certificateInfo.subject;
    const _certificateThumbprint = certificateInfo.thumbprint;

    return {
        certificatePath: refExpr`/certificates/tls.crt`,
        keyPath: refExpr`/certificates/tls.key`,
        pfxPath: refExpr`/certificates/tls.pfx`,
    };
});

const executionConfiguration = await executionConfigurationBuilder.build(builderExecutionContext);
const _certificateTrustData = await executionConfiguration.getCertificateTrustData();
const _httpsCertificateData = await executionConfiguration.getHttpsCertificateData();

const beforeStartSubscription = await builder.subscribeBeforeStart(async (beforeStartEvent) => {
    const beforeStartServices = await beforeStartEvent.services();
    const beforeStartModel = await beforeStartEvent.model();
    const _beforeStartResources = await beforeStartModel.getResources();
    const _beforeStartContainer = await beforeStartModel.findResourceByName("mycontainer");

    const _beforeStartEventing = await beforeStartServices.getEventing();
    const beforeStartLoggerFactory = await beforeStartServices.getLoggerFactory();
    const beforeStartLogger = await beforeStartLoggerFactory.createLogger("ValidationAppHost.BeforeStart");
    await beforeStartLogger.logInformation("BeforeStart information");
    await beforeStartLogger.logWarning("BeforeStart warning");
    await beforeStartLogger.logError("BeforeStart error");
    await beforeStartLogger.logDebug("BeforeStart debug");
    await beforeStartLogger.log("critical", "BeforeStart critical");

    const beforeStartResourceLoggerService = await beforeStartServices.getResourceLoggerService();
    await beforeStartResourceLoggerService.completeLog(container);
    await beforeStartResourceLoggerService.completeLogByName("mycontainer");

    const beforeStartNotificationService = await beforeStartServices.getResourceNotificationService();
    await beforeStartNotificationService.waitForResourceState("mycontainer", { targetState: "Running" });
    const _matchedResourceState: string = await beforeStartNotificationService.waitForResourceStates("mycontainer", ["Running", "FailedToStart"]);
    const _healthyResourceEvent = await beforeStartNotificationService.waitForResourceHealthy("mycontainer");
    await beforeStartNotificationService.waitForDependencies(container);
    const _currentResourceState = await beforeStartNotificationService.tryGetResourceState("mycontainer");
    await beforeStartNotificationService.publishResourceUpdate(container, { state: "Validated", stateStyle: "info" });

    const userSecretsManager = await beforeStartServices.getUserSecretsManager();
    const _userSecretsAvailable: boolean = await userSecretsManager.isAvailable();
    const _userSecretsFilePath: string = await userSecretsManager.filePath();
    const _secretSet: boolean = await userSecretsManager.trySetSecret("Validation:Key", "value");
    await userSecretsManager.getOrSetSecret(container, "Validation:GeneratedKey", "generated-value");
    const _generatedSecretValue: string = await builderConfiguration.getConfigValue("Validation:GeneratedKey");
    await userSecretsManager.saveStateJson("{\"Validation\":\"Value\"}");

    const _modelFromServices = await beforeStartServices.getDistributedApplicationModel();
});

const afterResourcesCreatedSubscription = await builder.subscribeAfterResourcesCreated(async (afterResourcesCreatedEvent) => {
    const afterResourcesCreatedServices = await afterResourcesCreatedEvent.services();
    const afterResourcesCreatedModel = await afterResourcesCreatedEvent.model();
    const _afterResources = await afterResourcesCreatedModel.getResources();
    const _afterResourcesContainer = await afterResourcesCreatedModel.findResourceByName("mycontainer");
    const afterResourcesCreatedLoggerFactory = await afterResourcesCreatedServices.getLoggerFactory();
    const afterResourcesCreatedLogger = await afterResourcesCreatedLoggerFactory.createLogger("ValidationAppHost.AfterResourcesCreated");
    await afterResourcesCreatedLogger.logInformation("AfterResourcesCreated");
});

const beforePublishSubscription = await builder.subscribeBeforePublish(async (beforePublishEvent) => {
    const beforePublishServices = await beforePublishEvent.services();
    const beforePublishModel = await beforePublishEvent.model();
    const _beforePublishResources = await beforePublishModel.getResources();
    const _beforePublishContainer = await beforePublishModel.findResourceByName("mycontainer");
    const beforePublishLoggerFactory = await beforePublishServices.getLoggerFactory();
    const beforePublishLogger = await beforePublishLoggerFactory.createLogger("ValidationAppHost.BeforePublish");
    await beforePublishLogger.logInformation("BeforePublish");
});

const afterPublishSubscription = await builder.subscribeAfterPublish(async (afterPublishEvent) => {
    const afterPublishServices = await afterPublishEvent.services();
    const afterPublishModel = await afterPublishEvent.model();
    const _afterPublishResources = await afterPublishModel.getResources();
    const _afterPublishContainer = await afterPublishModel.findResourceByName("mycontainer");
    const afterPublishLoggerFactory = await afterPublishServices.getLoggerFactory();
    const afterPublishLogger = await afterPublishLoggerFactory.createLogger("ValidationAppHost.AfterPublish");
    await afterPublishLogger.logInformation("AfterPublish");
});

const builderEventing = await builder.eventing();
await builderEventing.unsubscribe(beforeStartSubscription);
await builderEventing.unsubscribe(afterResourcesCreatedSubscription);
await builderEventing.unsubscribe(beforePublishSubscription);
await builderEventing.unsubscribe(afterPublishSubscription);

await container.onBeforeResourceStarted(async (beforeResourceStartedEvent) => {
    const _resource = await beforeResourceStartedEvent.resource();
    const services = await beforeResourceStartedEvent.services();
    const loggerFactory = await services.getLoggerFactory();
    const logger = await loggerFactory.createLogger("ValidationAppHost.BeforeResourceStarted");
    await logger.logInformation("BeforeResourceStarted");
});

await container.onResourceStopped(async (resourceStoppedEvent) => {
    const _resource = await resourceStoppedEvent.resource();
    const services = await resourceStoppedEvent.services();
    const loggerFactory = await services.getLoggerFactory();
    const logger = await loggerFactory.createLogger("ValidationAppHost.ResourceStopped");
    await logger.logWarning("ResourceStopped");
});

await builtConnectionString.onConnectionStringAvailable(async (connectionStringAvailableEvent) => {
    const _resource = await connectionStringAvailableEvent.resource();
    const services = await connectionStringAvailableEvent.services();
    const notifications = await services.getResourceNotificationService();
    const _connectionState = await notifications.tryGetResourceState("customcs");
});

await container.onInitializeResource(async (initializeResourceEvent) => {
    const _resource = await initializeResourceEvent.resource();
    const _initializeEventing = await initializeResourceEvent.eventing();
    const initializeLogger = await initializeResourceEvent.logger();
    const initializeNotifications = await initializeResourceEvent.notifications();
    const initializeServices = await initializeResourceEvent.services();
    await initializeLogger.logDebug("InitializeResource");
    await initializeNotifications.waitForDependencies(container);
    const _initializeModel = await initializeServices.getDistributedApplicationModel();
    const _initializeEventingFromServices = await initializeServices.getEventing();
});

await container.onResourceEndpointsAllocated(async (resourceEndpointsAllocatedEvent) => {
    const _resource = await resourceEndpointsAllocatedEvent.resource();
    const services = await resourceEndpointsAllocatedEvent.services();
    const loggerFactory = await services.getLoggerFactory();
    const logger = await loggerFactory.createLogger("ValidationAppHost.ResourceEndpointsAllocated");
    await logger.logInformation("ResourceEndpointsAllocated");
});

await container.onResourceReady(async (resourceReadyEvent) => {
    const _resource = await resourceReadyEvent.resource();
    const services = await resourceReadyEvent.services();
    const loggerFactory = await services.getLoggerFactory();
    const logger = await loggerFactory.createLogger("ValidationAppHost.ResourceReady");
    await logger.logInformation("ResourceReady");
});

// ===================================================================
// Pre-existing exports verification (sanity check)
// ===================================================================

// withEnvironment
await container.withEnvironment("MY_VAR", "value");

// withEndpoint
await container.withEndpoint();
await container.withEndpoint({ name: "callback-endpoint" });
await container.withEndpointCallback("callback-endpoint", async (updateContext) => {
    await updateContext.port.set(5001);
    await updateContext.targetPort.set(5002);
    await updateContext.isExternal.set(false);
}, { createIfNotExists: false });

// withHttpEndpoint
await container.withHttpEndpoint();
await container.withHttpEndpoint({ name: "callback-http" });
await container.withHttpEndpointCallback(async (updateContext) => {
    await updateContext.port.set(8081);
    await updateContext.targetPort.set(8082);
    await updateContext.isProxied.set(false);
}, { name: "callback-http", createIfNotExists: false });
await container.withHttpEndpointCallback(async (updateContext) => {
    await updateContext.port.set(8083);
    await updateContext.targetPort.set(8084);
    await updateContext.isProxied.set(false);
}, { name: "created-http" });

// withHttpsEndpoint
await container.withHttpsEndpoint();
await container.withHttpsEndpoint({ name: "callback-https" });
await container.withHttpsEndpointCallback(async (updateContext) => {
    await updateContext.port.set(8444);
    await updateContext.targetPort.set(8443);
    await updateContext.isProxied.set(false);
}, { name: "callback-https", createIfNotExists: false });
await container.withHttpsEndpointCallback(async (updateContext) => {
    await updateContext.port.set(8445);
    await updateContext.targetPort.set(8446);
    await updateContext.isProxied.set(false);
}, { name: "created-https" });

// withExternalHttpEndpoints
await container.withExternalHttpEndpoints();

// asHttp2Service
await container.asHttp2Service();

// withArgs
await container.withArgs(["--verbose"]);

// withParentRelationship
await container.withParentRelationship(exe);
await projectWithoutLaunchProfile.withParentRelationship(project);

// withExplicitStart
await container.withExplicitStart();

// withUrl
await container.withUrl("http://localhost:8080");

// withUrl - ReferenceExpression
await container.withUrl(refExpr`http://${endpoint}`);

// withHealthCheck
await container.withHealthCheck("http");
await container.withHealthCheck("custom_check");

// withCommand
await container.withCommand("noop", "Noop", async () => {
    return { success: true };
}, {
    commandOptions: {
        updateState: async (ctx) => {
            const snapshot = await ctx.resourceSnapshot();
            const updateStateServices = await ctx.services();
            const updateStateLoggerFactory = await updateStateServices.getLoggerFactory();
            const updateStateLogger = await updateStateLoggerFactory.createLogger("ValidationAppHost.UpdateCommandState");
            await updateStateLogger.logInformation("UpdateCommandState services");

            return snapshot.healthStatus === HealthStatus.Healthy
                ? ResourceCommandState.Enabled
                : ResourceCommandState.Disabled;
        },
    },
});
await container.withCommand("echo", "Echo", async (ctx) => {
    const commandInputs = await ctx.arguments();
    const message = await commandInputs.value("message");
    const echoServices = await ctx.services();
    const echoLoggerFactory = await echoServices.getLoggerFactory();
    const echoLogger = await echoLoggerFactory.createLogger("ValidationAppHost.EchoCommand");
    await echoLogger.logInformation("Echo command services");

    return { success: message === "hello" };
}, {
    commandOptions: {
        arguments: [
            {
                name: "message",
                inputType: InputType.Text,
                required: true
            }
        ],
        validateArguments: async (ctx) => {
            const validationServices = await ctx.services();
            const validationLoggerFactory = await validationServices.getLoggerFactory();
            const validationLogger = await validationLoggerFactory.createLogger("ValidationAppHost.ValidateCommandArguments");
            await validationLogger.logInformation("Validate command arguments services");
        }
    }
});
await container.withCommand("restart", "Restart", async (ctx) => {
    const cancellationToken = await ctx.cancellationToken();

    return await resourceCommandService.executeCommandAsync(container, "echo", {
        arguments: { message: "hello" },
        cancellationToken
    });
});
// Test bench for the polyglot IInteractionService API: prompts for a region, then dynamically
// loads the available zones for that region into a second choice input. Reached via the command's
// service provider (services().getInteractionService()), which only prompts when the
// interaction service is available (the interactive dashboard path).
await container.withCommand("pick-zone", "Pick Zone", async (ctx) => {
    const interactionService = await ctx.services().getInteractionService();

    if (!(await interactionService.isAvailable())) {
        return { success: true, message: "Interaction service is not available." };
    }

    const regionInput = await interactionService.createChoiceInput("region", {
        choices: [{ value: "us", label: "United States" }, { value: "eu", label: "Europe" }]
    });

    const zoneInput = await interactionService
        .createChoiceInput("zone")
        .withDynamicLoading(async (loadContext) => {
            const region = await loadContext.inputs().value("region");

            const zones: InteractionChoiceOption[] = region === "eu"
                ? [{ value: "eu-west", label: "EU West" }, { value: "eu-north", label: "EU North" }]
                : [{ value: "us-east", label: "US East" }, { value: "us-west", label: "US West" }];

            await loadContext.input().setChoiceOptions(zones);
        });

    const result = await interactionService.promptInputs(
        "Pick a zone",
        "Choose a region, then pick a zone from the dynamically loaded options.",
        [regionInput, zoneInput]);

    const canceled = await result.canceled();
    return { success: !canceled, canceled };
});
// Exhaustive coverage of the remaining IInteractionService surface so every newly added member is
// exercised by the polyglot typecheck: all prompt overloads, every input factory and builder method,
// the dynamic-loading context accessors/setters, and the option/result DTO fields.
await container.withCommand("interaction-showcase", "Interaction Showcase", async (ctx) => {
    const interactionService = await ctx.services().getInteractionService();

    if (!(await interactionService.isAvailable())) {
        return { success: true, message: "Interaction service is not available." };
    }

    const confirmation = await interactionService.promptConfirmation("Confirm", "Proceed?", {
        primaryButtonText: "Yes",
        secondaryButtonText: "No",
        showSecondaryButton: true,
        showDismiss: true,
        enableMessageMarkdown: true,
        intent: MessageIntent.Confirmation
    });

    const messageBox = await interactionService.promptMessageBox("Notice", "Read this.", {
        primaryButtonText: "OK",
        intent: MessageIntent.Information
    });

    const notification = await interactionService.promptNotification("Heads up", "Something happened.", {
        intent: MessageIntent.Warning,
        linkText: "Learn more",
        linkUrl: "https://aspire.dev",
        showDismiss: true
    });

    const textInput = await interactionService.createTextInput("name", {
        label: "Name",
        description: "Your **name**",
        enableDescriptionMarkdown: true,
        required: true,
        placeholder: "Jane Doe",
        value: "Jane",
        maxLength: 64,
        disabled: false
    });
    const secretInput = await interactionService.createSecretInput("password", { required: true });
    const booleanInput = await interactionService.createBooleanInput("enabled", { value: "true" });
    const numberInput = await interactionService.createNumberInput("count", { value: "1" });
    const choiceInput = await interactionService.createChoiceInput("color", {
        choices: [{ value: "r", label: "Red" }, { value: "g", label: "Green" }],
        options: { allowCustomChoice: true }
    });
    const presetInput = await interactionService.createTextInput("greeting").withValue("hello");
    const sizeInput = await interactionService
        .createChoiceInput("size")
        .withChoiceOptions([{ value: "s", label: "Small" }, { value: "l", label: "Large" }]);
    const dependentInput = await interactionService
        .createChoiceInput("shade")
        .withDynamicLoading(async (loadContext) => {
            const input = loadContext.input();
            const inputName = await input.getName();
            const color = await loadContext.inputs().value("color");

            await input.setChoiceOptions(color === "r"
                ? [{ value: "crimson", label: "Crimson" }, { value: "scarlet", label: "Scarlet" }]
                : [{ value: "lime", label: "Lime" }, { value: "forest", label: "Forest" }]);
            await input.setValue(inputName);
        }, {
            alwaysLoadOnStart: true,
            dependsOnInputs: ["color"]
        });

    const single = await interactionService.promptInput(
        "Single input",
        "Enter a value.",
        interactionService.createTextInput("solo"),
        {
            primaryButtonText: "Save",
            validationCallback: async (validationContext) => {
                const solo = await validationContext.inputs().value("solo");
                if (!solo) {
                    await validationContext.addValidationError("solo", "A value is required.");
                }
            }
        });

    const multi = await interactionService.promptInputs(
        "Multiple inputs",
        "Fill out the form.",
        [textInput, secretInput, booleanInput, numberInput, choiceInput, presetInput, sizeInput, dependentInput],
        {
            primaryButtonText: "Submit",
            enableMessageMarkdown: true,
            validationCallback: async (validationContext) => {
                const name = await validationContext.inputs().value("name");
                if (name === "bad") {
                    await validationContext.addValidationError("name", "Name cannot be 'bad'.");
                }
            }
        });

    const selectedColor = await multi.inputs().value("color");
    const soloValue = single.input?.value;

    const multiCanceled = await multi.canceled();
    const success = !confirmation.canceled
        && confirmation.value === true
        && !messageBox.canceled
        && !notification.canceled
        && !single.canceled
        && !multiCanceled;

    return {
        success,
        canceled: multiCanceled,
        message: `color=${selectedColor ?? ""} solo=${soloValue ?? ""}`
    };
});

// withHttpsCertificateConfiguration
await container.withHttpsCertificateConfiguration(async (certCtx) => {
    const _certResource = await certCtx.resource();
    const _certIsRunMode: boolean = await certCtx.executionContext().isRunMode();
    const certificatePath = await certCtx.certificatePath();
    const keyPath = await certCtx.keyPath();
    const certArgs = await certCtx.arguments();
    await certArgs.add("--certificate");
    await certArgs.add(certificatePath);
    await certArgs.add("--key");
    await certArgs.add(keyPath);
    const certEnv = await certCtx.environment();
    await certEnv.set("Kestrel__Certificates__Path", certificatePath);
    await certEnv.set("Kestrel__Certificates__KeyPath", keyPath);
});

// subscribeHttpsEndpointsUpdate
await container.subscribeHttpsEndpointsUpdate(async (httpsCtx) => {
    const _httpsResource = await httpsCtx.resource();
    const _httpsModel = await httpsCtx.model();
    const httpsServices = await httpsCtx.services();
    const httpsLoggerFactory = await httpsServices.getLoggerFactory();
    const httpsLogger = await httpsLoggerFactory.createLogger("ValidationAppHost.HttpsEndpointsUpdate");
    await httpsLogger.logInformation("HttpsEndpointsUpdate services");
});

// withContainerBuildOptions
await container.withContainerBuildOptions(async (buildCtx) => {
    await buildCtx.destination.set(ContainerImageDestination.Registry);
    await buildCtx.imageFormat.set(ContainerImageFormat.Oci);
    await buildCtx.targetPlatform.set(ContainerTargetPlatform.LinuxAmd64);
    await buildCtx.outputPath.set("./artifacts/container-image");
    await buildCtx.localImageName.set("validation-image");
    await buildCtx.localImageTag.set("latest");
    const _buildResource = await buildCtx.resource();
    const _buildExecutionContext = await buildCtx.executionContext();
    const buildServices = await buildCtx.services();
    const buildLoggerFactory = await buildServices.getLoggerFactory();
    const buildLogger = await buildLoggerFactory.createLogger("ValidationAppHost.ContainerBuildOptions");
    await buildLogger.logInformation("ContainerBuildOptions services");
});

// withProcessCommand
await container.withProcessCommand("dotnet-version", "Show .NET version", {
    executablePath: "dotnet",
    arguments: ["--version"],
    commandOptions: {
        description: "Runs dotnet --version from a TypeScript AppHost.",
        iconName: "WindowConsole",
    },
    maxOutputLineCount: 10,
    displayImmediately: false,
});
await container.withProcessCommand("node-stdin", "Node stdin", {
    executablePath: "node",
    arguments: [processCommandStdinScriptPath],
    standardInputContent: "hello-from-typescript",
    commandOptions: {
        description: "Runs node and writes command input to stdin.",
        iconName: "WindowConsole",
    },
    maxOutputLineCount: 10,
});
await container.withProcessCommand("node-message", "Node message", {
    createProcessSpec: async (context) => {
        const args = await context.arguments();
        const message = await args.requiredValue("message");

        return {
            executablePath: "node",
            arguments: ["-e", "console.log(process.argv[1])", message],
        };
    },
    commandOptions: {
        description: "Runs node with an argument supplied when the process command is invoked.",
        iconName: "WindowConsole",
        arguments: [
            {
                name: "message",
                inputType: InputType.Text,
                required: true,
            },
        ],
    },
    maxOutputLineCount: 10,
    displayImmediately: false,
});

// withHttpCommand
await container.withHttpCommand("/health", "Health Check");
await container.withHttpCommand("/api/reset", "Reset", {
    methodName: "POST",
    prepareRequest: async (context) => {
        const args = await context.arguments();
        const message = await args.requiredValue("message");

        return {
            content: JSON.stringify({ message }),
            contentType: "application/json",
            headers: {
                "X-Message": message,
            },
        };
    },
    commandOptions: {
        arguments: [
            {
                name: "message",
                inputType: InputType.Text,
                required: true,
            },
        ],
    },
    confirmationMessage: "Are you sure?",
});

const app = await builder.build();
await app.run();
