//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgentCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgentCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.AgentCommandStrings", typeof(AgentCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage AI agent environment configuration..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start the MCP (Model Context Protocol) server..
        /// </summary>
        internal static string McpCommand_Description {
            get {
                return ResourceManager.GetString("McpCommand_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initialize agent environment configuration for detected agents..
        /// </summary>
        internal static string InitCommand_Description {
            get {
                return ResourceManager.GetString("InitCommand_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update {0} config to use new 'agent mcp' command.
        /// </summary>
        internal static string DeprecatedConfigUpdate_Description {
            get {
                return ResourceManager.GetString("DeprecatedConfigUpdate_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} config uses deprecated 'mcp start' command.
        /// </summary>
        internal static string DeprecatedConfigWarning {
            get {
                return ResourceManager.GetString("DeprecatedConfigWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run 'aspire agent init' to update configuration.
        /// </summary>
        internal static string DeprecatedConfigFix {
            get {
                return ResourceManager.GetString("DeprecatedConfigFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The following agent configurations use the deprecated 'mcp start' command. Update them?.
        /// </summary>
        internal static string ConfigUpdatesSelectPrompt {
            get {
                return ResourceManager.GetString("ConfigUpdatesSelectPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration file '{0}' contains malformed JSON. Please fix the file manually and re-run the command..
        /// </summary>
        internal static string MalformedConfigFileError {
            get {
                return ResourceManager.GetString("MalformedConfigFileError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping update of '{0}'..
        /// </summary>
        internal static string SkippedMalformedConfigFile {
            get {
                return ResourceManager.GetString("SkippedMalformedConfigFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration completed with errors. Please fix the reported issues and re-run the command..
        /// </summary>
        internal static string ConfigurationCompletedWithErrors {
            get {
                return ResourceManager.GetString("ConfigurationCompletedWithErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None — skip.
        /// </summary>
        internal static string SkipNoneDescription {
            get {
                return ResourceManager.GetString("SkipNoneDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Where should skill files be installed?.
        /// </summary>
        internal static string InitCommand_SelectSkillLocations {
            get {
                return ResourceManager.GetString("InitCommand_SelectSkillLocations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Which skills should be installed?.
        /// </summary>
        internal static string InitCommand_SelectSkills {
            get {
                return ResourceManager.GetString("InitCommand_SelectSkills", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install Aspire MCP server.
        /// </summary>
        internal static string InitCommand_ConfigureMcpServer {
            get {
                return ResourceManager.GetString("InitCommand_ConfigureMcpServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed Playwright CLI..
        /// </summary>
        internal static string InitCommand_InstalledPlaywrightCli {
            get {
                return ResourceManager.GetString("InitCommand_InstalledPlaywrightCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playwright CLI requires npm, which was not found on PATH. Skipping installation..
        /// </summary>
        internal static string InitCommand_PlaywrightCliSkipped {
            get {
                return ResourceManager.GetString("InitCommand_PlaywrightCliSkipped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed Aspire agent skills:.
        /// </summary>
        internal static string InitCommand_InstalledSkillsSummary {
            get {
                return ResourceManager.GetString("InitCommand_InstalledSkillsSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skills: {0}.
        /// </summary>
        internal static string InitCommand_InstalledSkillsSummarySkills {
            get {
                return ResourceManager.GetString("InitCommand_InstalledSkillsSummarySkills", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Locations: {0}.
        /// </summary>
        internal static string InitCommand_InstalledSkillsSummaryLocations {
            get {
                return ResourceManager.GetString("InitCommand_InstalledSkillsSummaryLocations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0} skill at {1}: {2}..
        /// </summary>
        internal static string InitCommand_FailedToInstallSkill {
            get {
                return ResourceManager.GetString("InitCommand_FailedToInstallSkill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (configures detected agent environments).
        /// </summary>
        internal static string InitCommand_ConfiguresDetectedAgentEnvironments {
            get {
                return ResourceManager.GetString("InitCommand_ConfiguresDetectedAgentEnvironments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire CLI commands and workflows for distributed apps.
        /// </summary>
        internal static string SkillDescription_Aspire {
            get {
                return ResourceManager.GetString("SkillDescription_Aspire", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire deployment target selection, preflight, publish, and deploy workflows.
        /// </summary>
        internal static string SkillDescription_AspireDeployment {
            get {
                return ResourceManager.GetString("SkillDescription_AspireDeployment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browser automation and functional testing.
        /// </summary>
        internal static string SkillDescription_PlaywrightCli {
            get {
                return ResourceManager.GetString("SkillDescription_PlaywrightCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Query .NET API surfaces across NuGet packages and platform libraries.
        /// </summary>
        internal static string SkillDescription_DotnetInspect {
            get {
                return ResourceManager.GetString("SkillDescription_DotnetInspect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One-time setup: wire up AppHost with discovered projects.
        /// </summary>
        internal static string SkillDescription_Aspireify {
            get {
                return ResourceManager.GetString("SkillDescription_Aspireify", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standard (.agents/skills/).
        /// </summary>
        internal static string SkillLocation_StandardName {
            get {
                return ResourceManager.GetString("SkillLocation_StandardName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supported by VS Code, GitHub Copilot, and OpenCode (also installs at ~/).
        /// </summary>
        internal static string SkillLocation_StandardDescription {
            get {
                return ResourceManager.GetString("SkillLocation_StandardDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Claude Code (.claude/skills/).
        /// </summary>
        internal static string SkillLocation_ClaudeCodeName {
            get {
                return ResourceManager.GetString("SkillLocation_ClaudeCodeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required for Claude Code.
        /// </summary>
        internal static string SkillLocation_ClaudeCodeDescription {
            get {
                return ResourceManager.GetString("SkillLocation_ClaudeCodeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VS Code / GitHub Copilot (.github/skills/).
        /// </summary>
        internal static string SkillLocation_GitHubSkillsName {
            get {
                return ResourceManager.GetString("SkillLocation_GitHubSkillsName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legacy location for GitHub Copilot skills.
        /// </summary>
        internal static string SkillLocation_GitHubSkillsDescription {
            get {
                return ResourceManager.GetString("SkillLocation_GitHubSkillsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OpenCode (.opencode/skill/).
        /// </summary>
        internal static string SkillLocation_OpenCodeName {
            get {
                return ResourceManager.GetString("SkillLocation_OpenCodeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legacy location for OpenCode skills.
        /// </summary>
        internal static string SkillLocation_OpenCodeDescription {
            get {
                return ResourceManager.GetString("SkillLocation_OpenCodeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installing Aspire skills....
        /// </summary>
        internal static string AspireSkillsInstaller_InstallingStatus {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_InstallingStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire skills could not be downloaded from the verified GitHub release asset, and no valid cached or embedded bundle is available..
        /// </summary>
        internal static string AspireSkillsInstaller_GitHubUnavailable {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_GitHubUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire skills bundle is invalid: {0}.
        /// </summary>
        internal static string AspireSkillsInstaller_InvalidBundle {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_InvalidBundle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Embedded Aspire skills bundle metadata is invalid: {0}.
        /// </summary>
        internal static string AspireSkillsInstaller_InvalidMetadata {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_InvalidMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Embedded Aspire skills metadata must specify a version..
        /// </summary>
        internal static string AspireSkillsInstaller_MissingMetadataVersion {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_MissingMetadataVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Embedded Aspire skills metadata repository '{0}' does not match expected repository '{1}'..
        /// </summary>
        internal static string AspireSkillsInstaller_MetadataRepositoryMismatch {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_MetadataRepositoryMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Embedded Aspire skills metadata must specify a GitHub release tag..
        /// </summary>
        internal static string AspireSkillsInstaller_MissingMetadataTag {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_MissingMetadataTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Embedded Aspire skills metadata must specify a release asset name..
        /// </summary>
        internal static string AspireSkillsInstaller_MissingMetadataAssetName {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_MissingMetadataAssetName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Embedded Aspire skills metadata must specify the release asset SHA-256 hash..
        /// </summary>
        internal static string AspireSkillsInstaller_MissingMetadataSha256 {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_MissingMetadataSha256", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Embedded Aspire skills archive failed SHA-256 verification. Expected '{0}', got '{1}'..
        /// </summary>
        internal static string AspireSkillsInstaller_ArchiveHashVerificationFailed {
            get {
                return ResourceManager.GetString("AspireSkillsInstaller_ArchiveHashVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installing Playwright CLI....
        /// </summary>
        internal static string PlaywrightCliInstaller_InstallingStatus {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_InstallingStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve {0} from the npm registry..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToResolvePackage {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToResolvePackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provenance verification failed for {0}: {1}.
        /// </summary>
        internal static string PlaywrightCliInstaller_ProvenanceVerificationFailed {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_ProvenanceVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to download {0}..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToDownload {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToDownload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Integrity verification failed for {0}. The downloaded package may have been tampered with..
        /// </summary>
        internal static string PlaywrightCliInstaller_IntegrityVerificationFailed {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_IntegrityVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0} globally via npm..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToInstallGlobally {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToInstallGlobally", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to generate Playwright CLI skill files..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToGenerateSkillFiles {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToGenerateSkillFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed Playwright CLI (some locations failed to mirror)..
        /// </summary>
        internal static string PlaywrightCliInstaller_InstalledWithMirrorWarnings {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_InstalledWithMirrorWarnings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path to the workspace root directory.
        /// </summary>
        internal static string InitCommand_WorkspaceRootOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_WorkspaceRootOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of skill locations to install (e.g. {0}), '{1}', or '{2}'.
        /// </summary>
        internal static string InitCommand_SkillLocationsOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_SkillLocationsOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of skills to install. Bundle skills are loaded dynamically; CLI-provided skills include {0}. Use '{1}' or '{2}'.
        /// </summary>
        internal static string InitCommand_SkillsOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_SkillsOptionDescription", resourceCulture);
            }
        }
    }
}
