//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiCommandStrings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.ApiCommandStrings", typeof(ApiCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Description => ResourceManager.GetString("Description", resourceCulture);

        internal static string ListDescription => ResourceManager.GetString("ListDescription", resourceCulture);

        internal static string SearchDescription => ResourceManager.GetString("SearchDescription", resourceCulture);

        internal static string GetDescription => ResourceManager.GetString("GetDescription", resourceCulture);

        internal static string ScopeArgumentDescription => ResourceManager.GetString("ScopeArgumentDescription", resourceCulture);

        internal static string QueryArgumentDescription => ResourceManager.GetString("QueryArgumentDescription", resourceCulture);

        internal static string IdArgumentDescription => ResourceManager.GetString("IdArgumentDescription", resourceCulture);

        internal static string FormatOptionDescription => ResourceManager.GetString("FormatOptionDescription", resourceCulture);

        internal static string LimitOptionDescription => ResourceManager.GetString("LimitOptionDescription", resourceCulture);

        internal static string LanguageOptionDescription => ResourceManager.GetString("LanguageOptionDescription", resourceCulture);

        internal static string LoadingApiDocumentation => ResourceManager.GetString("LoadingApiDocumentation", resourceCulture);

        internal static string NoApiEntriesFound => ResourceManager.GetString("NoApiEntriesFound", resourceCulture);

        internal static string NoResultsFound => ResourceManager.GetString("NoResultsFound", resourceCulture);

        internal static string ApiNotFound => ResourceManager.GetString("ApiNotFound", resourceCulture);

        internal static string FoundApiEntries => ResourceManager.GetString("FoundApiEntries", resourceCulture);

        internal static string FoundSearchResults => ResourceManager.GetString("FoundSearchResults", resourceCulture);

        internal static string HeaderName => ResourceManager.GetString("HeaderName", resourceCulture);

        internal static string HeaderId => ResourceManager.GetString("HeaderId", resourceCulture);

        internal static string HeaderLanguage => ResourceManager.GetString("HeaderLanguage", resourceCulture);

        internal static string HeaderKind => ResourceManager.GetString("HeaderKind", resourceCulture);

        internal static string HeaderGroup => ResourceManager.GetString("HeaderGroup", resourceCulture);

        internal static string HeaderScore => ResourceManager.GetString("HeaderScore", resourceCulture);
    }
}
