//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleActivityLoggerStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleActivityLoggerStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.ConsoleActivityLoggerStrings", typeof(ConsoleActivityLoggerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string ActivityStarting {
            get {
                return ResourceManager.GetString("ActivityStarting", resourceCulture);
            }
        }

        internal static string ActivityStartingWithName {
            get {
                return ResourceManager.GetString("ActivityStartingWithName", resourceCulture);
            }
        }

        internal static string SummaryStepsSucceededWithTotal {
            get {
                return ResourceManager.GetString("SummaryStepsSucceededWithTotal", resourceCulture);
            }
        }

        internal static string SummaryStepsSucceeded {
            get {
                return ResourceManager.GetString("SummaryStepsSucceeded", resourceCulture);
            }
        }

        internal static string SummaryWarningsSingular {
            get {
                return ResourceManager.GetString("SummaryWarningsSingular", resourceCulture);
            }
        }

        internal static string SummaryWarningsPlural {
            get {
                return ResourceManager.GetString("SummaryWarningsPlural", resourceCulture);
            }
        }

        internal static string SummaryFailed {
            get {
                return ResourceManager.GetString("SummaryFailed", resourceCulture);
            }
        }

        internal static string SummaryTotalTime {
            get {
                return ResourceManager.GetString("SummaryTotalTime", resourceCulture);
            }
        }

        internal static string SummaryLogLevelHelp {
            get {
                return ResourceManager.GetString("SummaryLogLevelHelp", resourceCulture);
            }
        }

        internal static string PipelineSucceeded {
            get {
                return ResourceManager.GetString("PipelineSucceeded", resourceCulture);
            }
        }

        internal static string PipelineFailed {
            get {
                return ResourceManager.GetString("PipelineFailed", resourceCulture);
            }
        }
    }
}
