//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardCommandStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardCommandStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.DashboardCommandStrings", typeof(DashboardCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        public static string RunDescription {
            get {
                return ResourceManager.GetString("RunDescription", resourceCulture);
            }
        }

        public static string BundleNotAvailable {
            get {
                return ResourceManager.GetString("BundleNotAvailable", resourceCulture);
            }
        }

        public static string BundleLayoutNotFound {
            get {
                return ResourceManager.GetString("BundleLayoutNotFound", resourceCulture);
            }
        }

        public static string ManagedBinaryNotFound {
            get {
                return ResourceManager.GetString("ManagedBinaryNotFound", resourceCulture);
            }
        }

        public static string DashboardStarted {
            get {
                return ResourceManager.GetString("DashboardStarted", resourceCulture);
            }
        }

        public static string DashboardExitedWithError {
            get {
                return ResourceManager.GetString("DashboardExitedWithError", resourceCulture);
            }
        }

        public static string StartingDashboard {
            get {
                return ResourceManager.GetString("StartingDashboard", resourceCulture);
            }
        }

        public static string DashboardStartTimedOut {
            get {
                return ResourceManager.GetString("DashboardStartTimedOut", resourceCulture);
            }
        }

        public static string FrontendUrlOptionDescription {
            get {
                return ResourceManager.GetString("FrontendUrlOptionDescription", resourceCulture);
            }
        }

        public static string OtlpGrpcUrlOptionDescription {
            get {
                return ResourceManager.GetString("OtlpGrpcUrlOptionDescription", resourceCulture);
            }
        }

        public static string OtlpHttpUrlOptionDescription {
            get {
                return ResourceManager.GetString("OtlpHttpUrlOptionDescription", resourceCulture);
            }
        }

        public static string AllowAnonymousOptionDescription {
            get {
                return ResourceManager.GetString("AllowAnonymousOptionDescription", resourceCulture);
            }
        }

        public static string ConfigFilePathOptionDescription {
            get {
                return ResourceManager.GetString("ConfigFilePathOptionDescription", resourceCulture);
            }
        }

        public static string DashboardLabel {
            get {
                return ResourceManager.GetString("DashboardLabel", resourceCulture);
            }
        }

        public static string OtlpGrpcLabel {
            get {
                return ResourceManager.GetString("OtlpGrpcLabel", resourceCulture);
            }
        }

        public static string OtlpHttpLabel {
            get {
                return ResourceManager.GetString("OtlpHttpLabel", resourceCulture);
            }
        }

        public static string LogsLabel {
            get {
                return ResourceManager.GetString("LogsLabel", resourceCulture);
            }
        }

        public static string DashboardExitedUnexpectedError {
            get {
                return ResourceManager.GetString("DashboardExitedUnexpectedError", resourceCulture);
            }
        }

        public static string DashboardExitedValidationFailure {
            get {
                return ResourceManager.GetString("DashboardExitedValidationFailure", resourceCulture);
            }
        }

        public static string DashboardExitedAddressInUse {
            get {
                return ResourceManager.GetString("DashboardExitedAddressInUse", resourceCulture);
            }
        }

        public static string StoppingDashboard {
            get {
                return ResourceManager.GetString("StoppingDashboard", resourceCulture);
            }
        }

        public static string DashboardFailedToStart {
            get {
                return ResourceManager.GetString("DashboardFailedToStart", resourceCulture);
            }
        }

    }
}
