//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StopCommandStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StopCommandStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.StopCommandStrings", typeof(StopCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        public static string ProjectArgumentDescription {
            get {
                return ResourceManager.GetString("ProjectArgumentDescription", resourceCulture);
            }
        }

        public static string StoppingAppHost {
            get {
                return ResourceManager.GetString("StoppingAppHost", resourceCulture);
            }
        }

        public static string AppHostStoppedSuccessfully {
            get {
                return ResourceManager.GetString("AppHostStoppedSuccessfully", resourceCulture);
            }
        }

        public static string AppHostIdentifierWithProcessId {
            get {
                return ResourceManager.GetString("AppHostIdentifierWithProcessId", resourceCulture);
            }
        }

        public static string MultipleAppHostsRunning {
            get {
                return ResourceManager.GetString("MultipleAppHostsRunning", resourceCulture);
            }
        }

        public static string FailedToStopAppHost {
            get {
                return ResourceManager.GetString("FailedToStopAppHost", resourceCulture);
            }
        }

        public static string FoundRunningAppHost {
            get {
                return ResourceManager.GetString("FoundRunningAppHost", resourceCulture);
            }
        }

        public static string SendingStopSignal {
            get {
                return ResourceManager.GetString("SendingStopSignal", resourceCulture);
            }
        }

        public static string SelectAppHostAction {
            get {
                return ResourceManager.GetString("SelectAppHostAction", resourceCulture);
            }
        }

        public static string AllOptionDescription {
            get {
                return ResourceManager.GetString("AllOptionDescription", resourceCulture);
            }
        }

        public static string ForceOptionDescription {
            get {
                return ResourceManager.GetString("ForceOptionDescription", resourceCulture);
            }
        }

        public static string CouldNotDetermineAppHostPath {
            get {
                return ResourceManager.GetString("CouldNotDetermineAppHostPath", resourceCulture);
            }
        }

        public static string CleaningPersistentResources {
            get {
                return ResourceManager.GetString("CleaningPersistentResources", resourceCulture);
            }
        }

        public static string PersistentResourcesCleaned {
            get {
                return ResourceManager.GetString("PersistentResourcesCleaned", resourceCulture);
            }
        }

        public static string DcpCleanupUnavailable {
            get {
                return ResourceManager.GetString("DcpCleanupUnavailable", resourceCulture);
            }
        }

        public static string DcpCleanupCompatibilityCheckFailed {
            get {
                return ResourceManager.GetString("DcpCleanupCompatibilityCheckFailed", resourceCulture);
            }
        }

        public static string DcpCleanupUnsupportedAppHostVersion {
            get {
                return ResourceManager.GetString("DcpCleanupUnsupportedAppHostVersion", resourceCulture);
            }
        }

        public static string DcpCleanupFailed {
            get {
                return ResourceManager.GetString("DcpCleanupFailed", resourceCulture);
            }
        }

        public static string DcpCleanupExitCode {
            get {
                return ResourceManager.GetString("DcpCleanupExitCode", resourceCulture);
            }
        }

        public static string MultipleAppHostsNonInteractive {
            get {
                return ResourceManager.GetString("MultipleAppHostsNonInteractive", resourceCulture);
            }
        }

        public static string AllAndProjectMutuallyExclusive {
            get {
                return ResourceManager.GetString("AllAndProjectMutuallyExclusive", resourceCulture);
            }
        }

        public static string UnknownAspireHostingVersion {
            get {
                return ResourceManager.GetString("UnknownAspireHostingVersion", resourceCulture);
            }
        }

    }
}
