//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerminalCommandStrings {

        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal TerminalCommandStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    resourceMan = new System.Resources.ResourceManager("Aspire.Cli.Resources.TerminalCommandStrings", typeof(TerminalCommandStrings).Assembly);
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string LookingUpResource {
            get {
                return ResourceManager.GetString("LookingUpResource", resourceCulture);
            }
        }

        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }

        public static string DiscoveringSessions {
            get {
                return ResourceManager.GetString("DiscoveringSessions", resourceCulture);
            }
        }

        public static string TerminalUnavailable {
            get {
                return ResourceManager.GetString("TerminalUnavailable", resourceCulture);
            }
        }

        public static string ReplicaNotFound {
            get {
                return ResourceManager.GetString("ReplicaNotFound", resourceCulture);
            }
        }

        public static string ReplicaRequired {
            get {
                return ResourceManager.GetString("ReplicaRequired", resourceCulture);
            }
        }

        public static string SelectReplica {
            get {
                return ResourceManager.GetString("SelectReplica", resourceCulture);
            }
        }

        public static string ReplicaRunning {
            get {
                return ResourceManager.GetString("ReplicaRunning", resourceCulture);
            }
        }

        public static string ReplicaExited {
            get {
                return ResourceManager.GetString("ReplicaExited", resourceCulture);
            }
        }

        public static string TapeDescription {
            get {
                return ResourceManager.GetString("TapeDescription", resourceCulture);
            }
        }

        public static string TapePlayDescription {
            get {
                return ResourceManager.GetString("TapePlayDescription", resourceCulture);
            }
        }

        public static string ResourceArgumentDescription {
            get {
                return ResourceManager.GetString("ResourceArgumentDescription", resourceCulture);
            }
        }

        public static string ResourceRequired {
            get {
                return ResourceManager.GetString("ResourceRequired", resourceCulture);
            }
        }

        public static string TapeFileDescription {
            get {
                return ResourceManager.GetString("TapeFileDescription", resourceCulture);
            }
        }

        public static string ReplicaOptionDescription {
            get {
                return ResourceManager.GetString("ReplicaOptionDescription", resourceCulture);
            }
        }

        public static string TapeSelectAppHostAction {
            get {
                return ResourceManager.GetString("TapeSelectAppHostAction", resourceCulture);
            }
        }

        public static string TerminalIncompatible {
            get {
                return ResourceManager.GetString("TerminalIncompatible", resourceCulture);
            }
        }

        public static string TapeFileReadFailed {
            get {
                return ResourceManager.GetString("TapeFileReadFailed", resourceCulture);
            }
        }

        public static string TapeTimeoutInvalid {
            get {
                return ResourceManager.GetString("TapeTimeoutInvalid", resourceCulture);
            }
        }

        public static string TapePlaybackFailed {
            get {
                return ResourceManager.GetString("TapePlaybackFailed", resourceCulture);
            }
        }

        public static string TapeConnectionClosed {
            get {
                return ResourceManager.GetString("TapeConnectionClosed", resourceCulture);
            }
        }

        public static string TapeTimeoutDescription {
            get {
                return ResourceManager.GetString("TapeTimeoutDescription", resourceCulture);
            }
        }

        public static string TapeTimeout {
            get {
                return ResourceManager.GetString("TapeTimeout", resourceCulture);
            }
        }
    }
}
