// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.CommandLine;
using System.Diagnostics;

var runIdOption = new Option<string>("--run-id") { Description = "Workflow run ID" };
var repoOption = new Option<string>("--repo") { Description = "Repository (owner/repo)" };
var jsonOption = new Option<string>("--json") { Description = "Path to cached JSON data file (ci-timeline format)" };
var outputOption = new Option<string>("--output", "-o") { Description = "Write output to file (.html for standalone page)" };
var minTotalOption = new Option<double>("--min-total") { Description = "Only show jobs with total pipeline time above N minutes", DefaultValueFactory = _ => 0 };
var openOption = new Option<bool>("--open") { Description = "Open the HTML output in the default browser" };

var rootCommand = new RootCommand("Generate CI timeline summary for GitHub Actions step summary.")
{
    runIdOption,
    repoOption,
    jsonOption,
    outputOption,
    minTotalOption,
    openOption,
};

rootCommand.SetAction(async (result, ct) =>
{
    var runId = result.GetValue(runIdOption);
    var repo = result.GetValue(repoOption);
    var jsonPath = result.GetValue(jsonOption);
    var outputPath = result.GetValue(outputOption);
    var minTotalMinutes = result.GetValue(minTotalOption);
    var openBrowser = result.GetValue(openOption);

    System.Text.Json.JsonElement runInfo;
    List<System.Text.Json.JsonElement> jobs;

    if (!string.IsNullOrEmpty(jsonPath))
    {
        (runInfo, jobs) = GitHubApi.LoadJsonData(jsonPath);
    }
    else
    {
        repo ??= Environment.GetEnvironmentVariable("GITHUB_REPOSITORY") ?? "microsoft/aspire";
        runId = string.IsNullOrEmpty(runId) ? Environment.GetEnvironmentVariable("GITHUB_RUN_ID") : runId;
        if (string.IsNullOrEmpty(runId))
        {
            Console.Error.WriteLine("Error: --run-id is required (or set GITHUB_RUN_ID)");
            return;
        }

        (runInfo, jobs) = await GitHubApi.FetchRunDataAsync(repo, runId).ConfigureAwait(false);
    }

    var summary = TimelineRenderer.GenerateSummary(runInfo, jobs, minTotalMinutes);

    var stepSummary = Environment.GetEnvironmentVariable("GITHUB_STEP_SUMMARY");
    var isCi = !string.IsNullOrEmpty(stepSummary);

    // Determine output path — track whether we auto-generated a temp file
    var autoGeneratedOutput = false;
    if (string.IsNullOrEmpty(outputPath) && !isCi)
    {
        var tmpDir = Directory.CreateTempSubdirectory("ci-timeline");
        outputPath = Path.Combine(tmpDir.FullName, "ci-timeline.html");
        autoGeneratedOutput = true;
    }

    if (!string.IsNullOrEmpty(outputPath))
    {
        var isHtml = outputPath.EndsWith(".html", StringComparison.OrdinalIgnoreCase);
        var content = isHtml ? TimelineRenderer.WrapHtml(summary) : summary;
        await File.WriteAllTextAsync(outputPath, content, ct).ConfigureAwait(false);
        Console.Error.WriteLine($"{(isHtml ? "HTML" : "Summary")} written to {outputPath}");

        // Only auto-open for temp files we generated; explicit -o requires --open
        var shouldOpen = openBrowser || (autoGeneratedOutput && isHtml && !isCi);
        if (shouldOpen)
        {
            Process.Start(new ProcessStartInfo
            {
                FileName = outputPath,
                UseShellExecute = true,
            });
        }
    }

    if (isCi && stepSummary is not null)
    {
        await File.AppendAllTextAsync(stepSummary, summary + "\n", ct).ConfigureAwait(false);
        Console.Error.WriteLine("Summary appended to $GITHUB_STEP_SUMMARY");
    }
});

return await rootCommand.Parse(args).InvokeAsync().ConfigureAwait(false);
