//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerminalStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Dashboard.Resources.TerminalStrings", typeof(TerminalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string TerminalTitle {
            get {
                return ResourceManager.GetString("TerminalTitle", resourceCulture);
            }
        }

        public static string TerminalToolbarDecreaseFontSize {
            get {
                return ResourceManager.GetString("TerminalToolbarDecreaseFontSize", resourceCulture);
            }
        }

        public static string TerminalInputLabel {
            get {
                return ResourceManager.GetString("TerminalInputLabel", resourceCulture);
            }
        }

        public static string TerminalMountFailed {
            get {
                return ResourceManager.GetString("TerminalMountFailed", resourceCulture);
            }
        }

        public static string TerminalDisconnected {
            get {
                return ResourceManager.GetString("TerminalDisconnected", resourceCulture);
            }
        }

        public static string TerminalInputFailed {
            get {
                return ResourceManager.GetString("TerminalInputFailed", resourceCulture);
            }
        }

        public static string TerminalSizingFailed {
            get {
                return ResourceManager.GetString("TerminalSizingFailed", resourceCulture);
            }
        }

        public static string TerminalRetry {
            get {
                return ResourceManager.GetString("TerminalRetry", resourceCulture);
            }
        }

        public static string TerminalDismissError {
            get {
                return ResourceManager.GetString("TerminalDismissError", resourceCulture);
            }
        }

        public static string TerminalToolbarIncreaseFontSize {
            get {
                return ResourceManager.GetString("TerminalToolbarIncreaseFontSize", resourceCulture);
            }
        }

        public static string TerminalToolbarGridSize {
            get {
                return ResourceManager.GetString("TerminalToolbarGridSize", resourceCulture);
            }
        }

        public static string TerminalToolbarGridSizeAuto {
            get {
                return ResourceManager.GetString("TerminalToolbarGridSizeAuto", resourceCulture);
            }
        }

        public static string TerminalToolbarOpenInWindow {
            get {
                return ResourceManager.GetString("TerminalToolbarOpenInWindow", resourceCulture);
            }
        }

        public static string TerminalToolbarOpenInWindowBlocked {
            get {
                return ResourceManager.GetString("TerminalToolbarOpenInWindowBlocked", resourceCulture);
            }
        }

        public static string TerminalToolbarOpenInWindowFailed {
            get {
                return ResourceManager.GetString("TerminalToolbarOpenInWindowFailed", resourceCulture);
            }
        }

        public static string TerminalFocusControlsHint {
            get {
                return ResourceManager.GetString("TerminalFocusControlsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle terminal (`).
        /// </summary>
        public static string MainLayoutToggleTerminalDock {
            get {
                return ResourceManager.GetString("MainLayoutToggleTerminalDock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close terminal '{0}'.
        /// </summary>
        public static string TerminalDockCloseTab {
            get {
                return ResourceManager.GetString("TerminalDockCloseTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal close timed out.
        /// </summary>
        public static string TerminalDockCloseTimedOutTitle {
            get {
                return ResourceManager.GetString("TerminalDockCloseTimedOutTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for terminal '{0}' to shut down. Cleanup is continuing in the background..
        /// </summary>
        public static string TerminalDockCloseTimedOutMessage {
            get {
                return ResourceManager.GetString("TerminalDockCloseTimedOutMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open terminal in a new window.
        /// </summary>
        public static string TerminalDockDetach {
            get {
                return ResourceManager.GetString("TerminalDockDetach", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This terminal is running in a separate window..
        /// </summary>
        public static string TerminalDockDetached {
            get {
                return ResourceManager.GetString("TerminalDockDetached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This terminal may still be open in a separate window. Focus it or return it to the panel to continue..
        /// </summary>
        public static string TerminalDockRecoveringWindow {
            get {
                return ResourceManager.GetString("TerminalDockRecoveringWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to recover the terminal window state. Check browser storage permissions, reload, or explicitly return the terminal to the panel..
        /// </summary>
        public static string TerminalWindowTrackingFailed {
            get {
                return ResourceManager.GetString("TerminalWindowTrackingFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The browser blocked the terminal window. Allow pop-ups for the dashboard and try again..
        /// </summary>
        public static string TerminalDockDetachBlocked {
            get {
                return ResourceManager.GetString("TerminalDockDetachBlocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus window.
        /// </summary>
        public static string TerminalDockFocusWindow {
            get {
                return ResourceManager.GetString("TerminalDockFocusWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide terminal panel (`).
        /// </summary>
        public static string TerminalDockHide {
            get {
                return ResourceManager.GetString("TerminalDockHide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} pixels high.
        /// </summary>
        public static string TerminalDockHeight {
            get {
                return ResourceManager.GetString("TerminalDockHeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use Up or Down to resize, Shift for larger steps, Home for minimum height, and End for maximum height..
        /// </summary>
        public static string TerminalDockResizeHelp {
            get {
                return ResourceManager.GetString("TerminalDockResizeHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        public static string TerminalDockTabs {
            get {
                return ResourceManager.GetString("TerminalDockTabs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App host code can open terminals here. Resource terminals are shown separately on their resource pages..
        /// </summary>
        public static string TerminalDockPanelBody {
            get {
                return ResourceManager.GetString("TerminalDockPanelBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No docked terminals.
        /// </summary>
        public static string TerminalDockPanelHeading {
            get {
                return ResourceManager.GetString("TerminalDockPanelHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press the backtick key (`) to hide this panel..
        /// </summary>
        public static string TerminalDockPanelHint {
            get {
                return ResourceManager.GetString("TerminalDockPanelHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource terminals:.
        /// </summary>
        public static string TerminalDockResourceTerminals {
            get {
                return ResourceManager.GetString("TerminalDockResourceTerminals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string TerminalDockMoreInformation {
            get {
                return ResourceManager.GetString("TerminalDockMoreInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Return to panel.
        /// </summary>
        public static string TerminalDockReturnToDock {
            get {
                return ResourceManager.GetString("TerminalDockReturnToDock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This terminal has ended..
        /// </summary>
        public static string TerminalWindowEnded {
            get {
                return ResourceManager.GetString("TerminalWindowEnded", resourceCulture);
            }
        }
    }
}
