import aspire.*;
import java.util.Map;

void main() throws Exception {
        var builder = DistributedApplication.CreateBuilder();
        var container = builder.addContainer("mycontainer", "nginx");
        container.withOtlpExporter(OtlpProtocol.HTTP_JSON);
        var dockerContainer = builder.addDockerfile("dockerapp", "./app");
        var dockerfileFactory = (AspireFunc1<DockerfileFactoryContext, String>) (factoryContext) -> {
            var _factoryResource = factoryContext.resource();
            return """
                FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
                WORKDIR /app
                ENTRYPOINT ["dotnet", "App.dll"]
                """;
        };
        var dockerFactoryContainer = builder.addDockerfileFactory("dockerfactoryapp", "./app", dockerfileFactory, "runtime");
        var configureDockerfileBuilder = (AspireAction1<DockerfileBuilderCallbackContext>) (dockerfileContext) -> {
            var _dockerfileResource = dockerfileContext.resource();
            var dockerfileServices = dockerfileContext.services();
            var dockerfileLoggerFactory = dockerfileServices.getLoggerFactory();
            var dockerfileLogger = dockerfileLoggerFactory.createLogger("ValidationAppHost.DockerfileBuilder");
            dockerfileLogger.logInformation("Configuring Dockerfile builder");
            var dockerfileBuilder = dockerfileContext.builder();
            dockerfileBuilder.arg("BASE_IMAGE", "mcr.microsoft.com/dotnet/runtime:8.0");
            dockerfileBuilder.addContainerFilesStages(_dockerfileResource, dockerfileLogger);
            var buildStage = dockerfileBuilder.from("mcr.microsoft.com/dotnet/sdk:8.0", "build");
            buildStage.arg("APP_DIR", "/src");
            buildStage.workDir("/src");
            buildStage.copy("./src", "/src", "1000:1000");
            buildStage.run("echo building dockerfile");
            buildStage.runWithMounts("echo mounted", new String[] { "/tmp:/mnt" });
            var runtimeStage = dockerfileBuilder.from("mcr.microsoft.com/dotnet/runtime:8.0", "runtime");
            runtimeStage.copyFrom("build", "/src", "/app", "1000:1000");
            runtimeStage.env("ASPIRE_ENV", "Development");
            runtimeStage.expose(8080.0);
            runtimeStage.cmd(new String[] { "dotnet", "App.dll" });
            runtimeStage.entrypoint(new String[] { "dotnet", "App.dll" });
            runtimeStage.user("1000");
            runtimeStage.addContainerFiles(_dockerfileResource, "/app", dockerfileLogger);
            runtimeStage.emptyLine();
            runtimeStage.comment("Generated by Java polyglot validation");
        };
        var dockerBuilderContainer = builder.addDockerfileBuilder("dockerbuilderapp", "./app", configureDockerfileBuilder, "runtime");
        dockerContainer.withDockerfileBuilder("./app", configureDockerfileBuilder, "runtime");
        dockerFactoryContainer.withDockerfileFactory("./app", dockerfileFactory, "runtime");
        var exe = builder.addExecutable("myexe", "echo", ".", new String[] { "hello" });
        var project = builder.addProject("myproject", "./src/MyProject", "https");
        project.withEndpointsInEnvironment(new String[] { "https" });
        builder.addHealthCheck("custom_check", () -> {
            var result = new HealthCheckResult();
            result.setStatus(HealthStatus.HEALTHY);
            result.setDescription("custom health check");
            result.setData(Map.of("custom", "value"));
            return result;
        });
        var csharpApp = builder.addCSharpApp("csharpapp", "./src/CSharpApp");
        var cache = builder.addRedis("cache");
        var tool = builder.addDotnetTool("mytool", "dotnet-ef");
        var configParam = builder.addParameterFromConfiguration("myconfig", "MyConfig:Key");
        var secretParam = builder.addParameterFromConfiguration("mysecret", "MyConfig:Secret", true);
        var customInputParam = builder.addParameter("custom-input");
        var customInputOptions = new ParameterCustomInputOptions();
        customInputOptions.setInputType(InputType.NUMBER);
        customInputOptions.setLabel("Worker Count");
        customInputOptions.setPlaceholder("Enter number (1-10)");
        customInputOptions.setOptions(Map.of("one", "One", "two", "Two"));
        customInputParam.withCustomInput(customInputOptions);
        container.withDockerfileBaseImage(new WithDockerfileBaseImageOptions().buildImage("mcr.microsoft.com/dotnet/sdk:8.0"));
        var containerFilesOptions = new ContainerFilesOptions();
        containerFilesOptions.setDefaultOwner(1000.0);
        containerFilesOptions.setDefaultGroup(1000.0);
        containerFilesOptions.setUmask(18.0);
        container.withContainerFiles("/usr/lib/aspire/container-files", ".", containerFilesOptions);
        var callbackContainerFilesOptions = new ContainerFilesOptions();
        callbackContainerFilesOptions.setDefaultOwner(1000.0);
        callbackContainerFilesOptions.setDefaultGroup(1000.0);
        callbackContainerFilesOptions.setUmask(18.0);
        container.withContainerFilesCallback("/usr/lib/aspire/container-files", (filesCtx, filesCancellationToken) -> {
            var filesServices = filesCtx.services();
            var filesLoggerFactory = filesServices.getLoggerFactory();
            var filesLogger = filesLoggerFactory.createLogger("ValidationAppHost.ContainerFilesCallback");
            filesLogger.logInformation("ContainerFilesCallback services");
            var appConfig = filesCtx.createFile("app.conf", new CreateFileOptions().contents("key=value").mode(420.0));
            var nestedConfig = filesCtx.createFile("nested.conf", new CreateFileOptions().contents("nested=true"));
            var confDir = filesCtx.createDirectory("conf.d", new ContainerFileSystemItem[] { nestedConfig }, new CreateDirectoryOptions().mode(493.0));
            var cert = filesCtx.createCertificateFile("server.pem", new CreateCertificateFileOptions().contents("-----BEGIN CERTIFICATE-----"));
            return new ContainerFileSystemItem[] { appConfig, confDir, cert };
        }, callbackContainerFilesOptions);
        container.withImageRegistry("docker.io");
        dockerContainer.withHttpEndpoint(new WithHttpEndpointOptions().name("http").targetPort(80.0));
        dockerContainer.withHttpEndpointCallback((updateContext) -> { updateContext.setPort(8080.0); updateContext.setIsProxied(false); }, new WithHttpEndpointCallbackOptions().name("http").createIfNotExists(false));
        var endpoint = dockerContainer.getEndpoint("http");
        var expr = ReferenceExpression.refExpr("Host=%s", endpoint);
        var endpointHost = endpoint.property(EndpointProperty.HOST);
        var endpointPort = endpoint.property(EndpointProperty.PORT);
        var endpointUrl = ReferenceExpression.refExpr("http://%s:%s", endpointHost, endpointPort);
        var builtConnectionString = builder.addConnectionString("customcs", expr);
        var envConnectionString = builder.addConnectionString("envcs");
        var expressionConnectionString = builder.addConnectionString("exprcs", expr);
        cache.withConnectionProperty("Host", expr);
        cache.withConnectionProperty("Mode", "Development");
        container.withReference(endpoint);
        container.withReference("https://example.com/", new WithReferenceOptions().name("external-uri"));
        var externalService = builder.addExternalService("external-service", "https://example.com");
        var vnet = builder.addAzureVirtualNetwork("vnet", "10.0.0.0/16");
        var subnet = vnet.addSubnet("web", "10.0.1.0/24", null);
        subnet.allowInbound(new AllowInboundOptions().port("443").from(AzureServiceTags.AzureLoadBalancer));
        subnet.denyInbound(new DenyInboundOptions().from(AzureServiceTags.Internet));
        var aks = builder.addAzureKubernetesEnvironment("aks");
        aks.addNodePool("system", new AddNodePoolOptions().vmSize(AksNodeVmSizes.StandardDSv5.StandardD2sV5));
        var pipeline = builder.pipeline();
        pipeline.addStep("custom-builder-step", (stepContext) -> { var builderSummary = stepContext.summary(); builderSummary.add("BuilderPipelineStep", "Validated"); }, new AddStepOptions().dependsOn(new String[] { WellKnownPipelineSteps.Build }).requiredBy(new String[] { WellKnownPipelineSteps.Publish }));
        pipeline.configure((configContext) -> { var builderPipeline = configContext.pipeline(); var _allSteps = builderPipeline.steps(); var _builderTaggedSteps = configContext.getSteps("custom-build"); });
        container.withEnvironment("MY_ENDPOINT", endpoint);
        container.withEnvironment("MY_ENDPOINT_URL", endpointUrl);
        container.withEnvironment("MY_PARAM", configParam);
        container.withEnvironment("MY_BUILT_CONN", builtConnectionString);
        container.withEnvironment("MY_CONN", envConnectionString);
        container.withEnvironment("MY_EXPR_CONN", expressionConnectionString);
        container.withEnvironment("MY_EXTERNAL_SERVICE", externalService);
        container.withEnvironmentCallback((environmentContext) -> { var environment = environmentContext.environment(); var environmentLog = environmentContext.log(); var _environmentResource = environmentContext.resource(); var environmentExecutionContext = environmentContext.executionContext(); var _environmentIsRunMode = environmentExecutionContext.isRunMode(); environmentLog.warning("Environment callback logger"); environment.set("MY_CALLBACK_ENDPOINT", endpoint); });
        container.withArgsCallback((argsContext) -> { var argsEditor = argsContext.args(); var argsLog = argsContext.log(); var _argsResource = argsContext.resource(); var argsExecutionContext = argsContext.executionContext(); var _argsIsRunMode = argsExecutionContext.isRunMode(); argsLog.error("Args callback logger"); argsEditor.add("--validation-callback"); argsEditor.add(expr); });
        container.withUrls((urlsContext) -> { var _urlsResource = urlsContext.resource(); var urlsLog = urlsContext.log(); var urlsExecutionContext = urlsContext.executionContext(); var _urlsIsRunMode = urlsExecutionContext.isRunMode(); var callbackEndpoint = urlsContext.getEndpoint("http"); var urlsEditor = urlsContext.urls(); urlsLog.debug("URLs callback logger"); urlsEditor.add(ReferenceExpression.refExpr("https://%s", callbackEndpoint), null); urlsEditor.addForEndpoint(callbackEndpoint, "/details", "Details"); });
        cache.withConnectionProperty("Endpoint", expr);
        cache.withConnectionProperty("Protocol", "https");
        container.excludeFromManifest();
        container.excludeFromMcp();
        container.waitForCompletion(exe);
        container.withDeveloperCertificateTrust(true);
        container.withCertificateTrustScope(CertificateTrustScope.SYSTEM);
        container.withHttpsDeveloperCertificate();
        container.withoutHttpsCertificate();
        container.withChildRelationship(exe);
        container.withIconName("Database", IconVariant.FILLED);
        container.withHttpProbe(ProbeType.LIVENESS, new WithHttpProbeOptions().path("/health"));
        container.withRemoteImageName("myregistry.azurecr.io/myapp");
        container.withRemoteImageTag("latest");
        container.withImagePushOptions((context) -> {
            var options = context.options();
            options.setRemoteImageName("myregistry.azurecr.io/myapp");
            options.setRemoteImageTag("latest");
        });
        container.withMcpServer(new WithMcpServerOptions().path("/mcp"));
        container.withRequiredCommand("docker");
        container.withRequiredCommandValidation("docker", (validationCtx) -> {
            var _validationResolvedPath = validationCtx.resolvedPath();
            var validationServices = validationCtx.services();
            var validationLoggerFactory = validationServices.getLoggerFactory();
            var validationLogger = validationLoggerFactory.createLogger("ValidationAppHost.RequiredCommandValidation");
            validationLogger.logInformation("RequiredCommandValidation services");
            return validationCtx.success();
        });
        tool.withToolIgnoreExistingFeeds();
        tool.withToolIgnoreFailedSources();
        tool.withToolPackage("dotnet-ef");
        tool.withToolPrerelease();
        tool.withToolSource("https://api.nuget.org/v3/index.json");
        tool.withToolVersion("8.0.0");
        tool.publishAsDockerFile((_container) -> {});
        container.withPipelineStepFactory("custom-build-step", (stepContext) -> { var pipelineContext = stepContext.pipelineContext(); var pipelineModel = pipelineContext.model(); var _pipelineResources = pipelineModel.getResources(); var _pipelineContainer = pipelineModel.findResourceByName("mycontainer"); var pipelineServices = pipelineContext.services(); var pipelineLoggerFactory = pipelineServices.getLoggerFactory(); var pipelineFactoryLogger = pipelineLoggerFactory.createLogger("ValidationAppHost.PipelineContext"); pipelineFactoryLogger.logInformation("Pipeline factory context logger"); var pipelineLogger = pipelineContext.logger(); pipelineLogger.logDebug("Pipeline context logger"); var pipelineSummary = pipelineContext.summary(); pipelineSummary.add("PipelineContext", "Validated"); pipelineSummary.addMarkdown("PipelineMarkdown", "**Validated**"); var executionContext = stepContext.executionContext(); var _isPublishMode = executionContext.isPublishMode(); var stepServices = stepContext.services(); var stepLogger = stepContext.logger(); stepLogger.logInformation("Pipeline step context logger"); var stepSummary = stepContext.summary(); stepSummary.add("PipelineStepContext", "Validated"); var reportingStep = stepContext.reportingStep(); reportingStep.logStep("information", "Reporting step log"); reportingStep.logStepMarkdown("information", "**Reporting step markdown log**"); var reportingTask = reportingStep.createTask("Task created"); reportingTask.updateTask("Task updated"); reportingTask.updateTaskMarkdown("**Task markdown updated**"); reportingTask.completeTask(new CompleteTaskOptions().completionMessage("Task complete")); var markdownTask = reportingStep.createMarkdownTask("**Markdown task created**"); markdownTask.completeTaskMarkdown("**Markdown task complete**", new CompleteTaskMarkdownOptions().completionState("completed-with-warning")); reportingStep.completeStep("Reporting step complete"); reportingStep.completeStepMarkdown("**Reporting step markdown complete**", new CompleteStepMarkdownOptions().completionState("completed-with-warning")); var stepModel = stepContext.model(); var _stepResources = stepModel.getResources(); var _stepContainer = stepModel.findResourceByName("mycontainer"); var stepLoggerFactory = stepServices.getLoggerFactory(); var stepFactoryLogger = stepLoggerFactory.createLogger("ValidationAppHost.PipelineStepContext"); stepFactoryLogger.logDebug("Pipeline step factory logger"); var cancellationToken = stepContext.cancellationToken(); var cacheUriExpression = cache.uriExpression(); var _cacheUri = cacheUriExpression.getValue(cancellationToken); }, new WithPipelineStepFactoryOptions().dependsOn(new String[] { WellKnownPipelineSteps.Build }).requiredBy(new String[] { WellKnownPipelineSteps.Deploy }).tags(new String[] { WellKnownPipelineTags.BuildCompute }).description("Custom pipeline step"));
        container.withPipelineConfiguration((configContext) -> { var configLog = configContext.log(); configLog.info("Pipeline configuration logger"); var configPipeline = configContext.pipeline(); var allSteps = configPipeline.steps(); var taggedSteps = configPipeline.stepsByTag(WellKnownPipelineTags.BuildCompute); var _stepName = allSteps[0].name(); var _description = allSteps[0].description(); var _dependsOnSteps = allSteps[0].dependsOnSteps(); var _requiredBySteps = taggedSteps[0].requiredBySteps(); var _tags = taggedSteps[0].tags(); allSteps[0].addTag("validated"); allSteps[0].dependsOn("restore"); taggedSteps[0].requiredBy(WellKnownPipelineSteps.Publish); allSteps[0].dependsOn(WellKnownPipelineSteps.Build); });
        container.withPipelineConfiguration((configContext) -> { var configPipeline = configContext.pipeline(); var _resourceSteps = configPipeline.steps(); var _taggedSteps = configPipeline.stepsByTag(WellKnownPipelineTags.BuildCompute); });
        var _appHostDirectory = builder.appHostDirectory();
        var hostEnvironment = builder.environment();
        var _isDevelopment = hostEnvironment.isDevelopment();
        var _isProduction = hostEnvironment.isProduction();
        var _isStaging = hostEnvironment.isStaging();
        var _isSpecificEnvironment = hostEnvironment.isEnvironment("Development");
        var builderConfiguration = builder.getConfiguration();
        var _configValue = builderConfiguration.getConfigValue("MyConfig:Key");
        var _connectionString = builderConfiguration.getConnectionString("customcs");
        var _configSection = builderConfiguration.getSection("MyConfig");
        var _configChildren = builderConfiguration.getChildren();
        var _configExists = builderConfiguration.exists("MyConfig:Key");
        var builderExecutionContext = builder.executionContext();
        var executionContextServiceProvider = builderExecutionContext.serviceProvider();
        var _distributedApplicationModelFromExecutionContext = executionContextServiceProvider.getDistributedApplicationModel();
        var resourceCommandService = executionContextServiceProvider.getResourceCommandService();
        builder.addEventingSubscriber((registrationContext) -> {
            var subscriberExecutionContext = registrationContext.executionContext();
            var _subscriberIsRunMode = subscriberExecutionContext.isRunMode();
            var _subscriberCancellationToken = registrationContext.cancellationToken();
            registrationContext.onBeforeStart((beforeStartEvent) -> {
                var subscriberServices = beforeStartEvent.services();
                var aspireStore = subscriberServices.getAspireStore();
                var _contentBackedFilename = aspireStore.getFileNameWithContent("validation-apphost.java", "AppHost.java");
            });
            registrationContext.onBeforePublish((beforePublishEvent) -> {
                var beforePublishServices = beforePublishEvent.services();
                var beforePublishModel = beforePublishEvent.model();
                var _beforePublishEventing = beforePublishServices.getEventing();
                var _beforePublishResources = beforePublishModel.getResources();
            });
            registrationContext.onAfterPublish((afterPublishEvent) -> {
                var afterPublishServices = afterPublishEvent.services();
                var afterPublishModel = afterPublishEvent.model();
                var _afterPublishEventing = afterPublishServices.getEventing();
                var _afterPublishResources = afterPublishModel.getResources();
            });
            registrationContext.onAfterResourcesCreated((afterResourcesCreatedEvent) -> {
                var afterResourcesCreatedServices = afterResourcesCreatedEvent.services();
                var afterResourcesCreatedModel = afterResourcesCreatedEvent.model();
                var _afterResourcesCreatedEventing = afterResourcesCreatedServices.getEventing();
                var _afterResourcesCreatedResources = afterResourcesCreatedModel.getResources();
            });
        });
        builder.tryAddEventingSubscriber((_registrationContext) -> { });
        container.withArgs(new String[] { "--validation" });
        var executionConfigurationBuilder = container.createExecutionConfiguration();
        executionConfigurationBuilder.withArgumentsConfig();
        executionConfigurationBuilder.withEnvironmentVariablesConfig();
        executionConfigurationBuilder.withCertificateTrustConfig((requestedTrustScope) -> {
            var _requestedTrustScope = requestedTrustScope;
            var trustContext = new CertificateTrustExecutionConfigurationContext();
            trustContext.setCertificateBundlePath(ReferenceExpression.refExpr("/etc/ssl/certs/custom-bundle.pem"));
            trustContext.setCertificateDirectoriesPath(ReferenceExpression.refExpr("/etc/ssl/certs/custom"));
            trustContext.setRootCertificatesPath("/etc/ssl/certs");
            trustContext.setIsContainer(true);
            return trustContext;
        });
        executionConfigurationBuilder.withHttpsCertificateConfig((certificateInfo) -> {
            var _certificateSubject = certificateInfo.getSubject();
            var _certificateThumbprint = certificateInfo.getThumbprint();
            var certificateContext = new HttpsCertificateExecutionConfigurationContext();
            certificateContext.setCertificatePath(ReferenceExpression.refExpr("/certificates/tls.crt"));
            certificateContext.setKeyPath(ReferenceExpression.refExpr("/certificates/tls.key"));
            certificateContext.setPfxPath(ReferenceExpression.refExpr("/certificates/tls.pfx"));
            return certificateContext;
        });
        var executionConfiguration = executionConfigurationBuilder.build(builderExecutionContext);
        var _certificateTrustData = executionConfiguration.getCertificateTrustData();
        var _httpsCertificateData = executionConfiguration.getHttpsCertificateData();
        var beforeStartSubscription = builder.subscribeBeforeStart((beforeStartEvent) -> { var beforeStartServices = beforeStartEvent.services(); var beforeStartModel = beforeStartEvent.model(); var _beforeStartResources = beforeStartModel.getResources(); var _beforeStartContainer = beforeStartModel.findResourceByName("mycontainer"); var _beforeStartEventing = beforeStartServices.getEventing(); var beforeStartLoggerFactory = beforeStartServices.getLoggerFactory(); var beforeStartLogger = beforeStartLoggerFactory.createLogger("ValidationAppHost.BeforeStart"); beforeStartLogger.logInformation("BeforeStart information"); beforeStartLogger.logWarning("BeforeStart warning"); beforeStartLogger.logError("BeforeStart error"); beforeStartLogger.logDebug("BeforeStart debug"); beforeStartLogger.log("critical", "BeforeStart critical"); var beforeStartResourceLoggerService = beforeStartServices.getResourceLoggerService(); beforeStartResourceLoggerService.completeLog(container); beforeStartResourceLoggerService.completeLogByName("mycontainer"); var beforeStartNotificationService = beforeStartServices.getResourceNotificationService(); beforeStartNotificationService.waitForResourceState("mycontainer", "Running"); var _matchedResourceState = beforeStartNotificationService.waitForResourceStates("mycontainer", new String[] { "Running", "FailedToStart" }); var _healthyResourceEvent = beforeStartNotificationService.waitForResourceHealthy("mycontainer"); beforeStartNotificationService.waitForDependencies(container); var _currentResourceState = beforeStartNotificationService.tryGetResourceState("mycontainer"); beforeStartNotificationService.publishResourceUpdate(container, new PublishResourceUpdateOptions().state("Validated").stateStyle("info")); var userSecretsManager = beforeStartServices.getUserSecretsManager(); var _userSecretsAvailable = userSecretsManager.isAvailable(); var _userSecretsFilePath = userSecretsManager.filePath(); var _secretSet = userSecretsManager.trySetSecret("Validation:Key", "value"); userSecretsManager.getOrSetSecret(container, "Validation:GeneratedKey", "generated-value"); var _generatedSecretValue = builderConfiguration.getConfigValue("Validation:GeneratedKey"); userSecretsManager.saveStateJson("{\"Validation\":\"Value\"}"); var _modelFromServices = beforeStartServices.getDistributedApplicationModel(); });
        var afterResourcesCreatedSubscription = builder.subscribeAfterResourcesCreated((afterResourcesCreatedEvent) -> { var afterResourcesCreatedServices = afterResourcesCreatedEvent.services(); var afterResourcesCreatedModel = afterResourcesCreatedEvent.model(); var _afterResources = afterResourcesCreatedModel.getResources(); var _afterResourcesContainer = afterResourcesCreatedModel.findResourceByName("mycontainer"); var afterResourcesCreatedLoggerFactory = afterResourcesCreatedServices.getLoggerFactory(); var afterResourcesCreatedLogger = afterResourcesCreatedLoggerFactory.createLogger("ValidationAppHost.AfterResourcesCreated"); afterResourcesCreatedLogger.logInformation("AfterResourcesCreated"); });
        var beforePublishSubscription = builder.subscribeBeforePublish((beforePublishEvent) -> { var beforePublishServices = beforePublishEvent.services(); var beforePublishModel = beforePublishEvent.model(); var _beforePublishResources = beforePublishModel.getResources(); var _beforePublishContainer = beforePublishModel.findResourceByName("mycontainer"); var beforePublishLoggerFactory = beforePublishServices.getLoggerFactory(); var beforePublishLogger = beforePublishLoggerFactory.createLogger("ValidationAppHost.BeforePublish"); beforePublishLogger.logInformation("BeforePublish"); });
        var afterPublishSubscription = builder.subscribeAfterPublish((afterPublishEvent) -> { var afterPublishServices = afterPublishEvent.services(); var afterPublishModel = afterPublishEvent.model(); var _afterPublishResources = afterPublishModel.getResources(); var _afterPublishContainer = afterPublishModel.findResourceByName("mycontainer"); var afterPublishLoggerFactory = afterPublishServices.getLoggerFactory(); var afterPublishLogger = afterPublishLoggerFactory.createLogger("ValidationAppHost.AfterPublish"); afterPublishLogger.logInformation("AfterPublish"); });
        var builderEventing = builder.eventing();
        builderEventing.unsubscribe(beforeStartSubscription);
        builderEventing.unsubscribe(afterResourcesCreatedSubscription);
        builderEventing.unsubscribe(beforePublishSubscription);
        builderEventing.unsubscribe(afterPublishSubscription);
        container.onBeforeResourceStarted((beforeResourceStartedEvent) -> { var _resource = beforeResourceStartedEvent.resource(); var services = beforeResourceStartedEvent.services(); var loggerFactory = services.getLoggerFactory(); var logger = loggerFactory.createLogger("ValidationAppHost.BeforeResourceStarted"); logger.logInformation("BeforeResourceStarted"); });
        container.onResourceStopped((resourceStoppedEvent) -> { var _resource = resourceStoppedEvent.resource(); var services = resourceStoppedEvent.services(); var loggerFactory = services.getLoggerFactory(); var logger = loggerFactory.createLogger("ValidationAppHost.ResourceStopped"); logger.logWarning("ResourceStopped"); });
        cache.onConnectionStringAvailable((connectionStringAvailableEvent) -> { var _resource = connectionStringAvailableEvent.resource(); var services = connectionStringAvailableEvent.services(); var notifications = services.getResourceNotificationService(); var _connectionState = notifications.tryGetResourceState("cache"); });
        container.onInitializeResource((initializeResourceEvent) -> { var _resource = initializeResourceEvent.resource(); var _initializeEventing = initializeResourceEvent.eventing(); var initializeLogger = initializeResourceEvent.logger(); var initializeNotifications = initializeResourceEvent.notifications(); var initializeServices = initializeResourceEvent.services(); initializeLogger.logDebug("InitializeResource"); initializeNotifications.waitForDependencies(container); var _initializeModel = initializeServices.getDistributedApplicationModel(); var _initializeEventingFromServices = initializeServices.getEventing(); });
        container.onResourceEndpointsAllocated((resourceEndpointsAllocatedEvent) -> { var _resource = resourceEndpointsAllocatedEvent.resource(); var services = resourceEndpointsAllocatedEvent.services(); var loggerFactory = services.getLoggerFactory(); var logger = loggerFactory.createLogger("ValidationAppHost.ResourceEndpointsAllocated"); logger.logInformation("ResourceEndpointsAllocated"); });
        container.onResourceReady((resourceReadyEvent) -> { var _resource = resourceReadyEvent.resource(); var services = resourceReadyEvent.services(); var loggerFactory = services.getLoggerFactory(); var logger = loggerFactory.createLogger("ValidationAppHost.ResourceReady"); logger.logInformation("ResourceReady"); });
        container.withEnvironment("MY_VAR", "value");
        container.withEndpoint();
        container.withEndpoint(new WithEndpointOptions().name("callback-endpoint"));
        container.withEndpointCallback("callback-endpoint", (updateContext) -> { updateContext.setPort(5001.0); updateContext.setTargetPort(5002.0); updateContext.setIsExternal(false); }, false);
        container.withHttpEndpoint();
        container.withHttpEndpoint(new WithHttpEndpointOptions().name("callback-http"));
        container.withHttpEndpointCallback((updateContext) -> { updateContext.setPort(8081.0); updateContext.setTargetPort(8082.0); updateContext.setIsProxied(false); }, new WithHttpEndpointCallbackOptions().name("callback-http").createIfNotExists(false));
        container.withHttpEndpointCallback((updateContext) -> { updateContext.setPort(8083.0); updateContext.setTargetPort(8084.0); updateContext.setIsProxied(false); }, new WithHttpEndpointCallbackOptions().name("created-http"));
        container.withHttpsEndpoint();
        container.withHttpsEndpoint(new WithHttpsEndpointOptions().name("callback-https"));
        container.withHttpsEndpointCallback((updateContext) -> { updateContext.setPort(8444.0); updateContext.setTargetPort(8443.0); updateContext.setIsProxied(false); }, new WithHttpsEndpointCallbackOptions().name("callback-https").createIfNotExists(false));
        container.withHttpsEndpointCallback((updateContext) -> { updateContext.setPort(8445.0); updateContext.setTargetPort(8446.0); updateContext.setIsProxied(false); }, new WithHttpsEndpointCallbackOptions().name("created-https"));
        container.withExternalHttpEndpoints();
        container.asHttp2Service();
        container.withArgs(new String[] { "--verbose" });
        container.withParentRelationship(exe);
        container.withExplicitStart();
        container.withUrl("http://localhost:8080", null);
        container.withUrl(ReferenceExpression.refExpr("http://%s", endpoint), null);
        container.withHttpHealthCheck();
        container.withHttpHealthCheck();
        var commandOptions = new CommandOptions();
        commandOptions.setUpdateState((ctx) -> {
            var snapshot = ctx.resourceSnapshot();
            var updateStateServices = ctx.services();
            var updateStateLoggerFactory = updateStateServices.getLoggerFactory();
            var updateStateLogger = updateStateLoggerFactory.createLogger("ValidationAppHost.UpdateCommandState");
            updateStateLogger.logInformation("UpdateCommandState services");
            return snapshot.getHealthStatus() == HealthStatus.HEALTHY ? ResourceCommandState.ENABLED : ResourceCommandState.DISABLED;
        });
        container.withCommand("noop", "Noop", (_ctx) -> {
            var result = new ExecuteCommandResult();
            result.setSuccess(true);
            return result;
        }, commandOptions);
        var echoCommandOptions = new CommandOptions();
        var messageArgument = new InteractionInput();
        messageArgument.setName("message");
        messageArgument.setInputType(InputType.TEXT);
        messageArgument.setRequired(true);
        echoCommandOptions.setArguments(new InteractionInput[] { messageArgument });
        echoCommandOptions.setValidateArguments((ctx) -> {
            var validationServices = ctx.services();
            var validationLoggerFactory = validationServices.getLoggerFactory();
            var validationLogger = validationLoggerFactory.createLogger("ValidationAppHost.ValidateCommandArguments");
            validationLogger.logInformation("Validate command arguments services");
        });
        container.withCommand("echo", "Echo", (ctx) -> {
            var echoServices = ctx.services();
            var echoLoggerFactory = echoServices.getLoggerFactory();
            var echoLogger = echoLoggerFactory.createLogger("ValidationAppHost.EchoCommand");
            echoLogger.logInformation("Echo command services");
            var result = new ExecuteCommandResult();
            result.setSuccess("hello".equals(ctx.arguments().value("message")));
            return result;
        }, echoCommandOptions);
        container.withCommand("restart", "Restart", (ctx) -> {
            var cancellationToken = ctx.cancellationToken();
            return resourceCommandService.executeCommandAsync(
                container,
                "echo",
                new ExecuteCommandAsyncOptions()
                    .arguments(Map.of("message", "hello"))
                    .cancellationToken(cancellationToken));
        });
        // Test bench for the polyglot IInteractionService API: prompts for a region, then dynamically
        // loads the available zones for that region into a second choice input. Reached via the command's
        // service provider (services().getInteractionService()), which only prompts when the
        // interaction service is available (the interactive dashboard path).
        container.withCommand("pick-zone", "Pick Zone", (ctx) -> {
            var interactionService = ctx.services().getInteractionService();
            if (!interactionService.isAvailable()) {
                var unavailable = new ExecuteCommandResult();
                unavailable.setSuccess(true);
                unavailable.setMessage("Interaction service is not available.");
                return unavailable;
            }

            var regionInput = interactionService.createChoiceInput(
                "region",
                new CreateChoiceInputOptions().choices(new InteractionChoiceOption[] { opt("us", "United States"), opt("eu", "Europe") }));

            var zoneInput = interactionService.createChoiceInput("zone").withDynamicLoading((loadContext) -> {
                var region = loadContext.inputs().value("region");
                InteractionChoiceOption[] zones = "eu".equals(region)
                    ? new InteractionChoiceOption[] { opt("eu-west", "EU West"), opt("eu-north", "EU North") }
                    : new InteractionChoiceOption[] { opt("us-east", "US East"), opt("us-west", "US West") };
                loadContext.input().setChoiceOptions(zones);
            });

            var result = interactionService.promptInputs(
                "Pick a zone",
                "Choose a region, then pick a zone from the dynamically loaded options.",
                new InteractionInputBuilder[] { regionInput, zoneInput });

            var canceled = result.canceled();
            var commandResult = new ExecuteCommandResult();
            commandResult.setSuccess(!canceled);
            commandResult.setCanceled(canceled);
            return commandResult;
        });
        // Exhaustive coverage of the remaining IInteractionService surface so every newly added member is
        // exercised by the polyglot typecheck: all prompt overloads, every input factory and builder method,
        // the dynamic-loading context accessors/setters, and the option/result DTO fields.
        container.withCommand("interaction-showcase", "Interaction Showcase", (ctx) -> {
            var interactionService = ctx.services().getInteractionService();
            if (!interactionService.isAvailable()) {
                var unavailable = new ExecuteCommandResult();
                unavailable.setSuccess(true);
                unavailable.setMessage("Interaction service is not available.");
                return unavailable;
            }

            var confirmBox = new InteractionMessageBoxOptions();
            confirmBox.setPrimaryButtonText("Yes");
            confirmBox.setSecondaryButtonText("No");
            confirmBox.setShowSecondaryButton(true);
            confirmBox.setShowDismiss(true);
            confirmBox.setEnableMessageMarkdown(true);
            confirmBox.setIntent(MessageIntent.CONFIRMATION);
            var confirmation = interactionService.promptConfirmation("Confirm", "Proceed?",
                new PromptConfirmationOptions().options(confirmBox));

            var infoBox = new InteractionMessageBoxOptions();
            infoBox.setPrimaryButtonText("OK");
            infoBox.setIntent(MessageIntent.INFORMATION);
            var messageBox = interactionService.promptMessageBox("Notice", "Read this.",
                new PromptMessageBoxOptions().options(infoBox));

            var notificationOptions = new InteractionNotificationOptions();
            notificationOptions.setIntent(MessageIntent.WARNING);
            notificationOptions.setLinkText("Learn more");
            notificationOptions.setLinkUrl("https://aspire.dev");
            notificationOptions.setShowDismiss(true);
            var notification = interactionService.promptNotification("Heads up", "Something happened.",
                new PromptNotificationOptions().options(notificationOptions));

            var textOptions = new CreateInteractionInputOptions();
            textOptions.setLabel("Name");
            textOptions.setDescription("Your **name**");
            textOptions.setEnableDescriptionMarkdown(true);
            textOptions.setRequired(true);
            textOptions.setPlaceholder("Jane Doe");
            textOptions.setValue("Jane");
            textOptions.setMaxLength(64.0);
            textOptions.setDisabled(false);
            var textInput = interactionService.createTextInput("name", textOptions);

            var secretOptions = new CreateInteractionInputOptions();
            secretOptions.setRequired(true);
            var secretInput = interactionService.createSecretInput("password", secretOptions);

            var booleanOptions = new CreateInteractionInputOptions();
            booleanOptions.setValue("true");
            var booleanInput = interactionService.createBooleanInput("enabled", booleanOptions);

            var numberOptions = new CreateInteractionInputOptions();
            numberOptions.setValue("1");
            var numberInput = interactionService.createNumberInput("count", numberOptions);

            var choiceExtras = new CreateInteractionInputOptions();
            choiceExtras.setAllowCustomChoice(true);
            var choiceInput = interactionService.createChoiceInput("color",
                new CreateChoiceInputOptions().choices(new InteractionChoiceOption[] { opt("r", "Red"), opt("g", "Green") }).options(choiceExtras));

            var presetInput = interactionService.createTextInput("greeting").withValue("hello");
            var sizeInput = interactionService.createChoiceInput("size")
                .withChoiceOptions(new InteractionChoiceOption[] { opt("s", "Small"), opt("l", "Large") });

            var dynamicLoadingOptions = new DynamicLoadingOptions();
            dynamicLoadingOptions.setAlwaysLoadOnStart(true);
            dynamicLoadingOptions.setDependsOnInputs(new String[] { "color" });
            var dependentInput = interactionService.createChoiceInput("shade").withDynamicLoading((loadContext) -> {
                var input = loadContext.input();
                var inputName = input.getName();
                var color = loadContext.inputs().value("color");
                InteractionChoiceOption[] shades = "r".equals(color)
                    ? new InteractionChoiceOption[] { opt("crimson", "Crimson"), opt("scarlet", "Scarlet") }
                    : new InteractionChoiceOption[] { opt("lime", "Lime"), opt("forest", "Forest") };
                input.setChoiceOptions(shades);
                input.setValue(inputName);
            }, dynamicLoadingOptions);

            var singleDialogOptions = new InteractionInputsDialogOptions();
            singleDialogOptions.setPrimaryButtonText("Save");
            singleDialogOptions.setValidationCallback((validationContext) -> {
                if (validationContext.inputs().value("solo").isEmpty()) {
                    validationContext.addValidationError("solo", "A value is required.");
                }
            });
            var single = interactionService.promptInput("Single input", "Enter a value.",
                interactionService.createTextInput("solo"),
                new PromptInputOptions().options(singleDialogOptions));

            var multiDialogOptions = new InteractionInputsDialogOptions();
            multiDialogOptions.setPrimaryButtonText("Submit");
            multiDialogOptions.setEnableMessageMarkdown(true);
            multiDialogOptions.setValidationCallback((validationContext) -> {
                if ("bad".equals(validationContext.inputs().value("name"))) {
                    validationContext.addValidationError("name", "Name cannot be 'bad'.");
                }
            });
            var multi = interactionService.promptInputs("Multiple inputs", "Fill out the form.",
                new InteractionInputBuilder[] { textInput, secretInput, booleanInput, numberInput, choiceInput, presetInput, sizeInput, dependentInput },
                new PromptInputsOptions().options(multiDialogOptions));

            String selectedColor = multi.inputs().value("color");
            String soloValue = single.getInput() != null ? single.getInput().getValue() : "";

            var multiCanceled = multi.canceled();
            var success = !confirmation.getCanceled()
                && Boolean.TRUE.equals(confirmation.getValue())
                && !messageBox.getCanceled()
                && !notification.getCanceled()
                && !single.getCanceled()
                && !multiCanceled;

            var commandResult = new ExecuteCommandResult();
            commandResult.setSuccess(success);
            commandResult.setCanceled(multiCanceled);
            commandResult.setMessage("color=" + (selectedColor == null ? "" : selectedColor)
                + " solo=" + (soloValue == null ? "" : soloValue));
            return commandResult;
        });
        container.withHealthCheck("custom_check");
        container.withHttpsCertificateConfiguration((certCtx) -> {
            var _certResource = certCtx.resource();
            var _certIsRunMode = certCtx.executionContext().isRunMode();
            var certificatePath = certCtx.certificatePath();
            var keyPath = certCtx.keyPath();
            var certArgs = certCtx.arguments();
            certArgs.add("--certificate");
            certArgs.add(certificatePath);
            certArgs.add("--key");
            certArgs.add(keyPath);
            var certEnv = certCtx.environment();
            certEnv.set("Kestrel__Certificates__Path", certificatePath);
            certEnv.set("Kestrel__Certificates__KeyPath", keyPath);
        });
        container.subscribeHttpsEndpointsUpdate((httpsCtx) -> {
            var _httpsResource = httpsCtx.resource();
            var _httpsModel = httpsCtx.model();
            var httpsServices = httpsCtx.services();
            var httpsLoggerFactory = httpsServices.getLoggerFactory();
            var httpsLogger = httpsLoggerFactory.createLogger("ValidationAppHost.HttpsEndpointsUpdate");
            httpsLogger.logInformation("HttpsEndpointsUpdate services");
        });
        container.withContainerBuildOptions((buildCtx) -> {
            buildCtx.setDestination(ContainerImageDestination.REGISTRY);
            buildCtx.setImageFormat(ContainerImageFormat.OCI);
            buildCtx.setTargetPlatform(ContainerTargetPlatform.LINUX_AMD64);
            buildCtx.setOutputPath("./artifacts/container-image");
            buildCtx.setLocalImageName("validation-image");
            buildCtx.setLocalImageTag("latest");
            var _buildResource = buildCtx.resource();
            var _buildExecutionContext = buildCtx.executionContext();
            var buildServices = buildCtx.services();
            var buildLoggerFactory = buildServices.getLoggerFactory();
            var buildLogger = buildLoggerFactory.createLogger("ValidationAppHost.ContainerBuildOptions");
            buildLogger.logInformation("ContainerBuildOptions services");
        });
        container.withHttpCommand("/health", "Health Check");
        var httpCmdOptions = new HttpCommandExportOptions();
        httpCmdOptions.setMethodName("POST");
        httpCmdOptions.setConfirmationMessage("Are you sure?");
        container.withHttpCommand("/api/reset", "Reset", httpCmdOptions);
        var app = builder.build();
        app.run();
    }

    InteractionChoiceOption opt(String value, String label) {
        var option = new InteractionChoiceOption();
        option.setValue(value);
        option.setLabel(label);
        return option;
    }
