import aspire.*;

void main() throws Exception {
        var builder = DistributedApplication.CreateBuilder();
        builder.addAzureProvisioning();
        var location = builder.addParameter("location");
        var resourceGroup = builder.addParameter("resource-group");
        var existingName = builder.addParameter("existing-name");
        var existingResourceGroup = builder.addParameter("existing-resource-group");
        var connectionString = builder.addConnectionString("azure-validation", "AZURE_VALIDATION_CONNECTION_STRING");
        var azureEnvironment = builder.addAzureEnvironment();
        azureEnvironment.withLocation(location).withResourceGroup(resourceGroup);
        var container = builder.addContainer("api", "mcr.microsoft.com/dotnet/samples:aspnetapp");
        container.withHttpEndpoint(new WithHttpEndpointOptions().name("http").targetPort(8080.0));
        var executable = builder.addExecutable("worker", "dotnet", ".", new String[] { "--info" });
        executable.withHttpEndpoint(new WithHttpEndpointOptions().name("http").targetPort(8081.0));
        var endpoint = container.getEndpoint("http");
        var fileBicep = builder.addBicepTemplate("file-bicep", "./validation.bicep");
        fileBicep.publishAsConnectionString();
        fileBicep.clearDefaultRoleAssignments();
        fileBicep.getBicepIdentifier();
        fileBicep.isExisting();
        fileBicep.runAsExisting(AspireUnion.of("file-bicep-existing"), AspireUnion.of("rg-bicep"));
        fileBicep.runAsExisting(AspireUnion.of(existingName), AspireUnion.of(existingResourceGroup));
        fileBicep.publishAsExisting(AspireUnion.of("file-bicep-existing"), AspireUnion.of("rg-bicep"));
        fileBicep.publishAsExisting(AspireUnion.of(existingName), AspireUnion.of(existingResourceGroup));
        fileBicep.asExisting(AspireUnion.of(existingName), AspireUnion.of(existingResourceGroup));
        var inlineBicep = builder.addBicepTemplateString("inline-bicep", """
        output inlineUrl string = "https://inline.example.com"
        """);
        inlineBicep.publishAsConnectionString();
        inlineBicep.clearDefaultRoleAssignments();
        inlineBicep.getBicepIdentifier();
        inlineBicep.isExisting();
        var infrastructure = builder.addAzureInfrastructure("infra", (infrastructureContext) -> { });
        var infrastructureOutput = infrastructure.getOutput("serviceUrl");
        infrastructureOutput.name();
        infrastructureOutput.value();
        infrastructureOutput.valueExpression();
        infrastructure.withParameter("empty");
        infrastructure.withParameterStringValue("plain", "value");
        infrastructure.withParameterStringValues("list", new String[] { "one", "two" });
        infrastructure.withParameterFromParameter("fromParam", existingName);
        infrastructure.withParameterFromConnectionString("fromConnection", connectionString);
        infrastructure.withParameterFromOutput("fromOutput", infrastructureOutput);
        infrastructure.withParameterFromReferenceExpression("fromExpression", ReferenceExpression.refExpr("https://%s", endpoint));
        infrastructure.withParameterFromEndpoint("fromEndpoint", endpoint);
        infrastructure.publishAsConnectionString();
        infrastructure.clearDefaultRoleAssignments();
        infrastructure.getBicepIdentifier();
        infrastructure.isExisting();
        infrastructure.runAsExisting(AspireUnion.of("infra-existing"), AspireUnion.of("rg-infra"));
        infrastructure.runAsExisting(AspireUnion.of(existingName), AspireUnion.of(existingResourceGroup));
        infrastructure.publishAsExisting(AspireUnion.of("infra-existing"), AspireUnion.of("rg-infra"));
        infrastructure.publishAsExisting(AspireUnion.of(existingName), AspireUnion.of(existingResourceGroup));
        infrastructure.asExisting(AspireUnion.of(existingName), AspireUnion.of(existingResourceGroup));
        var identity = builder.addAzureUserAssignedIdentity("identity");
        identity.configureInfrastructure((infrastructureContext) -> { });
        identity.withParameter("identityEmpty");
        identity.withParameterStringValue("identityPlain", "value");
        identity.withParameterStringValues("identityList", new String[] { "a", "b" });
        identity.withParameterFromParameter("identityFromParam", existingName);
        identity.withParameterFromConnectionString("identityFromConnection", connectionString);
        identity.withParameterFromOutput("identityFromOutput", infrastructureOutput);
        identity.withParameterFromReferenceExpression("identityFromExpression", ReferenceExpression.refExpr("%s", location));
        identity.withParameterFromEndpoint("identityFromEndpoint", endpoint);
        identity.publishAsConnectionString();
        identity.clearDefaultRoleAssignments();
        identity.getBicepIdentifier();
        identity.isExisting();
        identity.runAsExisting(AspireUnion.of("identity-existing"), AspireUnion.of("rg-identity"));
        identity.runAsExisting(AspireUnion.of(existingName), AspireUnion.of(existingResourceGroup));
        identity.publishAsExisting(AspireUnion.of("identity-existing"), AspireUnion.of("rg-identity"));
        identity.publishAsExisting(AspireUnion.of(existingName), AspireUnion.of(existingResourceGroup));
        identity.asExisting(AspireUnion.of(existingName), AspireUnion.of(existingResourceGroup));
        container.withEnvironment("INFRA_URL", infrastructureOutput);
        container.withEnvironment("SECRET_FROM_IDENTITY", identity);
        container.withAzureUserAssignedIdentity(identity);
        executable.withEnvironment("INFRA_URL", infrastructureOutput);
        executable.withEnvironment("SECRET_FROM_IDENTITY", identity);
        executable.withAzureUserAssignedIdentity(identity);
        builder.build().run();
    }
