import aspire.*;

void main() throws Exception {
        var builder = DistributedApplication.CreateBuilder();
        builder.addAzureProvisioning();
        var location = builder.addParameter("location");
        var resourceGroup = builder.addParameter("resource-group");
        var existingName = builder.addParameter("existing-name");
        var existingResourceGroup = builder.addParameter("existing-resource-group");
        var connectionString = builder.addConnectionString("azure-validation", "AZURE_VALIDATION_CONNECTION_STRING");
        var azureEnvironment = builder.addAzureEnvironment();
        azureEnvironment.withLocation(location).withResourceGroup(resourceGroup);
        var container = builder.addContainer("api", "mcr.microsoft.com/dotnet/samples:aspnetapp");
        container.withHttpEndpoint(new WithHttpEndpointOptions().name("http").targetPort(8080.0));
        var executable = builder.addExecutable("worker", "dotnet", ".", new String[] { "--info" });
        executable.withHttpEndpoint(new WithHttpEndpointOptions().name("http").targetPort(8081.0));
        var endpoint = container.getEndpoint("http");
        var fileBicep = builder.addBicepTemplate("file-bicep", "./validation.bicep");
        fileBicep.publishAsConnectionString();
        fileBicep.clearDefaultRoleAssignments();
        fileBicep.getBicepIdentifier();
        fileBicep.isExisting();
        fileBicep.runAsExisting("file-bicep-existing", "rg-bicep");
        fileBicep.runAsExisting(existingName, existingResourceGroup);
        fileBicep.publishAsExisting("file-bicep-existing", "rg-bicep");
        fileBicep.publishAsExisting(existingName, existingResourceGroup);
        fileBicep.asExisting(existingName, existingResourceGroup);
        var inlineBicep = builder.addBicepTemplateString("inline-bicep", """
        output inlineUrl string = "https://inline.example.com"
        """);
        inlineBicep.publishAsConnectionString();
        inlineBicep.clearDefaultRoleAssignments();
        inlineBicep.getBicepIdentifier();
        inlineBicep.isExisting();
        var infrastructure = builder.addAzureInfrastructure("infra", (infrastructureContext) -> { });
        var infrastructureOutput = infrastructure.getOutput("serviceUrl");
        infrastructureOutput.name();
        infrastructureOutput.value();
        infrastructureOutput.valueExpression();
        infrastructure.withParameter("empty");
        infrastructure.withParameter("plain", "value");
        infrastructure.withParameter("list", new String[] { "one", "two" });
        infrastructure.withParameter("fromParam", existingName);
        infrastructure.withParameter("fromConnection", connectionString);
        infrastructure.withParameter("fromOutput", infrastructureOutput);
        infrastructure.withParameter("fromExpression", ReferenceExpression.refExpr("https://%s", endpoint));
        infrastructure.withParameter("fromEndpoint", endpoint);
        infrastructure.publishAsConnectionString();
        infrastructure.clearDefaultRoleAssignments();
        infrastructure.getBicepIdentifier();
        infrastructure.isExisting();
        infrastructure.runAsExisting("infra-existing", "rg-infra");
        infrastructure.runAsExisting(existingName, existingResourceGroup);
        infrastructure.publishAsExisting("infra-existing", "rg-infra");
        infrastructure.publishAsExisting(existingName, existingResourceGroup);
        infrastructure.asExisting(existingName, existingResourceGroup);
        var identity = builder.addAzureUserAssignedIdentity("identity");
        identity.configureInfrastructure((infrastructureContext) -> { });
        identity.withParameter("identityEmpty");
        identity.withParameter("identityPlain", "value");
        identity.withParameter("identityList", new String[] { "a", "b" });
        identity.withParameter("identityFromParam", existingName);
        identity.withParameter("identityFromConnection", connectionString);
        identity.withParameter("identityFromOutput", infrastructureOutput);
        identity.withParameter("identityFromExpression", ReferenceExpression.refExpr("%s", location));
        identity.withParameter("identityFromEndpoint", endpoint);
        identity.publishAsConnectionString();
        identity.clearDefaultRoleAssignments();
        identity.getBicepIdentifier();
        identity.isExisting();
        identity.runAsExisting("identity-existing", "rg-identity");
        identity.runAsExisting(existingName, existingResourceGroup);
        identity.publishAsExisting("identity-existing", "rg-identity");
        identity.publishAsExisting(existingName, existingResourceGroup);
        identity.asExisting(existingName, existingResourceGroup);
        container.withEnvironment("INFRA_URL", infrastructureOutput);
        container.withEnvironment("SECRET_FROM_IDENTITY", identity);
        container.withAzureUserAssignedIdentity(identity);
        executable.withEnvironment("INFRA_URL", infrastructureOutput);
        executable.withEnvironment("SECRET_FROM_IDENTITY", identity);
        executable.withAzureUserAssignedIdentity(identity);
        builder.build().run();
    }
