# Aspire Python validation AppHost
# Mirrors the top-level TypeScript playground surface with Python-style members.

from aspire_app import AzureResourceInfrastructure, ReferenceExpression, create_builder


def configure_infrastructure(_infrastructure: AzureResourceInfrastructure):
    pass


with create_builder() as builder:
    builder.add_azure_provisioning()
    location = builder.add_parameter("parameter")
    resource_group = builder.add_parameter("parameter")
    existing_name = builder.add_parameter("parameter")
    existing_resource_group = builder.add_parameter("parameter")
    connection_string = builder.add_connection_string(
        "connection-string", env_var_name_or_expression="AZURE_VALIDATION_CONNECTION_STRING"
    )
    azure_environment = builder.add_azure_env(location=location, resource_group=resource_group)
    azure_environment.with_location(location)
    container = builder.add_container("resource", "image")
    executable = builder.add_executable("resource", "echo", ".", [])
    endpoint = container.get_endpoint("default")
    reference_expression = ReferenceExpression.format_string("{0}", endpoint)
    file_bicep = builder.add_bicep_template("resource", "main.bicep")
    file_bicep.publish_as_connection_string()
    file_bicep.clear_default_role_assignments()
    file_bicep.get_bicep_identifier()
    file_bicep.is_existing()
    file_bicep.run_as_existing(existing_name)
    file_bicep.run_as_existing(existing_name, resource_group=existing_resource_group)
    file_bicep.publish_as_existing(existing_name)
    file_bicep.publish_as_existing(existing_name, resource_group=existing_resource_group)
    file_bicep.as_existing(existing_name)
    inline_bicep = builder.add_bicep_template_string("resource", "param location string")
    inline_bicep.publish_as_connection_string()
    inline_bicep.clear_default_role_assignments()
    inline_bicep.get_bicep_identifier()
    inline_bicep.is_existing()
    infrastructure = builder.add_azure_infrastructure("resource", configure_infrastructure)
    infrastructure_output = infrastructure.get_output("endpoint")
    infrastructure_output_expression = ReferenceExpression.format_string("{0}", infrastructure_output)
    _infrastructure_output_name = infrastructure_output.name
    _infrastructure_output_value = infrastructure_output.value
    _infrastructure_output_value_expression = infrastructure_output.value_expression
    infrastructure.with_parameter("default")
    infrastructure.with_parameter("string-value", value="value")
    infrastructure.with_parameter("string-values", value=["value-1", "value-2"])
    infrastructure.with_parameter("parameter", value=location)
    infrastructure.with_parameter("connection-string", value=connection_string)
    infrastructure.with_parameter("output", value=infrastructure_output)
    infrastructure.with_parameter("reference-expression", value=reference_expression)
    infrastructure.with_parameter("endpoint", value=endpoint)
    infrastructure.publish_as_connection_string()
    infrastructure.clear_default_role_assignments()
    infrastructure.get_bicep_identifier()
    infrastructure.is_existing()
    infrastructure.run_as_existing(existing_name)
    infrastructure.run_as_existing(existing_name, resource_group=existing_resource_group)
    infrastructure.publish_as_existing(existing_name)
    infrastructure.publish_as_existing(existing_name, resource_group=existing_resource_group)
    infrastructure.as_existing(existing_name)
    identity = builder.add_azure_user_assigned_identity("resource")
    identity_client_id = identity.get_output("clientId")
    identity_client_id_expression = ReferenceExpression.format_string("{0}", identity_client_id)
    identity.configure_infrastructure(configure_infrastructure)
    identity.with_parameter("default")
    identity.with_parameter("string-value", value="value")
    identity.with_parameter("string-values", value=["value-1", "value-2"])
    identity.with_parameter("parameter", value=location)
    identity.with_parameter("connection-string", value=connection_string)
    identity.with_parameter("output", value=infrastructure_output)
    identity.with_parameter("reference-expression", value=reference_expression)
    identity.with_parameter("endpoint", value=endpoint)
    identity.publish_as_connection_string()
    identity.clear_default_role_assignments()
    identity.get_bicep_identifier()
    identity.is_existing()
    identity.run_as_existing(existing_name)
    identity.run_as_existing(existing_name, resource_group=existing_resource_group)
    identity.publish_as_existing(existing_name)
    identity.publish_as_existing(existing_name, resource_group=existing_resource_group)
    identity.as_existing(existing_name)
    container.with_env("INFRA_URL", infrastructure_output_expression)
    container.with_env("IDENTITY_CLIENT_ID", identity_client_id_expression)
    container.with_azure_user_assigned_identity(identity)
    executable.with_env("INFRA_URL", infrastructure_output_expression)
    executable.with_env("IDENTITY_CLIENT_ID", identity_client_id_expression)
    executable.with_azure_user_assigned_identity(identity)
    builder.run()
