# Aspire Python validation AppHost
# Mirrors the top-level TypeScript playground surface with Python-style members.

from aspire_app import create_builder


with create_builder() as builder:
    builder.add_azure_provisioning("resource")
    location = builder.add_parameter("parameter")
    resource_group = builder.add_parameter("parameter")
    existing_name = builder.add_parameter("parameter")
    existing_resource_group = builder.add_parameter("parameter")
    connection_string = builder.add_connection_string("connection-string")
    azure_environment = builder.add_azure_environment("resource")
    azure_environment.with_location()
    container = builder.add_container("resource", "image")
    executable = builder.add_executable("resource", "echo", ".", [])
    endpoint = container.get_endpoint("default")
    file_bicep = builder.add_bicep_template("resource")
    file_bicep.publish_as_connection_string()
    file_bicep.clear_default_role_assignments()
    file_bicep.get_bicep_identifier()
    file_bicep.is_existing()
    file_bicep.run_as_existing()
    file_bicep.run_as_existing_from_parameters()
    file_bicep.publish_as_existing()
    file_bicep.publish_as_existing_from_parameters()
    file_bicep.as_existing()
    inline_bicep = builder.add_bicep_template_string("resource")
    inline_bicep.publish_as_connection_string()
    inline_bicep.clear_default_role_assignments()
    inline_bicep.get_bicep_identifier()
    inline_bicep.is_existing()
    infrastructure = builder.add_azure_infrastructure("resource")
    infrastructure_output = infrastructure.get_output()
    infrastructure_output.name.get()
    infrastructure_output.value.get()
    infrastructure_output.value_expression.get()
    infrastructure.with_parameter()
    infrastructure.with_parameter_string_value()
    infrastructure.with_parameter_string_values()
    infrastructure.with_parameter_from_parameter()
    infrastructure.with_parameter_from_connection_string()
    infrastructure.with_parameter_from_output()
    infrastructure.with_parameter_from_reference_expression()
    infrastructure.with_parameter_from_endpoint()
    infrastructure.publish_as_connection_string()
    infrastructure.clear_default_role_assignments()
    infrastructure.get_bicep_identifier()
    infrastructure.is_existing()
    infrastructure.run_as_existing()
    infrastructure.run_as_existing_from_parameters()
    infrastructure.publish_as_existing()
    infrastructure.publish_as_existing_from_parameters()
    infrastructure.as_existing()
    identity = builder.add_azure_user_assigned_identity("resource")
    identity.configure_infrastructure()
    identity.with_parameter()
    identity.with_parameter_string_value()
    identity.with_parameter_string_values()
    identity.with_parameter_from_parameter()
    identity.with_parameter_from_connection_string()
    identity.with_parameter_from_output()
    identity.with_parameter_from_reference_expression()
    identity.with_parameter_from_endpoint()
    identity.publish_as_connection_string()
    identity.clear_default_role_assignments()
    identity.get_bicep_identifier()
    identity.is_existing()
    identity.run_as_existing()
    identity.run_as_existing_from_parameters()
    identity.publish_as_existing()
    identity.publish_as_existing_from_parameters()
    identity.as_existing()
    container.with_environment("INFRA_URL", infrastructure_output)
    container.with_environment("SECRET_FROM_IDENTITY", identity)
    container.with_azure_user_assigned_identity()
    executable.with_environment("INFRA_URL", infrastructure_output)
    executable.with_environment("SECRET_FROM_IDENTITY", identity)
    executable.with_azure_user_assigned_identity()
    builder.run()
