//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class AzureNatGatewayExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureNatGatewayResource> AddNatGateway(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureNatGatewayResource> WithPublicIPAddress(this ApplicationModel.IResourceBuilder<Azure.AzureNatGatewayResource> builder, ApplicationModel.IResourceBuilder<Azure.AzurePublicIPAddressResource> publicIPAddress) { throw null; }
    }

    public static partial class AzureNetworkSecurityGroupExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureNetworkSecurityGroupResource> AddNetworkSecurityGroup(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureNetworkSecurityGroupResource> WithSecurityRule(this ApplicationModel.IResourceBuilder<Azure.AzureNetworkSecurityGroupResource> builder, Azure.AzureSecurityRule rule) { throw null; }
    }

    public static partial class AzureNetworkSecurityPerimeterExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureNetworkSecurityPerimeterResource> AddNetworkSecurityPerimeter(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureNetworkSecurityPerimeterResource> WithAccessRule(this ApplicationModel.IResourceBuilder<Azure.AzureNetworkSecurityPerimeterResource> builder, Azure.AzureNspAccessRule rule) { throw null; }

        [AspireExport("associateWithNetworkSecurityPerimeter", MethodName = "withNetworkSecurityPerimeter")]
        public static ApplicationModel.IResourceBuilder<T> WithNetworkSecurityPerimeter<T>(this ApplicationModel.IResourceBuilder<T> target, ApplicationModel.IResourceBuilder<Azure.AzureNetworkSecurityPerimeterResource> nsp, global::Azure.Provisioning.Network.NetworkSecurityPerimeterAssociationAccessMode accessMode = global::Azure.Provisioning.Network.NetworkSecurityPerimeterAssociationAccessMode.Enforced, string? associationName = null)
            where T : ApplicationModel.IResource, Azure.IAzureNspAssociationTarget { throw null; }
    }

    public static partial class AzurePrivateEndpointExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzurePrivateEndpointResource> AddPrivateEndpoint(this ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> subnet, ApplicationModel.IResourceBuilder<Azure.IAzurePrivateEndpointTarget> target) { throw null; }
    }

    public static partial class AzurePublicIPAddressExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzurePublicIPAddressResource> AddPublicIPAddress(this IDistributedApplicationBuilder builder, string name) { throw null; }
    }

    public static partial class AzureVirtualNetworkExtensions
    {
        [AspireExportIgnore(Reason = "Polyglot app hosts use the internal addAzureVirtualNetwork dispatcher export.")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureVirtualNetworkResource> AddAzureVirtualNetwork(this IDistributedApplicationBuilder builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> addressPrefix) { throw null; }

        [AspireExportIgnore(Reason = "Polyglot app hosts use the internal addAzureVirtualNetwork dispatcher export.")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureVirtualNetworkResource> AddAzureVirtualNetwork(this IDistributedApplicationBuilder builder, string name, string? addressPrefix = null) { throw null; }

        [AspireExportIgnore(Reason = "Polyglot app hosts use the internal addSubnet dispatcher export.")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> AddSubnet(this ApplicationModel.IResourceBuilder<Azure.AzureVirtualNetworkResource> builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> addressPrefix, string? subnetName = null) { throw null; }

        [AspireExportIgnore(Reason = "Polyglot app hosts use the internal addSubnet dispatcher export.")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> AddSubnet(this ApplicationModel.IResourceBuilder<Azure.AzureVirtualNetworkResource> builder, string name, string addressPrefix, string? subnetName = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> AllowInbound(this ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> builder, string? port = null, string? from = null, string? to = null, global::Azure.Provisioning.Network.SecurityRuleProtocol? protocol = null, int? priority = null, string? name = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> AllowOutbound(this ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> builder, string? port = null, string? from = null, string? to = null, global::Azure.Provisioning.Network.SecurityRuleProtocol? protocol = null, int? priority = null, string? name = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> DenyInbound(this ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> builder, string? port = null, string? from = null, string? to = null, global::Azure.Provisioning.Network.SecurityRuleProtocol? protocol = null, int? priority = null, string? name = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> DenyOutbound(this ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> builder, string? port = null, string? from = null, string? to = null, global::Azure.Provisioning.Network.SecurityRuleProtocol? protocol = null, int? priority = null, string? name = null) { throw null; }

        [AspireExport("withSubnetDelegatedSubnet", MethodName = "withDelegatedSubnet")]
        public static ApplicationModel.IResourceBuilder<T> WithDelegatedSubnet<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> subnet)
            where T : Azure.IAzureDelegatedSubnetResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> WithNatGateway(this ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> builder, ApplicationModel.IResourceBuilder<Azure.AzureNatGatewayResource> natGateway) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> WithNetworkSecurityGroup(this ApplicationModel.IResourceBuilder<Azure.AzureSubnetResource> builder, ApplicationModel.IResourceBuilder<Azure.AzureNetworkSecurityGroupResource> nsg) { throw null; }
    }
}

namespace Aspire.Hosting.Azure
{
    public partial class AzureNatGatewayResource : AzureProvisioningResource
    {
        public AzureNatGatewayResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public BicepOutputReference Id { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }
    }

    public partial class AzureNetworkSecurityGroupResource : AzureProvisioningResource
    {
        public AzureNetworkSecurityGroupResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public BicepOutputReference Id { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }
    }

    public partial class AzureNetworkSecurityPerimeterResource : AzureProvisioningResource
    {
        public AzureNetworkSecurityPerimeterResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public BicepOutputReference Id { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }
    }

    [AspireDto]
    public sealed partial class AzureNspAccessRule
    {
        public System.Collections.Generic.List<string> AddressPrefixes { get { throw null; } init { } }

        public System.Collections.Generic.List<ApplicationModel.ReferenceExpression> AddressPrefixReferences { get { throw null; } init { } }

        public required global::Azure.Provisioning.Network.NetworkSecurityPerimeterAccessRuleDirection Direction { get { throw null; } set { } }

        public System.Collections.Generic.List<ApplicationModel.ReferenceExpression> FullyQualifiedDomainNameReferences { get { throw null; } init { } }

        public System.Collections.Generic.List<string> FullyQualifiedDomainNames { get { throw null; } init { } }

        public required string Name { get { throw null; } set { } }

        public System.Collections.Generic.List<ApplicationModel.ReferenceExpression> SubscriptionReferences { get { throw null; } init { } }

        public System.Collections.Generic.List<string> Subscriptions { get { throw null; } init { } }
    }

    public partial class AzurePrivateEndpointResource : AzureProvisioningResource
    {
        public AzurePrivateEndpointResource(string name, AzureSubnetResource subnet, IAzurePrivateEndpointTarget target, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public BicepOutputReference Id { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public AzureSubnetResource Subnet { get { throw null; } }

        public IAzurePrivateEndpointTarget Target { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }
    }

    public partial class AzurePublicIPAddressResource : AzureProvisioningResource
    {
        public AzurePublicIPAddressResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public BicepOutputReference Id { get { throw null; } }

        public BicepOutputReference IpAddress { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }
    }

    [AspireDto]
    public sealed partial class AzureSecurityRule
    {
        public required global::Azure.Provisioning.Network.SecurityRuleAccess Access { get { throw null; } set { } }

        public string? Description { get { throw null; } set { } }

        public string DestinationAddressPrefix { get { throw null; } set { } }

        public ApplicationModel.ReferenceExpression? DestinationAddressPrefixReference { get { throw null; } set { } }

        public required string DestinationPortRange { get { throw null; } set { } }

        public required global::Azure.Provisioning.Network.SecurityRuleDirection Direction { get { throw null; } set { } }

        public required string Name { get { throw null; } set { } }

        public required int Priority { get { throw null; } set { } }

        public required global::Azure.Provisioning.Network.SecurityRuleProtocol Protocol { get { throw null; } set { } }

        public string SourceAddressPrefix { get { throw null; } set { } }

        public ApplicationModel.ReferenceExpression? SourceAddressPrefixReference { get { throw null; } set { } }

        public string SourcePortRange { get { throw null; } set { } }
    }

    public static partial class AzureServiceTags
    {
        [AspireValue("AzureServiceTags")]
        public const string AppService = "AppService";
        [AspireValue("AzureServiceTags")]
        public const string AzureActiveDirectory = "AzureActiveDirectory";
        [AspireValue("AzureServiceTags")]
        public const string AzureContainerRegistry = "AzureContainerRegistry";
        [AspireValue("AzureServiceTags")]
        public const string AzureCosmosDB = "AzureCosmosDB";
        [AspireValue("AzureServiceTags")]
        public const string AzureKeyVault = "AzureKeyVault";
        [AspireValue("AzureServiceTags")]
        public const string AzureLoadBalancer = "AzureLoadBalancer";
        [AspireValue("AzureServiceTags")]
        public const string AzureMonitor = "AzureMonitor";
        [AspireValue("AzureServiceTags")]
        public const string AzureTrafficManager = "AzureTrafficManager";
        [AspireValue("AzureServiceTags")]
        public const string EventHub = "EventHub";
        [AspireValue("AzureServiceTags")]
        public const string GatewayManager = "GatewayManager";
        [AspireValue("AzureServiceTags")]
        public const string Internet = "Internet";
        [AspireValue("AzureServiceTags")]
        public const string ServiceBus = "ServiceBus";
        [AspireValue("AzureServiceTags")]
        public const string Sql = "Sql";
        [AspireValue("AzureServiceTags")]
        public const string Storage = "Storage";
        [AspireValue("AzureServiceTags")]
        public const string VirtualNetwork = "VirtualNetwork";
    }

    [AspireExport]
    public partial class AzureSubnetResource : ApplicationModel.Resource, ApplicationModel.IResourceWithParent<AzureVirtualNetworkResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource
    {
        public AzureSubnetResource(string name, string subnetName, ApplicationModel.ParameterResource addressPrefix, AzureVirtualNetworkResource parent) : base(default!) { }

        public AzureSubnetResource(string name, string subnetName, string addressPrefix, AzureVirtualNetworkResource parent) : base(default!) { }

        public string? AddressPrefix { get { throw null; } }

        public ApplicationModel.ParameterResource? AddressPrefixParameter { get { throw null; } }

        public BicepOutputReference Id { get { throw null; } }

        public AzureVirtualNetworkResource Parent { get { throw null; } }

        public string SubnetName { get { throw null; } }
    }

    public sealed partial class AzureSubnetServiceDelegationAnnotation : ApplicationModel.IResourceAnnotation
    {
        public AzureSubnetServiceDelegationAnnotation(string name, string serviceName) { }

        public string Name { get { throw null; } set { } }

        public string ServiceName { get { throw null; } set { } }
    }

    [AspireExport]
    public partial class AzureVirtualNetworkResource : AzureProvisioningResource
    {
        public AzureVirtualNetworkResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure, ApplicationModel.ParameterResource addressPrefix) : base(default!, default!) { }

        public AzureVirtualNetworkResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure, string? addressPrefix) : base(default!, default!) { }

        public AzureVirtualNetworkResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public string? AddressPrefix { get { throw null; } }

        public ApplicationModel.ParameterResource? AddressPrefixParameter { get { throw null; } }

        public BicepOutputReference Id { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }
    }

    public partial interface IAzurePrivateEndpointTargetNotification : IAzurePrivateEndpointTarget, ApplicationModel.IResource
    {
        void OnPrivateEndpointCreated(ApplicationModel.IResourceBuilder<AzurePrivateEndpointResource> privateEndpoint);
    }
}