# Aspire Python validation AppHost
# Mirrors the top-level TypeScript playground surface with Python-style members.

from aspire_app import create_builder


with create_builder() as builder:
    def update_existing_http_endpoint(endpoint):
        endpoint.port = 8080
        endpoint.is_proxied = False

    def update_endpoint(endpoint):
        endpoint.port = 5001
        endpoint.target_port = 5002
        endpoint.is_external = False

    def update_http_endpoint(endpoint):
        endpoint.port = 8081
        endpoint.target_port = 8082
        endpoint.is_proxied = False

    def update_created_http_endpoint(endpoint):
        endpoint.port = 8083
        endpoint.target_port = 8084
        endpoint.is_proxied = False

    def update_https_endpoint(endpoint):
        endpoint.port = 8444
        endpoint.target_port = 8443
        endpoint.is_proxied = False

    def update_created_https_endpoint(endpoint):
        endpoint.port = 8445
        endpoint.target_port = 8446
        endpoint.is_proxied = False

    def configure_dockerfile_builder(dockerfile_context):
        _dockerfile_resource = dockerfile_context.resource
        _dockerfile_services = dockerfile_context.services
        dockerfile_logger_factory = _dockerfile_services.get_logger_factory()
        dockerfile_logger = dockerfile_logger_factory.create_logger("ValidationAppHost.DockerfileBuilder")
        dockerfile_logger.log_information("Configuring Dockerfile builder")
        dockerfile_builder = dockerfile_context.builder
        dockerfile_builder.arg("BASE_IMAGE", default_value="mcr.microsoft.com/dotnet/runtime:8.0")
        dockerfile_builder.add_container_files_stages(_dockerfile_resource, logger=dockerfile_logger)

        build_stage = dockerfile_builder.from_("mcr.microsoft.com/dotnet/sdk:8.0", stage_name="build")
        build_stage.arg("APP_DIR", default_value="/src")
        build_stage.work_dir("/src")
        build_stage.copy("./src", "/src", chown="1000:1000")
        build_stage.run("echo building dockerfile")
        build_stage.run_with_mounts("echo mounted", ["/tmp:/mnt"])

        runtime_stage = dockerfile_builder.from_("mcr.microsoft.com/dotnet/runtime:8.0", stage_name="runtime")
        runtime_stage.copy_from("build", "/src", "/app", chown="1000:1000")
        runtime_stage.env("ASPIRE_ENV", "Development")
        runtime_stage.expose(8080)
        runtime_stage.cmd(["dotnet", "App.dll"])
        runtime_stage.entrypoint(["dotnet", "App.dll"])
        runtime_stage.user("1000")
        runtime_stage.add_container_files(_dockerfile_resource, "/app", logger=dockerfile_logger)
        runtime_stage.empty_line()
        runtime_stage.comment("Generated by Python polyglot validation")

    # addContainer (pre-existing)
    container = builder.add_container("resource", "image")
    # addDockerfile
    docker_container = builder.add_dockerfile("resource", ".")
    docker_builder_container = builder.add_dockerfile_builder("builder-resource", ".", configure_dockerfile_builder, stage="runtime")
    docker_container.with_dockerfile_builder(".", configure_dockerfile_builder, stage="runtime")
    # addExecutable (pre-existing)
    exe = builder.add_executable("resource", "echo", ".", [])
    # addProject (pre-existing)
    project = builder.add_project("resource", ".", "default")
    # addCSharpApp
    csharp_app = builder.add_c_sharp_app("resource", ".")
    # addRedis
    cache = builder.add_redis("resource")
    # addDotnetTool
    tool = builder.add_dotnet_tool("resource", "package")
    # addParameterFromConfiguration
    config_param = builder.add_parameter_from_config("parameter", "Config:Key")
    secret_param = builder.add_parameter_from_config("parameter", "Config:Key")
    # withDockerfileBaseImage
    container.with_dockerfile_base_image()
    # withImageRegistry
    container.with_image_registry("docker.io")
    # ===================================================================
    docker_container.with_http_endpoint(name="http", target_port=80)
    docker_container.with_http_endpoint_callback(update_existing_http_endpoint, name="http", create_if_not_exists=False)
    endpoint = docker_container.get_endpoint("http")
    expr = "expression"
    built_connection_string = builder.add_connection_string_builder("connection-string", lambda *_args, **_kwargs: None)
    built_connection_string.with_connection_property("Key", "Value")
    built_connection_string.with_connection_property_value("Key", "Value")
    # builder-level pipeline APIs
    pipeline = builder.pipeline

    def configure_builder_step(step_context):
        step_context.summary.add("BuilderPipelineStep", "Validated")

    pipeline.add_step(
        "custom-builder-step",
        configure_builder_step,
        depends_on=["build"],
        required_by=["publish"],
    )

    def configure_builder_pipeline(config_context):
        _all_steps = config_context.steps
        _builder_tagged_steps = config_context.get_steps_by_tag("custom-build")

    pipeline.configure(configure_builder_pipeline)
    # withEnvironment - EndpointReference
    container.with_environment("KEY", endpoint)
    # withEnvironment - ParameterResource
    container.with_environment("KEY", builder.add_parameter("param"))
    # withEnvironment - connection string resource
    container.with_environment("KEY", built_connection_string)
    # withConnectionProperty — with ReferenceExpression
    built_connection_string.with_connection_property("Key", "Value")
    # withConnectionPropertyValue — with string
    built_connection_string.with_connection_property_value("Key", "Value")
    # excludeFromManifest
    container.exclude_from_manifest()
    # excludeFromMcp
    container.exclude_from_mcp()
    # waitForCompletion (pre-existing)
    container.wait_for_completion()
    # withDeveloperCertificateTrust
    container.with_developer_certificate_trust()
    # withCertificateTrustScope
    container.with_certificate_trust_scope()
    # withHttpsDeveloperCertificate
    container.with_https_developer_certificate()
    # withoutHttpsCertificate
    container.without_https_certificate()
    # withChildRelationship
    container.with_child_relationship()
    # withIconName
    container.with_icon_name()
    # withHttpProbe
    container.with_http_probe("liveness")
    # withRemoteImageName
    container.with_remote_image_name()
    # withRemoteImageTag
    container.with_remote_image_tag()
    # withImagePushOptions
    def configure_image_push_options(context):
        options = context.options
        options.remote_image_name = "myregistry.azurecr.io/myapp"
        options.remote_image_tag = "latest"

    container.with_image_push_options(configure_image_push_options)
    # withMcpServer
    container.with_mcp_server()
    # withRequiredCommand
    container.with_required_command("docker")
    # withToolIgnoreExistingFeeds
    tool.with_tool_ignore_existing_feeds()
    # withToolIgnoreFailedSources
    tool.with_tool_ignore_failed_sources()
    # withToolPackage
    tool.with_tool_package()
    # withToolPrerelease
    tool.with_tool_prerelease()
    # withToolSource
    tool.with_tool_source()
    # withToolVersion
    tool.with_tool_version()
    # publishAsDockerFile
    tool.publish_as_docker_file()
    # ===================================================================
    container.with_pipeline_step_factory("step", lambda *_args, **_kwargs: None)
    container.with_pipeline_configuration(lambda *_args, **_kwargs: None)
    container.with_pipeline_configuration(lambda *_args, **_kwargs: None)
    # ===================================================================
    _app_host_directory = builder.app_host_dir
    host_environment = builder.env
    _is_development = host_environment.is_development()
    _is_production = host_environment.is_production()
    _is_staging = host_environment.is_staging()
    _is_specific_environment = host_environment.is_environment()
    builder_configuration = builder.get_configuration()
    _config_value = builder_configuration.get_config_value()
    _connection_string = builder_configuration.get_connection_string()
    _config_section = builder_configuration.get_section()
    _config_children = builder_configuration.get_children()
    _config_exists = builder_configuration.exists()
    builder_execution_context = builder.execution_context
    execution_context_service_provider = builder_execution_context.service_provider
    _distributed_application_model_from_execution_context = execution_context_service_provider.get_distributed_application_model()
    before_start_subscription = builder.subscribe_before_start(lambda *_args, **_kwargs: None)
    after_resources_created_subscription = builder.subscribe_after_resources_created(lambda *_args, **_kwargs: None)
    builder_eventing = builder.eventing
    builder_eventing.unsubscribe(None)
    builder_eventing.unsubscribe(None)
    container.on_before_resource_started(lambda *_args, **_kwargs: None)
    container.on_resource_stopped(lambda *_args, **_kwargs: None)
    built_connection_string.on_connection_string_available(lambda *_args, **_kwargs: None)
    container.on_initialize_resource(lambda *_args, **_kwargs: None)
    container.on_resource_endpoints_allocated(lambda *_args, **_kwargs: None)
    container.on_resource_ready(lambda *_args, **_kwargs: None)
    # withEnvironment
    container.with_environment("KEY", "value")
    # withEndpoint
    container.with_endpoint()
    container.with_endpoint(name="callback-endpoint")
    container.with_endpoint_callback("callback-endpoint", update_endpoint, create_if_not_exists=False)
    # withHttpEndpoint
    container.with_http_endpoint()
    container.with_http_endpoint(name="callback-http")
    container.with_http_endpoint_callback(update_http_endpoint, name="callback-http", create_if_not_exists=False)
    container.with_http_endpoint_callback(update_created_http_endpoint, name="created-http")
    # withHttpsEndpoint
    container.with_https_endpoint()
    container.with_https_endpoint(name="callback-https")
    container.with_https_endpoint_callback(update_https_endpoint, name="callback-https", create_if_not_exists=False)
    container.with_https_endpoint_callback(update_created_https_endpoint, name="created-https")
    # withExternalHttpEndpoints
    container.with_external_http_endpoints()
    # asHttp2Service
    container.as_http2_service()
    # withArgs
    container.with_args()
    # withParentRelationship
    container.with_parent_relationship()
    # withExplicitStart
    container.with_explicit_start()
    # withUrl
    container.with_url("http://localhost")
    # withUrlExpression
    container.with_url_expression("http://localhost")
    # withHttpHealthCheck
    container.with_http_health_check()
    # withCommand
    container.with_command("command", "Command", lambda *_args, **_kwargs: {"success": True})
    # withHttpCommand
    container.with_http_command("/health", "Health Check")
    container.with_http_command("/api/reset", "Reset", options={"MethodName": "POST", "ConfirmationMessage": "Are you sure?"})
    app = builder.build()
    _distributed_app_connection_string = app.get_connection_string()
    _distributed_app_endpoint = app.get_endpoint("default")
    _distributed_app_endpoint_for_network = app.get_endpoint_for_network("resource")
    builder.run()
