# Aspire Python validation AppHost
# Mirrors the top-level TypeScript playground surface with Python-style members.

from aspire_app import AksNodeVmSizes, AzureServiceTags, ReferenceExpression, WellKnownPipelineSteps, WellKnownPipelineTags, create_builder


with create_builder() as builder:
    def update_existing_http_endpoint(endpoint):
        endpoint.port = 8080
        endpoint.is_proxied = False

    def update_endpoint(endpoint):
        endpoint.port = 5001
        endpoint.target_port = 5002
        endpoint.is_external = False

    def update_http_endpoint(endpoint):
        endpoint.port = 8081
        endpoint.target_port = 8082
        endpoint.is_proxied = False

    def update_created_http_endpoint(endpoint):
        endpoint.port = 8083
        endpoint.target_port = 8084
        endpoint.is_proxied = False

    def update_https_endpoint(endpoint):
        endpoint.port = 8444
        endpoint.target_port = 8443
        endpoint.is_proxied = False

    def update_created_https_endpoint(endpoint):
        endpoint.port = 8445
        endpoint.target_port = 8446
        endpoint.is_proxied = False

    def configure_dockerfile_builder(dockerfile_context):
        _dockerfile_resource = dockerfile_context.resource
        _dockerfile_services = dockerfile_context.services
        dockerfile_logger_factory = _dockerfile_services.get_logger_factory()
        dockerfile_logger = dockerfile_logger_factory.create_logger("ValidationAppHost.DockerfileBuilder")
        dockerfile_logger.log_information("Configuring Dockerfile builder")
        dockerfile_builder = dockerfile_context.builder
        dockerfile_builder.arg("BASE_IMAGE", default_value="mcr.microsoft.com/dotnet/runtime:8.0")
        dockerfile_builder.add_container_files_stages(_dockerfile_resource, logger=dockerfile_logger)

        build_stage = dockerfile_builder.from_("mcr.microsoft.com/dotnet/sdk:8.0", stage_name="build")
        build_stage.arg("APP_DIR", default_value="/src")
        build_stage.work_dir("/src")
        build_stage.copy("./src", "/src", chown="1000:1000")
        build_stage.run("echo building dockerfile")
        build_stage.run_with_mounts("echo mounted", ["/tmp:/mnt"])

        runtime_stage = dockerfile_builder.from_("mcr.microsoft.com/dotnet/runtime:8.0", stage_name="runtime")
        runtime_stage.copy_from("build", "/src", "/app", chown="1000:1000")
        runtime_stage.env("ASPIRE_ENV", "Development")
        runtime_stage.expose(8080)
        runtime_stage.cmd(["dotnet", "App.dll"])
        runtime_stage.entrypoint(["dotnet", "App.dll"])
        runtime_stage.user("1000")
        runtime_stage.add_container_files(_dockerfile_resource, "/app", logger=dockerfile_logger)
        runtime_stage.empty_line()
        runtime_stage.comment("Generated by Python polyglot validation")

    def build_connection_string(connection_string_builder):
        _is_empty = connection_string_builder.is_empty
        connection_string_builder.append_literal("Host=")
        connection_string_builder.append_value_provider(endpoint)
        connection_string_builder.append_literal(";Key=")
        connection_string_builder.append_value_provider(secret_param)
        _built_expression = connection_string_builder.build()

    def configure_environment_callback(context):
        _environment_resource = context.resource
        _environment_is_run_mode = context.execution_context.is_run_mode()
        context.log.warning("Environment callback logger")
        context.env.set("MY_CALLBACK_ENDPOINT", endpoint)

    def configure_args_callback(context):
        _args_resource = context.resource
        _args_is_run_mode = context.execution_context.is_run_mode()
        context.log.error("Args callback logger")
        context.args.add("--validation-callback")
        context.args.add(expr)

    def configure_urls_callback(context):
        _urls_resource = context.resource
        _urls_is_run_mode = context.execution_context.is_run_mode()
        callback_endpoint = context.get_endpoint("http")
        context.log.debug("URLs callback logger")
        context.urls.add(ReferenceExpression.format_string("https://%s", callback_endpoint))
        context.urls.add_for_endpoint(callback_endpoint, "/details", display_text="Details")

    # addContainer (pre-existing)
    container = builder.add_container("resource", "image")
    # addDockerfile
    docker_container = builder.add_dockerfile("resource", ".")
    docker_builder_container = builder.add_dockerfile_builder("builder-resource", ".", configure_dockerfile_builder, stage="runtime")
    docker_container.with_dockerfile_builder(".", configure_dockerfile_builder, stage="runtime")
    # addExecutable (pre-existing)
    exe = builder.add_executable("resource", "echo", ".", [])
    # addProject (pre-existing)
    project = builder.add_project("resource", ".", launch_profile_or_options="default")
    # addCSharpApp
    csharp_app = builder.add_c_sharp_app("resource", ".")
    # addRedis
    cache = builder.add_redis("resource")
    # addDotnetTool
    tool = builder.add_dotnet_tool("resource", "package")
    # addParameterFromConfiguration
    config_param = builder.add_parameter_from_config("parameter", "Config:Key")
    secret_param = builder.add_parameter_from_config("parameter", "Config:Key")
    # withDockerfileBaseImage
    container.with_dockerfile_base_image()
    # withImageRegistry
    container.with_image_registry("docker.io")
    # ===================================================================
    docker_container.with_http_endpoint(name="http", target_port=80)
    docker_container.with_http_endpoint_callback(update_existing_http_endpoint, name="http", create_if_not_exists=False)
    endpoint = docker_container.get_endpoint("http")
    expr = ReferenceExpression.format_string("Host=%s", endpoint)
    endpoint_host = endpoint.property("Host")
    endpoint_port = endpoint.property("Port")
    endpoint_url = ReferenceExpression.format_string("http://%s:%s", endpoint_host, endpoint_port)
    built_connection_string = builder.add_connection_string("connection-string", env_var_name_or_expression=expr)
    env_connection_string = builder.add_connection_string("env-connection-string")
    expression_connection_string = builder.add_connection_string("expression-connection-string", env_var_name_or_expression=expr)
    built_connection_string.with_connection_property("Key", "Value")
    built_connection_string.with_connection_property_value("Key", "Value")
    container.with_reference(endpoint)
    container.with_reference("https://example.com/", name="external-uri")
    built_connection_string.with_connection_property("Host", expr)
    built_connection_string.with_connection_property("Mode", "Development")
    vnet = builder.add_azure_virtual_network("vnet", address_prefix="10.0.0.0/16")
    subnet = vnet.add_subnet("web", "10.0.1.0/24")
    subnet.allow_inbound(port="443", from_=AzureServiceTags.AzureLoadBalancer)
    subnet.deny_inbound(from_=AzureServiceTags.Internet)
    aks = builder.add_azure_kubernetes_environment("aks")
    aks.add_node_pool("system", vm_size=AksNodeVmSizes.StandardDSv5.StandardD2sV5)
    # builder-level pipeline APIs
    pipeline = builder.pipeline

    def configure_builder_step(step_context):
        step_context.summary.add("BuilderPipelineStep", "Validated")

    pipeline.add_step(
        "custom-builder-step",
        configure_builder_step,
        depends_on=[WellKnownPipelineSteps.Build],
        required_by=[WellKnownPipelineSteps.Publish],
    )

    def configure_builder_pipeline(config_context):
        config_context.log.info("Builder pipeline configuration logger")
        builder_pipeline = config_context.pipeline
        _all_steps = list(builder_pipeline.steps())
        _builder_tagged_steps = config_context.get_steps("custom-build")

    pipeline.configure(configure_builder_pipeline)

    def configure_resource_pipeline(config_context):
        config_context.log.info("Pipeline configuration logger")
        config_pipeline = config_context.pipeline
        all_steps = list(config_pipeline.steps())
        tagged_steps = list(config_pipeline.steps_by_tag(WellKnownPipelineTags.BuildCompute))
        _step_name = all_steps[0].name
        _description = all_steps[0].description
        all_steps[0].add_tag("validated")
        all_steps[0].depends_on("restore")
        tagged_steps[0].required_by(WellKnownPipelineSteps.Publish)
        all_steps[0].depends_on(WellKnownPipelineSteps.Build)

    def capture_resource_pipeline(config_context):
        config_pipeline = config_context.pipeline
        _resource_steps = list(config_pipeline.steps())
        _tagged_steps = list(config_pipeline.steps_by_tag(WellKnownPipelineTags.BuildCompute))
    # withEnvironment - EndpointReference
    container.with_environment("MY_ENDPOINT", endpoint)
    # withEnvironment - ParameterResource
    container.with_environment("MY_PARAM", builder.add_parameter("param"))
    # withEnvironment - endpoint property expression
    container.with_environment("MY_ENDPOINT_URL", endpoint_url)
    # withEnvironment - connection string resource
    container.with_environment("MY_CONN", env_connection_string)
    container.with_environment("MY_EXPR_CONN", expression_connection_string)
    container.with_env_callback(configure_environment_callback)
    container.with_args_callback(configure_args_callback)
    container.with_urls_callback(configure_urls_callback)
    # withConnectionProperty — with ReferenceExpression
    built_connection_string.with_connection_property("Endpoint", expr)
    # withConnectionProperty — with string
    built_connection_string.with_connection_property("Protocol", "https")
    # excludeFromManifest
    container.exclude_from_manifest()
    # excludeFromMcp
    container.exclude_from_mcp()
    # waitForCompletion (pre-existing)
    container.wait_for_completion()
    # withDeveloperCertificateTrust
    container.with_developer_certificate_trust()
    # withCertificateTrustScope
    container.with_certificate_trust_scope()
    # withHttpsDeveloperCertificate
    container.with_https_developer_certificate()
    # withoutHttpsCertificate
    container.without_https_certificate()
    # withChildRelationship
    container.with_child_relationship()
    # withIconName
    container.with_icon_name()
    # withHttpProbe
    container.with_http_probe("liveness")
    # withRemoteImageName
    container.with_remote_image_name()
    # withRemoteImageTag
    container.with_remote_image_tag()
    # withImagePushOptions
    def configure_image_push_options(context):
        options = context.options
        options.remote_image_name = "myregistry.azurecr.io/myapp"
        options.remote_image_tag = "latest"

    container.with_image_push_options(configure_image_push_options)
    # withMcpServer
    container.with_mcp_server()
    # withRequiredCommand
    container.with_required_command("docker")
    # withToolIgnoreExistingFeeds
    tool.with_tool_ignore_existing_feeds()
    # withToolIgnoreFailedSources
    tool.with_tool_ignore_failed_sources()
    # withToolPackage
    tool.with_tool_package()
    # withToolPrerelease
    tool.with_tool_prerelease()
    # withToolSource
    tool.with_tool_source()
    # withToolVersion
    tool.with_tool_version()
    # publishAsDockerFile
    tool.publish_as_docker_file()
    # ===================================================================
    container.with_pipeline_step_factory(
        "custom-build-step",
        lambda *_args, **_kwargs: None,
        depends_on=[WellKnownPipelineSteps.Build],
        required_by=[WellKnownPipelineSteps.Deploy],
        tags=[WellKnownPipelineTags.BuildCompute],
        description="Custom pipeline step",
    )
    container.with_pipeline_configuration(configure_resource_pipeline)
    container.with_pipeline_configuration(capture_resource_pipeline)
    # ===================================================================
    _app_host_directory = builder.app_host_dir
    host_environment = builder.env
    _is_development = host_environment.is_development()
    _is_production = host_environment.is_production()
    _is_staging = host_environment.is_staging()
    _is_specific_environment = host_environment.is_environment()
    builder_configuration = builder.get_configuration()
    _config_value = builder_configuration.get_config_value()
    _connection_string = builder_configuration.get_connection_string()
    _config_section = builder_configuration.get_section()
    _config_children = builder_configuration.get_children()
    _config_exists = builder_configuration.exists()
    builder_execution_context = builder.execution_context
    execution_context_service_provider = builder_execution_context.service_provider
    _distributed_application_model_from_execution_context = execution_context_service_provider.get_distributed_app_model()

    def configure_eventing_subscriber(registration_context):
        _subscriber_execution_context = registration_context.execution_context

        def on_eventing_before_start(before_start_event):
            subscriber_services = before_start_event.services
            aspire_store = subscriber_services.get_aspire_store()
            _content_backed_filename = aspire_store.get_file_name_with_content("validation-apphost.py", "apphost.py")

        def on_eventing_after_resources_created(after_resources_created_event):
            after_resources_created_services = after_resources_created_event.services
            after_resources_created_model = after_resources_created_event.model
            _after_resources_created_eventing = after_resources_created_services.get_eventing()
            _after_resources_created_resources = after_resources_created_model.get_resources()

        registration_context.on_before_start(on_eventing_before_start)
        registration_context.on_after_resources_created(on_eventing_after_resources_created)

    builder.add_eventing_subscriber(configure_eventing_subscriber)
    builder.try_add_eventing_subscriber(lambda _registration_context: None)

    container.with_args(["--validation"])

    def configure_certificate_trust(requested_trust_scope):
        _requested_trust_scope = requested_trust_scope
        return {
            "CertificateBundlePath": ReferenceExpression.format_string("/etc/ssl/certs/custom-bundle.pem"),
            "CertificateDirectoriesPath": ReferenceExpression.format_string("/etc/ssl/certs/custom"),
            "RootCertificatesPath": "/etc/ssl/certs",
            "IsContainer": True,
        }

    def configure_https_certificate(certificate_info):
        _certificate_subject = certificate_info.get("Subject")
        _certificate_thumbprint = certificate_info.get("Thumbprint")
        return {
            "CertificatePath": ReferenceExpression.format_string("/certificates/tls.crt"),
            "KeyPath": ReferenceExpression.format_string("/certificates/tls.key"),
            "PfxPath": ReferenceExpression.format_string("/certificates/tls.pfx"),
        }

    execution_config_builder = container.create_execution_config()
    execution_config_builder.with_arguments_config()
    execution_config_builder.with_env_vars_config()
    execution_config_builder.with_certificate_trust_config(configure_certificate_trust)
    execution_config_builder.with_https_certificate_config(configure_https_certificate)
    execution_config = execution_config_builder.build(builder_execution_context)
    _certificate_trust_data = execution_config.get_certificate_trust_data()
    _https_certificate_data = execution_config.get_https_certificate_data()
    before_start_subscription = builder.subscribe_before_start(lambda *_args, **_kwargs: None)
    after_resources_created_subscription = builder.subscribe_after_resources_created(lambda *_args, **_kwargs: None)
    builder_eventing = builder.eventing
    builder_eventing.unsubscribe(None)
    builder_eventing.unsubscribe(None)
    container.on_before_resource_started(lambda *_args, **_kwargs: None)
    container.on_resource_stopped(lambda *_args, **_kwargs: None)
    built_connection_string.on_connection_string_available(lambda *_args, **_kwargs: None)
    container.on_initialize_resource(lambda *_args, **_kwargs: None)
    container.on_resource_endpoints_allocated(lambda *_args, **_kwargs: None)
    container.on_resource_ready(lambda *_args, **_kwargs: None)
    # withEnvironment
    container.with_environment("KEY", "value")
    # withEndpoint
    container.with_endpoint()
    container.with_endpoint(name="callback-endpoint")
    container.with_endpoint_callback("callback-endpoint", update_endpoint, create_if_not_exists=False)
    # withHttpEndpoint
    container.with_http_endpoint()
    container.with_http_endpoint(name="callback-http")
    container.with_http_endpoint_callback(update_http_endpoint, name="callback-http", create_if_not_exists=False)
    container.with_http_endpoint_callback(update_created_http_endpoint, name="created-http")
    # withHttpsEndpoint
    container.with_https_endpoint()
    container.with_https_endpoint(name="callback-https")
    container.with_https_endpoint_callback(update_https_endpoint, name="callback-https", create_if_not_exists=False)
    container.with_https_endpoint_callback(update_created_https_endpoint, name="created-https")
    # withExternalHttpEndpoints
    container.with_external_http_endpoints()
    # asHttp2Service
    container.as_http2_service()
    # withArgs
    container.with_args()
    # withParentRelationship
    container.with_parent_relationship()
    # withExplicitStart
    container.with_explicit_start()
    # withUrl
    container.with_url("http://localhost")
    # withUrl - ReferenceExpression
    container.with_url(ReferenceExpression.format_string("http://localhost"))
    # withHttpHealthCheck
    container.with_http_health_check()
    # withCommand
    container.with_command("command", "Command", lambda *_args, **_kwargs: {"success": True})
    # withHttpCommand
    container.with_http_command("/health", "Health Check")
    container.with_http_command("/api/reset", "Reset", options={"MethodName": "POST", "ConfirmationMessage": "Are you sure?"})
    app = builder.build()
    _distributed_app_connection_string = app.get_connection_string()
    _distributed_app_endpoint = app.get_endpoint("default")
    _distributed_app_endpoint_for_network = app.get_endpoint_for_network("resource")
    builder.run()
