<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>02bbcc01-7921-4f54-9a52-7a711f3fe1f4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <AspireProjectOrPackageReference Include="Aspire.Hosting.AppHost" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.Rust" />
  </ItemGroup>

</Project>
