<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageTags>aspire integration hosting valkey cache caching</PackageTags>
    <Description>Valkey® support for Aspire.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SharedDir)ContainerReplCommand.cs" Link="Utils\ContainerReplCommand.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire.Hosting\Aspire.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Aspire.Hosting.Valkey.Tests" />
  </ItemGroup>

</Project>
