name: Build Packages (Reusable)

on:
  workflow_call:
    inputs:
      versionOverrideArg:
        required: false
        type: string

jobs:
  build_packages:
    name: Build packages
    runs-on: 8-core-ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build with packages
        run: ./build.sh -restore -build -ci -pack -bl -p:InstallBrowsersForPlaywright=false -p:SkipTestProjects=true -p:SkipPlaygroundProjects=true -p:SkipBundleDeps=true ${{ inputs.versionOverrideArg }}

      - name: Clean up artifacts
        run: |
          rm -rf artifacts/bin
          rm -rf artifacts/obj

      - name: Upload built NuGets
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: built-nugets
          path: artifacts/packages
          if-no-files-found: error
          retention-days: 15

      # Always upload logs, even if the build fails, to enable debugging
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build_packages_logs
          path: artifacts/log
          retention-days: 5

