#!/usr/bin/env bash
set -euo pipefail

display_path="extension/CHANGELOG.md"
changelog_path="${1:-$display_path}"
pending_marker_prefix='<!-- aspire-ext-changelog from='
finalized_marker_prefix_regex='<!-- aspire-ext-changelog-(finalized|done) from='
finalized_marker_regex='^<!-- aspire-ext-changelog-(finalized|done) from=([0-9a-f]{40}) to=([0-9a-f]{40}) base=[^>]* -->$'
restore_and_retrigger_guidance="Restore the pending placeholder entry, update the release branch if needed, and re-add the \`vscode-extension-release\` label to retrigger the placeholder workflow."

if [[ ! -f "$changelog_path" ]]; then
  printf '%s\n' "::error file=$display_path,title=Finalize VS Code extension changelog::Expected $display_path to exist."
  exit 1
fi

find_placeholder_line() {
  local placeholder="$1"
  local file="$2"
  local match

  match="$(grep -Fn -m 1 "$placeholder" "$file" || true)"
  if [[ -z "$match" ]]; then
    return 1
  fi

  printf '%s' "${match%%:*}"
}

emit_placeholder_error() {
  local line="$1"
  local reason="$2"

  printf '%s\n' "::error file=$display_path,line=$line,title=Finalize VS Code extension changelog::$display_path still contains $reason. Replace the placeholder with finalized release notes before merging."
}

emit_release_error() {
  local line="$1"
  local reason="$2"

  printf '%s\n' "::error file=$display_path,line=$line,title=Finalize VS Code extension changelog::$reason $restore_and_retrigger_guidance"
}

is_release_branch_pr() {
  [[ "${PR_HEAD_REF:-}" == extension-release/* && "${PR_BASE_REF:-}" == "main" ]]
}

extract_package_version() {
  local version_line

  # The release branch package.json contains a line like:
  #   "version": "1.99.0"
  # Extract it from the checked-in file without depending on jq in the gate environment.
  version_line="$(grep -m 1 -E '"version"[[:space:]]*:[[:space:]]*"[^"]+"' extension/package.json || true)"
  if [[ -z "$version_line" ]]; then
    return 1
  fi

  printf '%s\n' "$version_line" | sed -E 's/.*"version"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/'
}

extract_section_after_heading() {
  local heading="$1"
  local file="$2"

  awk -v heading="$heading" '
    $0 == heading { in_section = 1; next }
    in_section && /^## / { exit }
    in_section { print }
  ' "$file"
}

extract_section_after_heading_with_line_numbers() {
  local heading="$1"
  local file="$2"

  awk -v heading="$heading" '
    $0 == heading { in_section = 1; next }
    in_section && /^## / { exit }
    in_section { printf "%d\t%s\n", NR, $0 }
  ' "$file"
}

if line="$(find_placeholder_line "$pending_marker_prefix" "$changelog_path")"; then
  emit_placeholder_error "$line" "the pending release-notes marker"
  exit 1
fi

if line="$(find_placeholder_line '_Release notes are being generated automatically' "$changelog_path")"; then
  emit_placeholder_error "$line" "autogenerated placeholder prose"
  exit 1
fi

if ! is_release_branch_pr; then
  printf '%s\n' "$display_path is finalized."
  exit 0
fi

if [[ ! -f extension/package.json ]]; then
  printf '%s\n' "::error file=extension/package.json,title=Finalize VS Code extension changelog::Expected extension/package.json to exist for an extension release PR. $restore_and_retrigger_guidance"
  exit 1
fi

current_version="$(extract_package_version)" || {
  printf '%s\n' "::error file=extension/package.json,title=Finalize VS Code extension changelog::Could not read the current extension/package.json version for this release PR. $restore_and_retrigger_guidance"
  exit 1
}

version_heading="## v${current_version}"
heading_line_match="$(grep -Fn -m 1 "$version_heading" "$changelog_path" || true)"
if [[ -z "$heading_line_match" ]]; then
  printf '%s\n' "::error file=$display_path,title=Finalize VS Code extension changelog::Could not find the current release heading '$version_heading'. $restore_and_retrigger_guidance"
  exit 1
fi

heading_line_number="${heading_line_match%%:*}"
current_section="$(extract_section_after_heading "$version_heading" "$changelog_path")"
current_section_with_line_numbers="$(extract_section_after_heading_with_line_numbers "$version_heading" "$changelog_path")"

mapfile -t finalized_markers < <(printf '%s\n' "$current_section_with_line_numbers" | grep -E "$finalized_marker_prefix_regex" || true)
if [[ "${#finalized_markers[@]}" -ne 1 ]]; then
  emit_release_error "$heading_line_number" "Expected exactly one finalized release marker in the current release entry for $version_heading."
  exit 1
fi

finalized_marker_entry="${finalized_markers[0]}"
IFS=$'\t' read -r finalized_marker_line_number finalized_marker_line <<< "$finalized_marker_entry"

if [[ ! "$finalized_marker_line" =~ ${finalized_marker_regex} ]]; then
  emit_release_error "$finalized_marker_line_number" "The finalized release marker is malformed: $finalized_marker_line."
  exit 1
fi

from_sha="${BASH_REMATCH[2]}"
to_sha="${BASH_REMATCH[3]}"

if ! printf '%s\n' "$current_section" | grep -Fxq "$finalized_marker_line"; then
  emit_release_error "$heading_line_number" "The current release section $version_heading must contain the finalized release marker."
  exit 1
fi

if ! printf '%s\n' "$current_section" | grep -Eq '^- .*[^[:space:]]'; then
  emit_release_error "$heading_line_number" "The current release section $version_heading must contain at least one '- ' release-note bullet with non-whitespace content."
  exit 1
fi

if ! git cat-file -e "${to_sha}^{commit}" 2>/dev/null; then
  emit_release_error "$finalized_marker_line_number" "The finalized release marker references a missing 'to' SHA: $to_sha."
  exit 1
fi

if [[ -z "${PR_BASE_SHA:-}" ]]; then
  emit_release_error "$finalized_marker_line_number" "The workflow did not provide the current PR base SHA for stale-range validation."
  exit 1
fi

if ! git cat-file -e "${PR_BASE_SHA}^{commit}" 2>/dev/null; then
  emit_release_error "$finalized_marker_line_number" "The workflow provided an unreadable PR base SHA: ${PR_BASE_SHA}."
  exit 1
fi

if ! git merge-base --is-ancestor "$to_sha" "$PR_BASE_SHA" 2>/dev/null; then
  emit_release_error "$finalized_marker_line_number" "Finalized changelog range ends at $to_sha, but the current PR base $PR_BASE_SHA does not descend from it."
  exit 1
fi

if [[ -n "$(git diff --name-only "${to_sha}..${PR_BASE_SHA}" -- extension/)" ]]; then
  emit_release_error "$finalized_marker_line_number" "Finalized changelog range ends at $to_sha, but the current PR base $PR_BASE_SHA contains newer extension/ changes."
  exit 1
fi

printf '%s\n' "$display_path is finalized."
