name: "Copilot Setup Steps"

# Allow testing of the setup steps from your repository's "Actions" tab.
on: workflow_dispatch

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ${{ github.repository_owner == 'microsoft' && '8-core-ubuntu-latest' || 'ubuntu-latest' }}

    permissions:
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Install gh aw to enable GitHub Copilot Agent integration
      - name: Install gh-aw extension
        uses: github/gh-aw-actions/setup-cli@81b86c58b134601fc10d4745e276d7861cd12911 # v0.69.0
        with:
          version: v0.69.0

      - name: Build solution
        # a full build is too slow; also do not fail on errors, continue so that
        # copilot can attempt to recover
        run: ./build.sh -restore || true

      # Install verify tool for snapshot testing
      - name: Install verify tool
        run: ./dotnet.sh tool install --global Verify.Tool --version 0.6.0 || true

      - name: Setup PATH
        run:
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          echo "$PWD/.dotnet/" >> $GITHUB_PATH

      # For MCP servers like nuget's
      - name: Install .NET 10.x
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: |
            10.x
          dotnet-quality: preview

      # for MCP servers
      - name: Install .NET 8.x
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: |
            8.x

      # Diagnostics in the log
      - name: dotnet --info
        run: dotnet --info
